### ISSUE TITLE
[Candidate 1v1 [NMC] Plant Waste v2] Top base has wrong headquarter rotation

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#120]
**Issue Description**
Top base has wrong custom headquarter rotation.

**Expected behavior**
Top base headquarter has default rotation.

**Screenshots**
![shot_20210328_140428_9](https://user-images.githubusercontent.com/4720891/112751519-d389f200-8fce-11eb-9b64-6892ee022f19.jpg)

![shot_20210328_140425_8](https://user-images.githubusercontent.com/4720891/112751525-d7b60f80-8fce-11eb-8ab3-68b1a95d6705.jpg)

**Comment by Jundiyy** [comment]
This is normal for Laser General AI, it does this, unless some map.ini has been used to force the Command Centre to rotate.

**Comment by xezon** [comment]
AI game issue.
