### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] Main supply cannot be boxed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#126]
**Issue Description**
Main supply cannot be boxed. As designed?

**Screenshots**
![shot_20210330_103440_15](https://user-images.githubusercontent.com/4720891/112960535-cdb61d00-9144-11eb-968a-f198864db2fe.jpg)

**Comment by xezon** [comment]
For it to be boxed, there probably would have to be some rocks or other structures at the bottom/top of the map to form a real barrier.

**Comment by xezon** [comment]
Does this side work correctly for GLA workers and China trucks?

**Comment by Millard9** [comment]
yes tested with logica before it was v1 and he was happy, by all means if you find a bug please let me know
