### ISSUE TITLE
[Release 1v1 [RANK] ZH Carrier is Over v2] Player is unable to see terrain at all map borders (bottom)

### ISSUE THREAD

**Issue by RisingZH** [TheSuperHackers/GeneralsRankedMaps#13]
Field of view - top

**Comment by cncHD** [comment]
I dont see an issue here. Many maps have that problem and in all these years there has never been an issue with it, especialy with tournament desert. It could be avoided in future maps, yes, but it is not a „bug“ Im going to fix in the current maps

**Comment by xezon** [comment]
I checked map and bug is valid, however it is not critical and does not require new version. If there is a v3 of this map, then this would be nice to be fixed.

Default camera boundary:
![shot_20210227_104845_1](https://user-images.githubusercontent.com/4720891/109384324-58102480-78ec-11eb-9edf-23a9c8fd453f.jpg)

Changed camera boundary:
![shot_20210227_104856_2](https://user-images.githubusercontent.com/4720891/109384336-68280400-78ec-11eb-8807-60a9a3a414ca.jpg)

Trying to hide unit:
![shot_20210227_110305_3](https://user-images.githubusercontent.com/4720891/109384346-724a0280-78ec-11eb-9cf1-c2d9038057f5.jpg)

**Comment by RisingZH** [comment]
Ah, so you don't need to change the terrain at all, you can just change the camera boundary?

**Comment by xezon** [comment]
The camera boundary is altered when using Numpad 8 to zoom in. Then when pressing Numpad 5 the camera goes back to max height but camera boundary is not reverted. This is a bug.

I was hoping camera boundary can be set in World Builder. But maybe its automatic to boundaries of map. But then maybe boundary of map can be increased and moveable area can be decreased to mitigate problem.

**Comment by Jundiyy** [comment]
> Ah, so you don't need to change the terrain at all, you can just change the camera boundary?

I mentioned this twice in the map topic lol, maybe you missed it. If you reset it at the start of the game, you can move up and down further on the map.

**Comment by Jundiyy** [comment]
I think this can be closed? I don't think cncHD plans to do anything and personally I don't think there is anything to do.
