### ISSUE TITLE
[Candidate 3v3 Subjugation Mk 14 [WBC Winner]] map.str contains script messages. Are there custom event scripts on map?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#134]
**Issue Description**
map.str contains script messages. Are there custom event scripts on map?

```
SCRIPT:Sell your Demo Trap to vote against the Firefly FX
"Sell your Demo Trap to vote against the Firefly FX"
End

SCRIPT:Vote Number
"Number of votes not counted"
End

SCRIPT:Vote Count
"Vote tally x2"
End

At least half did not sell their Demos, the Fireflies will remain
"At least half did not sell their Demos, the Fireflies will remain"
End

More than half sold their Demos, the Fireflies will be removed
"More than half sold their Demos, the Fireflies will be removed"
End
```

**Expected behavior**
No event scripts in ranked maps.

**Comment by Jundiyy** [comment]
This was in a previous version of this map, I'm quite sure the mapper removed this for it to become WBC winner, he is already planning to edit this map himself but I will mention to him to remove these text files.

**Comment by Jundiyy** [comment]
He has confirmed that these scripts no longer work.
