### ISSUE TITLE
[Candidate 3v3 Naval Port Reyes [WBC Winner]] map.str contains script messages. Are there custom event scripts on map?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#135]
**Issue Description**
map.str contains script messages. Are there custom event scripts on map?

```
SCRIPT:DynamicWater
"Extra Paths will be open In:"
End
```

**Expected behavior**
Map contains no custom events scripts.

**Comment by Jundiyy** [comment]
This was in a previous version, quite certain it was removed.

**Comment by Jundiyy** [comment]
He just confirmed it.
