### ISSUE TITLE
[Candidate 1v1 Arab Tradegy ZHv3] Unsafe supply piles are spread to far apart of each other

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#15]
**Describe the bug**
Unsafe supply piles are spread to far apart of each other.

**Expected behavior**
Supply piles are placed closer together. Better for GLA and China.

**Comment by SpeCoV1k** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
why can't you list all the errors in one place ????
I have already made a new version with corrected lighting and water - but I just noticed this topic. This is VERY inconvenient!

**Comment by xezon** [comment]
Yeah as of right now you need to look through all bugs on all pages and search for map name to find all bugs for a map. It's not ideal but it's ok. Bugs need to be separate otherwise we cannot close single issues when fixed.

**Comment by xezon** [comment]
This map has 8 issue reports right now.

**Comment by xezon** [comment]
Is this a problem?

![shot_20210417_102235_11](https://user-images.githubusercontent.com/4720891/115106786-edcc4580-9f66-11eb-88e4-c21b4ce63042.jpg)

![shot_20210417_102245_12](https://user-images.githubusercontent.com/4720891/115106793-f7ee4400-9f66-11eb-8c3d-f90050b4b08f.jpg)

**Comment by Jundiyy** [comment]
In my opinion I think it would be best so make them closer together, as soon as GLA or China finishes collecting from 1 or 2 piles, they have to start doing long distance, which I think for a base supply is not good. For USA this is no problem.
![01](https://user-images.githubusercontent.com/79164303/115657167-5b44f100-a32e-11eb-80ff-64d4dd15ab0f.PNG)
Or like this
![02](https://user-images.githubusercontent.com/79164303/115657181-5f710e80-a32e-11eb-9a6b-5c4cc28ea9de.PNG)

Issue #21 has not been fixed.
This also applies for the bottom pad.

**Comment by xezon** [comment]
@Jundiyy please provide image for issue #21 because no one knows what you mean.

**Comment by kABUSE1** [comment]
I closed #21 as it is covered in #158 and the map is being overhauled by Lyo.

**Comment by TKLyo** [comment]
I'm taking over

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/4638621dc9bead2f455e04457ce248ad8f6526b4
