### ISSUE TITLE
[Candidate 4v4 Dusty Rampage v3] Title text does not name author of map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#155]
**Issue Description**
Title text does not name author of map.

**Expected behavior**
Title text names original author of map.

**Screenshots**
![shot_20210417_103241_14](https://user-images.githubusercontent.com/4720891/115107167-751ab880-9f69-11eb-90c6-cc237c705625.jpg)

**Comment by Newgate-M17** [comment]
The original creator is unknown
