### ISSUE TITLE
[Candidate 1v1 ButterbroT ZH v3] Map needs a bridge

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#16]
**Describe the bug**
Map has no bridge.

**Expected behavior**
Map has a bridge. Please refer to Rising for more information.

**Comment by SpeCoV1k** [comment]
returned the bridge back to where it was in version 1: https://www.gamereplays.org/community/uploads/post-103811-1617454099.png
+ change lightning and add light rain after 3 min game.
and change water. 
It was https://www.gamereplays.org/community/uploads/post-103811-1617454260.png
became https://www.gamereplays.org/community/uploads/post-103811-1617454093.png

map dL: https://www.gamereplays.org/community/index.php?act=Attach&type=post&id=861803

**Comment by xezon** [comment]
@RisingZH

**Comment by Jundiyy** [comment]
Why is this even being brought up? Forest of Oblivion is the later version and it has a bridge.
I'm sure I already mentioned this in the staff topic.

**Comment by xezon** [comment]
I don't know what the issue is. Some images of it would be good.

**Comment by xezon** [comment]
So we remove this map right?

**Comment by RisingZH** [comment]
Sorry this is my fault. 

I was meaning with my comment that I didn’t like this version and preferred the existing version with the bridge (which I knew was already ranked but couldn’t remember the name). As Jundiyy says it’s called Forest of Oblivion.

So yeah I’d just remove Butterbrot.

**Comment by Jundiyy** [comment]
Yes correct, as Rising said, remove.

@Rising, ah okay makes sense.

**Comment by SpeCoV1k** [comment]
https://disk.yandex.ru/d/yc_37D9IIvnkzg its same that i load 24 days ago, just rename Forest of Oblivion ZH v2
