### ISSUE TITLE
[Candidate 4v4 Dusty Rampage v4] Top side of map has 2 oils but bottom side does not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#180]
**Issue Description**
Top side of map has 2 oils but bottom side does not. Is this as designed?

![shot_20210429_224815_8](https://user-images.githubusercontent.com/4720891/116616607-2bed4000-a93d-11eb-8493-22508c98ad26.jpg)
![shot_20210429_224820_9](https://user-images.githubusercontent.com/4720891/116616610-2c85d680-a93d-11eb-9673-f1f6017df6ac.jpg)

**Comment by mp36660** [comment]
It is designed, yes.
