### ISSUE TITLE
[Release 1v1 [RANK] A New Tragedy ZH v1] Replay playback does not work correctly

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#184]
**Issue Description**
Replay playback does not work correctly. Radar is not visible. FPS is not locked to 30.

**Expected behavior**
Replay playback works correctly.

**Screenshots**
![shot_20210503_194855_1](https://user-images.githubusercontent.com/4720891/116913109-5dba1b80-ac49-11eb-87d5-a7c3ec9efaee.jpg)

**Comment by MTKing4** [comment]
the 30 FPS was because i ran it through skirmish on 100 FPS, i tried the map from network the replay from there works just fine on 30 FPS

nothing wrong with the map on that regard

**Comment by xezon** [comment]
Maybe map boundary issue. May require hex editing to fix @kABUSE1

**Comment by Jundiyy** [comment]
If I remembere correctly, this map has 2 boundaries, and the new one was used rather than the original. When switched back, the replays started working.
I didn't test it myself but remember someone mentioning it on GR.

**Comment by xezon** [comment]
Apparently fixed here.
[A_New_Tragedy_ZH_v2.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/8702336/A_New_Tragedy_ZH_v2.zip)

**Comment by xezon** [comment]
Is fixed in new version.
