### ISSUE TITLE
[Candidate 1v1 Entropy's Empire ZH v2] Map name contains apostrophe symbol

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#188]
**Issue Description**
"Entropy's Empire ZH v2" contains apostrophe symbol.

**Expected behavior**
Map name does not contain apostrophe symbol. Should contain alpha numeric only (apart from [] for [RANK]).

**Comment by DoMiNaToRuk2** [comment]
Please remove that symbol
