### ISSUE TITLE
[Candidate 1v1 Alfie's Haven ZH v1] Map name contains apostrophe symbol

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#189]
**Issue Description**
"Alfie's Haven ZH v1" contains apostrophe symbol.

**Expected behavior**
Map name does not contain apostrophe symbol. Should contain alpha numeric only (apart from [] for [RANK]).

**Comment by DoMiNaToRuk2** [comment]
Please remove that symbol
