### ISSUE TITLE
[Candidate 1v1 [NMC] Plant Waste v2] Bunker at the bottom of the map has an unspecified problem

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#19]
**Describe the bug**
Bunker at the bottom of the map has an unspecified problem. Please refer to Jundiyy for more information.

**Comment by xezon** [comment]
Map has been moved to back log. Cannot be used.

**Comment by SpeCoV1k** [comment]
https://img5.goodfon.ru/original/2474x1650/b/42/zima-derevia-zakat-solntse-vid-ozero.jpg
http://fotorelax.ru/wp-content/uploads/2016/02/Beautiful-winter-photos-02.jpg

I don’t know how things are with xezon’s sunset, but in my city in winter at sunset the buildings are painted pink like in these two pictures - so the color I set in the game is realistic ;)
