### ISSUE TITLE
[Candidate 2v2 Diamond's Edge ZH v1] Map name contains apostrophe symbol

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#190]
**Issue Description**
"Diamond's Edge ZH v1" contains apostrophe symbol.

**Expected behavior**
Map name does not contain apostrophe symbol. Should contain alpha numeric only (apart from [] for [RANK]).

**Comment by DoMiNaToRuk2** [comment]
Please remove that symbol

**Comment by xezon** [comment]
The ones with apostrophe, would it perhaps make sense to rename them as

* Edge of Diamond
* Empire of Entropy

?
