### ISSUE TITLE
[Candidate 3v3 Aeon of ExCaL ZH v5] Map name contains player name

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#191]
**Issue Description**
"Aeon of ExCaL ZH v5" contains player name.

**Expected behavior**
Map names do not contain exclusive player names.

**Comment by DoMiNaToRuk2** [comment]
This was not a rule listed for ranked maps, at this point we are just making up rules on the spot. I personally don't see any player having any issue at any point in time with the name of this map. We are making an issue from nothing. Please let's go ahead

**Comment by xezon** [comment]
Rules contains these 2:

> Has no graphics that belong to real or fictional characters, groups, organizations

> Map name fits the naming style of Official Maps

The reason for this is to have uniform and neutral map names that fit well together and do not stand out from one another.

So for example one would not be presented the following map list

* Blossoming Valley
* Green Pastures
* Aeon of ExCaL
* Snowy Drought
* Manic Aggression

It does not fit the tone of the other maps.

If the map name cannot be fixed, then we can reject this map and put it in back log.

**Comment by DoMiNaToRuk2** [comment]
Ok can we name it Aeon of Excalibur?

**Comment by xezon** [comment]
That would work yes.

**Comment by DoMiNaToRuk2** [comment]
Ok pls do it :)
