### ISSUE TITLE
[Candidate 1v1 Morning Dew ZH v7] Map name collides with Morning Dew ZH v7 from 2v2 bundle

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#192]
**Issue Description**
2 maps share the same name: Morning Dew ZH v7

**Expected behavior**
Every map has a unique name.

**Comment by DoMiNaToRuk2** [comment]
It's a 2v2 map so I removed the map from 1v1 folder on google drive. It was duplicate. Please go ahead with 2v2 map

**Comment by xezon** [comment]
ok
