### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] Map name is similar to Dominance ZH v1

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#193]
**Issue Description**
Dominion ZH v1 and Dominance ZH v1 read very similar.

**Expected behavior**
Ideally names are clearly different. Perhaps names can be modified such as

* Godly Dominance
* Due Dominion

so that they are easier to tell apart.

**Comment by DoMiNaToRuk2** [comment]
Ok please change dominion to Cute Dominion

**Comment by NoMerciBKK** [comment]
As one of the Mappers of this Map we wanna stick to the name Dominion cause its based on the League of Legends map Dominion also the map Dominance is not in the current Ranked sections as far as i know.

**Comment by xezon** [comment]
Ok. Will be renamed to Dominion.

Dominance is here, also an 8 player map.

https://github.com/TheSuperHackers/GeneralsRankedMaps/tree/main/candidate/maps_4v4_zh/Dominance%20ZH%20v1

**Comment by NoMerciBKK** [comment]
this map shouldnt be in there tbh

**Comment by xezon** [comment]
Hmm. It was part of Dominators pack delivery. So it is in here right now. I will look at it when I get to it.

**Comment by DoMiNaToRuk2** [comment]
Remove it. It's bad map. We decided as group to remove

**Comment by xezon** [comment]
Ok. Will be moved to backlog.
