### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Map has too many particles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#197]
**Issue Description**
This map has too many particles. It fails to render low priority particles for faction structures and units. Flame particles on Oil Derricks and Oil Refineries are flickering.

**Expected behavior**
The map does not consume the particle pool on its own.

**Screenshots**

![shot_20230922_153458_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2370bfb5-d210-4fe9-b186-1b9e89d68082)

**Comment by xezon** [comment]
I assume this particle problem also drains performance. On my machine I get 60 FPS max in home base, with not much built. I assume that this will lag lower machines, especially with more action on the map.

![shot_20230922_153621_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e9a6d15e-5e33-4d6d-a557-25ae3c28d9f3)

**Comment by xezon** [comment]
In the black outside of the map it renders white cloud particles.

![shot_20230922_153759_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d021e342-31c2-4ac1-992d-d6b74e20122f)

**Comment by DoMiNaToRuk2** [comment]
[AKAs Magic.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12885232/AKAs.Magic.zip)

ok please have a try of this version. Tell me any feedback including FPS mpact

**Comment by xezon** [comment]
Frame rate is much better. Min 90 FPS on my machine. Particles are no longer bugging out.
