### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Oil Derricks, Oil Refineries and Artillery Platforms have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#198]
**Issue Description**
Oil Derricks, Oil Refineries and Artillery Platforms have custom rotations that make their flag less visible.

**Expected behavior**
Oil Derricks, Oil Refineries and Artillery Platforms preferably have default rotation or a rotation that makes their flag highly visible.

**Screenshots**
![shot_20230922_153817_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1915a0ce-de20-428f-b9fc-2ef83d53c81d)

![shot_20230922_153909_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/58da47cf-35b6-4641-90b4-bd082cfb20cc)

![shot_20230922_155514_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b8874032-db04-4c90-b5d1-371f2617094d)

**Comment by DoMiNaToRuk2** [comment]
Fixed on next version
