### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] There are many obstacles on the terrain that can be driven through but not clicked on

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#199]
**Issue Description**
There are many obstacles on the terrain that can be driven through but not clicked on. They are visually ambiguous. One could assume that units should not drive and shoot through. It is not possible to click on the terrain under these ruins.

**Expected behavior**
All tall ruins are placed on impassable terrain only.

**Screenshots**
![shot_20230922_153157_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c94a5c09-0cf4-4a3f-8acf-78dfd8b4dafd)
![shot_20230922_153213_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/37678fac-a1b5-4b29-bf8f-e71f4ef29aba)

**Comment by xezon** [comment]
> Fixed on next version, impassable terrain added under all the ruins.

This could backfire if ruins can be removed with scaffolds. I will see. Impassable areas on main path ways will perhaps make this map unplayable.

**Comment by DoMiNaToRuk2** [comment]
Xezon you just made me spend 1 hour adding impassable terrain under all these ruins without thinking it through first. You need to start thinking longer and harder before raising these ridiculous blockers. 

Next you're gonna say that ruins can be cleared and impassable remains, therefore all ruins get banned... which is ridiculous and we are not banning that.

If these ruins can be cleared, then we need to allow ruins and units to go through them. Because there's 1000s of other objects on other maps already that get played everyday and no player ever complains. So I hope we can solve this.

**Comment by xezon** [comment]
As far as I know these ruins are special because they cannot be clicked into. So they affect gameplay negatively, beside being visual distractions. It is important to test what is placed on maps and consider their impact. My advice is to not put unnecessary things into maps that make it

a) slow
b) crowded
c) difficult to play on

This map was created by Adriane. Perhaps it is a good idea to involve him here to find proper solutions for the problems.

**Comment by DoMiNaToRuk2** [comment]
But what's the issue now? All your fixes have been implemented

**Comment by xezon** [comment]
I have not tested your edit yet. The way I would have fixed it is move all ruins to the side of path ways to not obstruct the play ground - or replace them with low things that do not affect clicking. I can give another update when I looked at changes.

**Comment by DoMiNaToRuk2** [comment]
[AKAs Magic.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12887368/AKAs.Magic.zip)

Removed some ruins as I agree its making the map too bunkery.

I also figured you cannot remove the ruins with a scaffold, with the impassable terrain underneath. So we are making progress.

Please test this new version, delete old.

**Comment by DoMiNaToRuk2** [comment]
[AKAs Magic.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12909631/AKAs.Magic.zip)

new version is here with all the fixes, believe map is finished now

**Comment by DoMiNaToRuk2** [comment]
I have just gotten an updated INI file which is now included in the above map version, this fixes the buildings disappearing in the fog.
