### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Map has text imprints that do not fit the style of the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#200]
**Issue Description**
The map has text imprints that do not fit the style of the map. The terrain looks natural. The text imprints look unnatural and distracting.

**Expected behavior**
Map looks natural without unexpected terrain text imprints.

**Screenshots**
![shot_20230922_153742_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cb394dd5-b36c-4e58-aa65-c3f6fd55ae6a)

![shot_20230922_153954_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/596b92bb-3b3b-4f8c-a917-def359c7aa8f)

**Comment by xezon** [comment]
Map rules say:

> Has no graphics that belong to real or fictional characters, groups, organizations

The "Lucifer Arise" on the "Black Hell" map technically also violates it, but I am going to pass that because "Lucifer" is also a regular name, fits the theme of the map and the way the text is written fits well into the map art.

This is not the case here.

We would also not accept a map with "xezon" written on it.

We can perhaps come to an agreement to pass this one through, if whole community so desires, however, it will not be part of GenTool download because map names and map contents are meant to be neutral.

Also GenTool & Shatabrick are not associated with player.

**Comment by DoMiNaToRuk2** [comment]
You say not associated with a player but he is not a player. He is a donator, of $10,000 +

**Comment by xezon** [comment]
Yes but money can not buy everything. One could make the same argument for someone sponsoring 1 Dollar.

**Comment by DoMiNaToRuk2** [comment]
[AKAs Magic.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12885696/AKAs.Magic.zip)

Well I disagree, but whatever. Here is new version with AKAs name removed

**Comment by xezon** [comment]
I can understand the disagreement. Sponsors appreciation is necessary, but Ranked Maps are not the right tool for this. Videos and Forum Posts are.
