### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Some foliage and props are tightly packed and can hide units

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#201]
**Issue Description**
Some foliage and props are tightly packed and can hide units.

**Expected behavior**
Trees and props are reasonably spaced and or impassable and do not offer grand opportunity to hide behind.

**Screenshots**

2 infantry defenders hiding in trees and props.

![shot_20230922_154502_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d32ca4c0-59eb-4025-ac7b-5ee3758180b5)

2 trees placed on the same spot.

![shot_20230922_154537_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/294e1ac2-4716-48f6-b067-ed27ce33be8b)

There are more places. Needs review.

**Comment by xezon** [comment]
Removed blocker. I suggest to clean it up anyway. Map has low performance. There is no need to pack objects this tightly.

Also, I see a bunch of floating rocks in the bottom screenshot. Perhaps that can be looked into as well. Is not (yet) separately tracked.

**Comment by DoMiNaToRuk2** [comment]
Fixed this on next version. Coming soon.

**Comment by xezon** [comment]
Looks better. Here are some more spots that can be optimized where green trees clip through white tree:

### Remove green tree inside white tree

![shot_20231014_181609_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/34713952-af06-4752-b607-b471b3550747)

### Remove green tree inside white tree

![shot_20231014_181637_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/200381bd-3972-4c41-be54-f40467d82437)

### Remove green tree inside white tree

![shot_20231014_181658_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7f8cb55a-9a28-42ce-8c7c-5f46382a9906)

### Remove green tree

![shot_20231014_181730_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4970ab68-3547-4fc5-a817-18efb53e4499)

### Remove green tree behind white tree

![shot_20231014_181745_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c119bd6e-d7f4-4a8e-9941-1e90d2b19ffd)

### Remove 1 green tree behind white tree

![shot_20231014_181755_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/af4c4ce9-caef-4e17-a90a-3cc64de331d9)

### Remove green tree inside white tree

![shot_20231014_181827_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a2223bd0-4c65-4eb0-b368-e3d3f5a26040)

**Comment by DoMiNaToRuk2** [comment]
all trees fixed in new version
