### ISSUE TITLE
[Candidate 1v1 Alfies Haven ZH v1] Buildings at docks are not selectable but can be clicked into

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#205]
**Issue Description**
Buildings at docks are not selectable but can be clicked into.

**Expected behavior**
Buildings at docks are selectable or cannot be clicked into (impassable).

**Screenshots**
![shot_20230922_162744_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/630e5a14-f8f9-44f5-9d85-3cac8c243556)

![shot_20230922_162805_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/08a1d20e-3941-4212-8859-9f9865a58714)

![shot_20230922_162914_54](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/034e3a44-3553-414a-a0a4-b78c7fbf3044)

**Comment by General-StaZzz** [comment]
also this house prevents the dozer (or supl trucks) box from being built :/
![shot_20230925_192039_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/91178098/234b0e40-b990-4067-9806-5cd9838bccb7)
