### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Oil Derricks, Oil Refineries and Artillery Platforms have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#206]
**Issue Description**
Oil Derricks, Oil Refineries and Artillery Platforms have custom rotations that make their flag less visible.

**Expected behavior**
Oil Derricks, Oil Refineries and Artillery Platforms preferably have default rotation or a rotation that makes their flag highly visible.

**Screenshots**

Bad

![shot_20230923_165647_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd776975-e233-4507-8a20-779899be1bdc)

Not optimal

![shot_20230923_165716_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/94d15d82-aceb-4c60-8c83-f9124e4038d7)

Good

![shot_20230923_165747_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ce403b9b-93a1-4fca-b89f-cfcf621caa1b)

**Comment by DoMiNaToRuk2** [comment]
Fixed in v6 and attached on gamereplays Maps Proposal topic.
