### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Barrels around Oil Derrick in center do not explode

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#207]
**Issue Description**
Green barrels around Oil Derrick in center do not explode. Brown barrels around other Oil Derricks do explode. Behavior is ambiguous.

**Expected behavior**
Barrels ideally behave consistently. Otherwise, prefer remove decorative barrels from center.

**Screenshots**

Explode under fire.

![shot_20230923_170333_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/48614218-e0e6-4824-84d2-f9bf76d6df89)

Do not explode under fire.

![shot_20230923_170338_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7b39d5e7-26ec-4cdd-8a6f-c78bd6c48491)

**Comment by General-StaZzz** [comment]
Personally, I've never noticed barrels like this before this thread. 

I don't consider it a problem for the following reasons:
- Blue barrels cannot be selected
- They have a less detailed texture than barrels that can explode.

**Comment by xezon** [comment]
Dominator is author of this map and wants it closed. Closing.

**Comment by DoMiNaToRuk2** [comment]
Is arctic arena no longer a candidate?

**Comment by xezon** [comment]
If it is in candidate folder then it is candidate.
