### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Snow in water does not look optimal

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#208]
**Issue Description**
Snow in water does not look optimal. Bottom left corner.

**Expected behavior**
Bottom left corner looks visually as good as top right corner.

**Screenshots**

Does not look good.

![shot_20230923_170434_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b5c3cfbb-a9d0-4f8c-8fb9-ae590717eaaf)

Looks good.

![shot_20230923_170730_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dd3bb591-0c00-41ff-9677-e8a27ee19b5b)

**Comment by DoMiNaToRuk2** [comment]
I am fixing this now, as this map was my design. Bottom left snow will look fine in v6
