### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Supply piles have odd terrain texture underneath

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#209]
**Issue Description**
Supply piles have odd terrain texture underneath.

**Expected behavior**
Supply piles sit on normal terrain. Matter of preference. Leave as is if ultimately desired.

**Screenshots**

![shot_20230923_170637_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3a66a8dd-19c5-451a-ba73-982338013f51)

![shot_20230923_172132_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ce966924-e874-44c3-8e49-37f1dbac4c22)

![shot_20230923_172309_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/34612b6b-6d83-417d-99cf-3ae56632b85d)

**Comment by General-StaZzz** [comment]
I agree with Dominator that it is necessary to visually highlight such resource piles, because sometimes they really can be overlooked. But in this example, the texture chosen is really not the best, which departs from the theme of the map (it looks like a puddle of asphalt).

**Comment by xezon** [comment]
Yes perhaps could be snowy dirt instead of asphalt.

**Comment by xezon** [comment]
Here is how it looks in Snowy Roads. In my opinion a better choice of paint.

![shot_20230927_160939_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3788931e-6ac9-4f1b-8d14-b47950406ebc)

**Comment by DoMiNaToRuk2** [comment]
This will not be fixed for two reasons.

1. When you try to replace a texture using fill paint option, the textures all mess up and become blocky in many areas. This requires hours of extra work filling in pixel by pixel to fix the new errors.

2. This texture was originally set by the map maker as per intsructions and feedback that even top players were sometimes not seeing their supply. Plus it does not look so bad. Looks fines.

**Comment by xezon** [comment]
As designed.
