### ISSUE TITLE
[Candidate 1v1 Arizona Airfield ZH v1] Map uses tall shrubbery that cannot be crushed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#210]
**Issue Description**
Map uses tall shrubbery that cannot be crushed.

**Expected behavior**
Tall shrubbery should be crushable or removed. Map would likely look still look rich with all these tall ones removed.

**Screenshots**

![shot_20230923_172729_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/55022185-933a-4896-845c-3d301dee5b05)

**Comment by DoMiNaToRuk2** [comment]
Fixed - all trees removed. New version v2 will be on GR.org topic
