### ISSUE TITLE
[Candidate 1v1 Arizona Airfield ZH v1] Supply stashes to the left have wrong brightness

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#211]
**Issue Description**
Supply stashes to the left have wrong brightness.

**Expected behavior**
Supply stashes have proper brightness level.

**Screenshots**

Bad

![shot_20230923_173152_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0d0e440b-3d82-49f1-b928-0da9d1e39c72)

Good

![shot_20230923_173201_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7290ab1c-3b29-44b2-aa91-f8b03b33f88c)

**Comment by DoMiNaToRuk2** [comment]
Fixed - all trees removed. New version v2 will be on GR.org topic
