### ISSUE TITLE
[Candidate 1v1 Arizona Airfield ZH v1] Units can move into shipping containers

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#212]
**Issue Description**
Units can move into shipping containers.

**Expected behavior**
Units can not move into shipping containers

**Screenshots**

![shot_20230923_173019_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e17c3fc-702b-4501-a78e-e1bf5af76a99)

**Comment by DoMiNaToRuk2** [comment]
Fixed. New version v2 will be on GR.org topic
