### ISSUE TITLE
[Candidate 1v1 Arizona Airfield ZH v1] Buildings at docks are not selectable but can be clicked into

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#213]
**Issue Description**
Buildings at docks are not selectable but can be clicked into.

**Expected behavior**
Buildings at docks are selectable or cannot be clicked into (impassable).

**Screenshots**

![shot_20230923_172921_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a414835d-618f-48e6-bb4d-c6c8a3a01bf3)

**Comment by DoMiNaToRuk2** [comment]
Fixed. New version v2 will be on GR.org topic

**Comment by xezon** [comment]
They can now be selected, but not killed. May I suggest to make them killable if selectable, or impassable and not selectable, if not killable?

**Comment by xezon** [comment]
In latest version, all structures near Oils, except the crane, are destructible.

There are now 2 problems:

1. At the bottom, Units cannot move through the crane, but at the top they can. This ideally should be consistent.

![shot_20231007_092622_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8ff97a1a-4c3e-4f0e-8899-fd82977d0b5a)

![shot_20231007_092646_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/12160e86-8317-48a8-abf5-2a7744b84f50)

2. After killing the Shipping containers, the terrain is still impassable and units cannot move over the empty space. On both sides.

![shot_20231007_092156_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d873d256-5027-49f1-999b-4dba2f6a3c1c)

**Comment by DoMiNaToRuk2** [comment]
Maybe we should have left it exactly like it was hey?

**Comment by xezon** [comment]
There are different ways to design this. The executed design just needs to be properly polished.

In original design buildings were not selectable, but could be clicked into, meaning the mouse cursor would show it was passable.

Now structures are selectable and destructible, but there are pathing issues.

**Comment by DoMiNaToRuk2** [comment]
ok in next version cranes made the same, plus shipping containers made indestructible so that the impassable terrain underneath remains always correctly.

**Comment by DoMiNaToRuk2** [comment]
[Arizona Airfield v4.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12837522/Arizona.Airfield.v4.zip)


ok everything fixed, including supply position and the dock area is now working perfect
