### ISSUE TITLE
[Candidate 1v1 Bozic Destruction ZH v6] Bottom oils are fenced, top oils are not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#221]
**Issue Description**
The Oil Tech structures at the bottom of the map are fenced, but not at the top. Fences do block infantry movement.

**Expected behavior**
Fences are equally placed to maintain equal conditions for players.

**Screenshots**

![shot_20230926_103001_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b0c6618c-4eee-4300-98ef-1282bddbca64)

![shot_20230926_102956_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/77eeee43-8bf0-4c87-871e-d812b8e0f457)

**Comment by NoMerciBKK** [comment]
updated
