### ISSUE TITLE
[Candidate 1v1 Bozic Destruction ZH v6] Main Supply Dock does not offer same build space

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#222]
**Issue Description**
Main Supply Dock does not offer same build space. The supply at the bottom has advantages, especially for China because of more generous room.

**Expected behavior**
Supply Docks offer about equal building space on both sides.

**Screenshots**

![shot_20230926_103417_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ac50ccf4-e1ec-4683-a38d-e9bfc3bd4da4)

![shot_20230926_103428_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/30ce70d8-01ae-408c-b81a-d98c6dec5696)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
It is possible to build now.

The ramp has a quite pronounced edge now. Unclear if this could potentially cause issues with units fighting near that edge. Perhaps can be smoothed a bit?

![shot_20240121_150721_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6eb658db-613d-47b0-9465-631f1713af4b)

**Comment by NoMerciBKK** [comment]
it should not cause any problems on fighting there and if you smooth it out more you have problems again with the supplys placement
