### ISSUE TITLE
[Candidate 1v1 Desert Fury ZH v2] Left player tower is likely advantageous

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#224]
**Issue Description**
The tower for the left player at the top of the maps is likely advantageous. The gap is narrower, so it can easier damage passing infantry. It can also reach a generous area of the ramp to the oils, making it easier to push to the Oils or Supply Dock with the back up of the tower. The other Tower is more secluded and does not provide this much cover.

**Expected behavior**
Both towers have similar reach to important path ways to valuable resources.

**Screenshots**

![shot_20230926_110106_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/963d0784-2f8d-4020-b1c3-441a82913341)

![shot_20230926_110115_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4ee173e5-935a-4920-8b89-14bcd6d88c4f)

![shot_20230926_110949_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/947775b2-5a1b-4d19-be1c-7657e157f1ab)

![shot_20230926_111013_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/345d4637-6d1b-458f-8a7e-b5f9da46cacc)

**Comment by NoMerciBKK** [comment]
updated
