### ISSUE TITLE
[Candidate 1v1 Dust Devil ZH v2] Second Main Supply Dock does not offer same build space

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#225]
**Issue Description**
Second Main Supply Dock does not offer same build space. The supply at the top has advantages for GLA, as it can squeeze a supply stash.

**Expected behavior**
Supply Docks offer about equal building space on both sides.

**Screenshots**

![shot_20230926_112413_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b2f1c94f-cef0-4386-9323-d1d1eff5fd92)

![shot_20230926_112421_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7cd62c36-0856-4000-be83-4de45fb75e1a)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
It is now possible to build a Supply Stash at the bottom.

It still is not entirely fair. At the top, units can drive behind the Supply Stash. At the bottom not.

![shot_20240122_184055_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d29015aa-6686-47f8-ae70-27a8b5bf6c5c)

![shot_20240122_184046_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cceb3880-b75d-4b10-84e1-0fb9bbded2d7)

**Comment by NoMerciBKK** [comment]
> It is now possible to build a Supply Stash at the bottom.
> 
> It still is not entirely fair. At the top, units can drive behind the Supply Stash. At the bottom not.
> 
> ![shot_20240122_184055_2](https://private-user-images.githubusercontent.com/4720891/298673932-d29015aa-6686-47f8-ae70-27a8b5bf6c5c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjAyOTUsIm5iZiI6MTcwNTk1OTk5NSwicGF0aCI6Ii80NzIwODkxLzI5ODY3MzkzMi1kMjkwMTVhYS02Njg2LTQ3ZjgtYWU3MC0yN2E4YjViZjZjNWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjE0NjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzUyNWY1ZmRjZjU3YjM1Y2M3NzhiODZlN2U3OGUwYjg1YzZiZWI3MGQwOTAxNmVmYzUyZjcxYjBjNDE3YjM0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dnTgPQ8yKrF7iS7GgC7p4baCEIG1DFY69Wj97gvQ3KI)
> 
> ![shot_20240122_184046_1](https://private-user-images.githubusercontent.com/4720891/298673916-cceb3880-b75d-4b10-84e1-0fb9bbded2d7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjAyOTUsIm5iZiI6MTcwNTk1OTk5NSwicGF0aCI6Ii80NzIwODkxLzI5ODY3MzkxNi1jY2ViMzg4MC1iNzVkLTRiMTAtODRlMS0wZmI5YmJkZWQyZDcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjE0NjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk4NTQ5NzY3ODcwNjc2ZjcwZjg3NWFhYTRlZDZlZGE2NWU5YjNmZDhiZDg3NzBjMzk5NzNlZjAzMzgwMGZmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z-M5xJuI7nN7zTcPp0r-3K0ZMpYmUnfhclAlXb7CvBE)

yes ineed but it depends how you build a building anywhere on the map if units can pass or not and the blocker was that you cant build a supply where nobody rly would build a supply , i dont think it matters a lot tbh

**Comment by xezon** [comment]
Would be good if conditions are equal on both sides. The same issue was present in #530. TanSo fixed it somehow.

**Comment by xezon** [comment]
Fixed with #628
