### ISSUE TITLE
[Candidate 1v1 Echo ZH v1] Supply piles at the bottom left cannot be passed behind

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#229]
**Issue Description**
The supply piles at the bottom left cannot be passed behind. The other supply piles can be passed.

**Expected behavior**
All supply piles can be passed behind to offer equal opportunity for unit movement.

**Screenshots**

Impassable

![shot_20230926_115542_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/34db3eff-a7d9-404c-be31-654c67116d62)

Passable

![shot_20230926_115550_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ca605c6b-5413-4031-afd5-70f5db41bd46)

![shot_20230926_115608_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ccd6dba8-a239-4d6f-aefc-a568bb907b6b)

![shot_20230926_115626_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/15adcae0-2b75-4a08-bada-8975301e9734)

**Comment by NoMerciBKK** [comment]
updated
