### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] FPS drops by about 50% when a dam breaks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#231]
**Issue Description**
FPS drops by about 50% when a dam breaks.

**Expected behavior**
FPS does not drop drastically when a dam breaks.

**Screenshots**

Frame rate during dam break.

![shot_20230926_182303_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/213ed7d0-9322-46a8-bbc0-9a7c1e3539f9)

Frame rate after dam break.

![shot_20230926_182309_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/10ed9bb7-5237-440f-85ed-3a298650c3ba)

**Comment by xezon** [comment]
Perhaps can be optimized by reducing particles?

**Comment by ImTimK** [comment]
It's pretty low generally I just noticed on excals stream and his hardware is much better than average.

https://www.youtube.com/watch?v=Rm1e5YzId1A

**Comment by DoMiNaToRuk2** [comment]
Here I think the overall map FPS (when dam is not breaking) could be checked on how to fix - weather particles? unneccesary objects etc that can be removed?

Then there's the dams, I agree its laggy when dam breaks. I think we need to try removing the particles and do what Newgate did on the likes of Crazy Beach map or Adrianne on battleship map, there the map can flood ok but without particles and without lag.

Tanso please can you trial without particles and send up update?

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
I have observed performance improvement. It now drops just by 25% to about 75 FPS on my machine. Much better. I will remove blocker label because the other bug with 25% drop is also no blocker.
