### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Structures are z clipping at many places

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#232]
**Issue Description**
Structures are z clipping at many places. It has a notable negative visual impact on the otherwise beautiful environment.

**Expected behavior**
Structures are not z clipping. This can be avoided by varying the height of structures by a tiny amount. Polygons must not share the same plane.

**Screenshots**

![shot_20230926_181350_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f174702-6063-49bd-8764-933db20e6da9)

**Comment by xezon** [comment]
Looks much better indeed. There is still some clipping on the facades. This can be fixed by varying the positions by a tiny amount.

![shot_20230927_111724_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/60027250-c0a6-43f2-9b40-912c6c1b05e1)

**Comment by xezon** [comment]
And these 4 spots were missed:

![shot_20230927_113009_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/00012ea8-62c0-4007-8d1a-79ffd62aa326)

**Comment by DoMiNaToRuk2** [comment]
if quick fix - i have asked tanso to try and fix. If takes many hours then ok to leave

**Comment by xezon** [comment]
At least the inland surface clipping can be fixed. It is highly visible. Location on last screenshot, 4 times.

**Comment by toirehantaa** [comment]
fixed.
