### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Oil Derrick at the top left has unsymmetrical rotation

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#233]
**Issue Description**
Oil Derrick at the top left has unsymmetrical rotation. All other Oil Derricks face the shoreline with the pump. But not this one.

**Expected behavior**
Oil Derrick is rotated by 180 degrees and the pump faces the shore.

**Screenshots**

Pump does not face the shoreline.

![shot_20230926_181619_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dce01bc8-d5c8-42fa-9ef3-3c953f1383cd)

Pump faces the shoreline with the 3 other Oil Derricks.

![shot_20230926_181731_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/71d56d27-5ea7-4216-bfb0-50c912445deb)

**Comment by toirehantaa** [comment]
fixed.
