### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Oil Derricks at shoreline are not consistently placed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#234]
**Issue Description**
Oil Derricks at shoreline are not consistently placed. The pump has different overlaps on the nearby structures.

**Expected behavior**
The Oil Derricks are placed with the same distances near the structures.

**Screenshots**

![shot_20230926_181731_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7f105e17-6a1a-409b-8d0d-0dee7858e604)

![shot_20230926_181913_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b10ecb71-1b2d-48f9-8bb2-dd889fed9df6)

![shot_20230926_181947_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bcd8039c-bf20-4a9b-8456-cadda602f3d0)

**Comment by toirehantaa** [comment]
This is due to the layout of the edge buildings. The Oil derricks are 100% Symmetric and equally distant, to the millimetre. The scenery creates this effect

**Comment by xezon** [comment]
Ok. Close?

**Comment by toirehantaa** [comment]
yep
