### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Artillery Platform in center has custom rotation that make its flag not visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#235]
**Issue Description**
Artillery Platform in center has custom rotation that make its flag not visible.

**Expected behavior**
Artillery Platform is rotated by 90 degrees to show its flag. The Artillery Platform on the opposite side can be adjusted accordingly to keep them symmetrical.

**Screenshots**

![shot_20230926_182555_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/376966e1-ac05-441f-88ef-b428bc03db38)

**Comment by toirehantaa** [comment]
in my opinion there are enough colorbind cues. The platform is rotated like this for symmetry reasons, looks best like this

**Comment by xezon** [comment]
I can see the symmetry. The flags point clockwise.

The flag doubles the house color surface, which is certainly desired. Perhaps there is a way to make it happen?

![shot_20230926_213351_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/50aba76e-74f8-495e-9493-d35ad34eef60)

**Comment by toirehantaa** [comment]
only if both arty platforms point to one player, which looks weird - also wrote the same in DC DMs

**Comment by xezon** [comment]
I understand the problem. Symmetry vs Housecolor Visibility. Perhaps we come up with a good idea here. Right now I have none.

**Comment by DoMiNaToRuk2** [comment]
As xezon will not back down on this, I suggest just make the arty platforms face one player. Its a 2minute job. I asked tanso to fix

**Comment by toirehantaa** [comment]
Having no symmetry also impacts the balance. Rotation dictates where the Gun of the platform is facing. Upon capturing it needs different amounts of time to point the gun to a unit -  Which could, if we go this much into detail, mean the difference between a unit being hit or getting out of range before the cannon fires. Therefore one player would have a slight disadvantage. I think we can all agree that there is no reason to debate this. I'd like to keep it symmetric

**Comment by xezon** [comment]
Alright then.
