### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Water spray particles are moving fast

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#236]
**Issue Description**
The water spray particles look faster than they should.

**Expected behavior**
The water particles are a bit slower. See Toxin Tractor spray splash for reference.

**Screenshots**

![shot_20230926_182427_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/99f58c8c-427c-4de5-b226-673441b370cb)

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e680efef-a7e3-4cf1-b57d-671367fe3688

**Comment by toirehantaa** [comment]
The FPS is dictating how fast the animation goes - so out of my might

**Comment by xezon** [comment]
The video was created with 30 fps. Particles look fast with 30 already.

**Comment by toirehantaa** [comment]
Still not something I can fix though, it's an animation coded to the object itself
