### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Structures cannot be placed in center, although terrain looks flat

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#237]
**Issue Description**
Structures cannot be placed in center, although terrain looks flat.

**Expected behavior**
Structures can be built in center.

**Screenshots**

![shot_20230926_185256_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9676155a-c288-4457-a3f2-3d4deed4a4e3)

**Comment by xezon** [comment]
Perhaps this is it intended to block players from establishing a stronghold in the center?

**Comment by toirehantaa** [comment]
yep, exactly, not supposed to be buildable, since after damblows this will be the only open area

**Comment by xezon** [comment]
As designed.
