### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#238]
**Issue Description**
Audio emitters have no easing. Sounds clips in and out unpleasantly.

**Expected behavior**
Sound is setup with easing. Scrolling over the map gives nice audio transitions.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9ae7faf5-4cc7-4b12-a86b-622e100955e4

**Comment by toirehantaa** [comment]
should be fixed now.
