### ISSUE TITLE
[Candidate 1v1 Double Damination ZH v4] There are water sounds by the dams before there is any water

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#239]
**Issue Description**
There are water sounds by the dams before there is any water.

**Expected behavior**
Water sounds spawn after dam destruction, if technically possible.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f63e29b6-7f93-4ece-935f-047aee550f06

**Comment by toirehantaa** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/c247b4e8-c16c-4949-9a93-667a682f83bc)
there is water, but I agree that it is not as visible - I'd take it as a sound cue that the dam is there and ready to be exploded

**Comment by xezon** [comment]
Perhaps it is possible to have shallow water at the dam before killing it? Is this possible? This would help give the clue for dam breakage and fit the water sounds.

**Comment by toirehantaa** [comment]
at the dam... where? I mean it is already behind it... I would not reeeeeaally like to add any more water sources

**Comment by xezon** [comment]
In front of the dam. Shallow water. Then after dam break, deep water.

**Comment by toirehantaa** [comment]
wouldn't that just make it impassable?

**Comment by ImTimK** [comment]
> wouldn't that just make it impassable?

I think so, 

I think current is fine, gives a clue that there's water behind the dam.

**Comment by xezon** [comment]
> wouldn't that just make it impassable?

No, shallow water like in "AKAs Magic" map. Unit can drive over it.

**Comment by toirehantaa** [comment]
let me have a look

**Comment by xezon** [comment]
As designed.
