### ISSUE TITLE
[Candidate 1v1 Double Damination ZH v4] Map uses tall shrubbery that cannot be crushed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#240]
**Issue Description**
Map uses tall shrubbery that cannot be crushed. They also look odd when in fog. Much darker than other foliage.

**Expected behavior**
Tall shrubbery on passable areas should be crushable or removed. Map would likely look still look rich with all these tall ones removed.

**Screenshots**

Shrubbery towers above vehicles but cannot be crushed.

![shot_20230926_195729_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/191e5a30-e58e-4728-9bb1-1d7e98b0e7af)

Shrubbery is very dark in the fog.

![shot_20230926_195832_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4693bfe9-b147-41b0-b6cd-a85f9175020e)

**Comment by Jundiyy** [comment]
![shot_20231002_211218_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/6a8fedc5-3c0c-4ce3-b2e8-1fb02ec70aad)
![shot_20231002_211344_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/f04b67a1-ae33-48ae-8581-6e5d1133a102)
![shot_20231002_212134_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79164303/0855d760-6f8b-428d-a327-e21746214a86)

I don't think this is a problem but here are possible solutions.

**Comment by xezon** [comment]
Tanso has requested to demote this from blocker. Demoted.

**Comment by xezon** [comment]
As designed.
