### ISSUE TITLE
[Candidate 1v1 Double Damination ZH v4] Supply Piles near dam are passable on one side, but not on the other

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#241]
**Issue Description**
Supply Piles near dam are passable on one side, but not on the other. This possible puts one player at an advantage or disadvantage, depending on circumstances.

**Expected behavior**
Supply Pile placement is mirrored. Units can either pass or not pass equally on both sides.

**Screenshots**

![shot_20230926_201339_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a662becc-6889-42ee-b762-97f7a9e8be5c)

![shot_20230926_201400_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ac5b0049-950f-4ad3-9cba-08b60b4e6153)

**Comment by toirehantaa** [comment]
fixed.
