### ISSUE TITLE
[Candidate 1v1 Double Damination ZH v4] Dams have large attack area

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#242]
**Issue Description**
Dams have a large attack area. This means it is possible to attack the dam accidentally when commanding units near the dams. For example trying to move Infantry behind the Supply Piles on the right side can issue an attack on the dam. Perhaps this also interferes with enemy unit engagements.

**Expected behavior**
Dams have a smaller attack area, if possible.

**Screenshots**

![shot_20230926_201547_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e09e228e-e4c0-4268-bdbe-06934caacc8f)

**Comment by toirehantaa** [comment]
The attack area is not something I can influence like an object property - I would need to limit it with terrain, which would make it more bunkery at this spot, so I wont do it

**Comment by xezon** [comment]
I was afraid so. Dam object is too large. Is there no smaller dam object that could be used?

**Comment by toirehantaa** [comment]
none that fit's the theme - also this object specifically on DoMi's wish

**Comment by xezon** [comment]
How about we make the object not attackable, just attackable with force fire?

**Comment by toirehantaa** [comment]
I initially made it targetable so that players can see that those dams are supposed to be blown

**Comment by xezon** [comment]
What is the default attack behavior? Force attack only?

Perhaps there is another way to communicate that dams are destructible? With map design? For example put a hazard sign near dam, or construction zone, or something else that indicates it is brittle. Perhaps put a small particle stream of water at the dam that indicates it has a hole already.

**Comment by toirehantaa** [comment]
yea, default is forcefire only, like any other uncaptured civilian building.
I thought it would make it easier for players to micro when they were targetable

**Comment by xezon** [comment]
Force fire (default) might be better to avoid unwanted attacks on the structure. Could you perhaps send a test version with default behavior?

**Comment by xezon** [comment]
Nevermind, I tested with unit that has no weapon. There would still be problems without attack. The select command will take priority over move command. The core of the issue is the huge selection box.

Close this?

**Comment by toirehantaa** [comment]
Close then

**Comment by xezon** [comment]
Cannot be fixed, because dam objects are too large
