### ISSUE TITLE
[Candidate 1v1 Double Damination ZH v4] FPS drops by about 66% when a dam breaks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#244]
**Issue Description**
FPS drops by about 66% when a dam breaks.

**Expected behavior**
FPS does not drop drastically when a dam breaks.

**Screenshots**

Frame rate before dam break.

![shot_20230926_203816_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5bf58e82-d796-43d6-a959-8e484a4e8e8a)

Frame rate during dam break.

![shot_20230926_203820_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/01917086-1089-40fb-9d0b-977c9224a705)

**Comment by NoMerciBKK** [comment]
this will happen on every dam map because the game engine is single core running every bigger movement on map will cause fps drops for a short time, fixable if we can make the engine run on more cores

**Comment by xezon** [comment]
It is not the particles that slow it.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/efe82048-e73f-466e-8964-e13d2277ef71

**Comment by xezon** [comment]
There is this map:

https://github.com/TheSuperHackers/GeneralsGamePatch/tree/main/Maps/Any/!TestRisingWater

It stalls just very shortly when the water rises. Perhaps this can be replicated?

**Comment by xezon** [comment]
| Cat.      | Old min FPS  | New min FPS |
| Overall   | 120          | 210         |
| Dam Break | 38           | 150         |

Huge performance improvement on this map. Demoting from blocker.

**Comment by xezon** [comment]
Remaining performance drop is acceptable. Fixed.
