### ISSUE TITLE
[Candidate 1v1 Yelling Avalanche ZH v2] Deep dent in terrain near top Oil Derrick

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#245]
**Issue Description**
There is a deep dent in terrain near top Oil Derrick. This could be disadvantageous for Humvees, Battle Bus and Rocket Buggy. There is no such dent at the bottom side of the map.

**Expected behavior**
No dent in terrain.

**Screenshots**

Top, dent

![shot_20230927_094706_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5252b879-484c-4ab6-8964-5b760381ec75)

Bottom, no dent

![shot_20230927_094726_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b2f5711c-64d5-4d63-9d3d-1cd52c13f374)

**Comment by xezon** [comment]
Also look like the structure near the terrain dent is floating above terrain. Not clear from the screenshot.

**Comment by xezon** [comment]
Terrain is still dented somehow. Units will move on bumpy ground. I suggest to smooth the terrain.

![shot_20231008_163317_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4b45729e-9d38-47a1-8151-2f5af0b503a3)

![shot_20231008_163508_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/084d6f01-23cd-4bb1-bd04-95ad7656c81e)

**Comment by NoMerciBKK** [comment]
updated
