### ISSUE TITLE
[Candidate 1v1 Yelling Avalanche ZH v2] Oil Refineries and Artillery Platforms have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#248]
**Issue Description**
Oil Refineries and Artillery Platforms have custom rotations that make their flag less visible.

**Expected behavior**
Oil Refineries and Artillery Platforms preferably have default rotation or a rotation that makes their flag highly visible.

**Screenshots**

![shot_20230927_094929_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1d564fa1-c666-4733-a003-7344bebae2ca)

![shot_20230927_095157_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/97c36d13-30bf-4b82-b2a3-114d18a6317b)

**Comment by DoMiNaToRuk2** [comment]
[Yelling Avalanche ZH v3.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12839407/Yelling.Avalanche.ZH.v3.zip)

Here is yelling avalanche v3. It contains fixed for rotations of tech buildings and dent in top left is fixed.

The snow patch not visible under fog cannot be fixed, i tried changing all settings and i even compared to other maps like Arctic Arena (another map maker made that) and the patch acts the same. We are map makers, not game patchers - please let's stick to map making.

Please let's approve this map now if fully accepted.

**Comment by xezon** [comment]
There is still one Oil Derrick that could be rotated 90 degrees clock wise.

![shot_20231008_165721_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ad303505-3ee7-4758-b746-cec231f02f53)
