### ISSUE TITLE
[Candidate 1v1 Natural Threats ZH v4] Space behind main supplies has different size

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#249]
**Issue Description**
Space behind main supplies has different size. This affects unit maneuver abilities.

**Expected behavior**
Space behind main supplies is identical between top and bottom spot.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/15b38128-b7aa-4533-b207-3d5595baff97

**Comment by ReLaX82** [comment]
I took 3 cells in regard to the supply as passable terrain behind the supplies now.
So, it is equal for both.

**Comment by ReLaX82** [comment]
Now, fixing all 3 issues there a new version, please test.
Final version will be renamed accordingly.
The audio issue was hard to solve. I ended up redoing the audio from scratch and did not interfere cracking up to now.

**Comment by xezon** [comment]
Where is version?

**Comment by ReLaX82** [comment]
7ZIP and RAR is not supported, downloading ZIP.

**Comment by ReLaX82** [comment]
[Natural Threats ZH v4_EDITv1.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12927399/Natural.Threats.ZH.v4_EDITv1.zip)

**Comment by xezon** [comment]
Space behind both supplies is now no longer passable. Does not look good.

**Comment by NoMerciBKK** [comment]
Fixed and can be closed?

**Comment by NoMerciBKK** [comment]
updated
