### ISSUE TITLE
[Candidate 1v1 Natural Threats ZH v4] White trash bin is placed on grass land

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#251]
**Issue Description**
There is a white trash bin is placed on grass land. It looks unfitting.

**Expected behavior**
White trash bin is removed or moved to the village in the center.

**Screenshots**

![shot_20230927_103757_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7bb862a1-d80e-4e87-8bc9-e0c76a9a831a)

![shot_20230927_103801_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/232be1c2-d7ee-4582-a92f-0c45751c11bd)

**Comment by ReLaX82** [comment]
Relocated in update.
