### ISSUE TITLE
[Candidate 1v1 Mountain Arena ZH v1] Map looks like a fun map, but should it be ranked?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#252]
Mountain Arena ZH v1 looks like a fun map, but should it be ranked?

It is just one big flat space surrounded by Supply Piles.

![shot_20230927_104308_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/679ea772-6ce6-4e34-8262-6c92d78e33a0)

The Supply Piles at the South are hidden by the terrain.

![shot_20230927_104249_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/58a2898c-0062-4775-9d99-e29c9645545d)

Do we know that both players have equal amounts of Supply Piles?

**Comment by NoMerciBKK** [comment]
I´ve never seen this Map before, Timber and me testet all "Ranked" maps so far.

**Comment by DoMiNaToRuk2** [comment]
yes should be ranked, every map is unique and this is very unique.

both players have same number of piles in their immediate proximity.

**Comment by NoMerciBKK** [comment]
Unbalanced design workers and trucks are way slower than chinnoks so they d collect slower or need way more supplys also the placement of those crates is unfair playerspawn wise

**Comment by DoMiNaToRuk2** [comment]
China supplies and gla supplies are cheaper. Workers and trucks are cheaper.

China is the king at expanding due to super fast supply construction.

So you cannot compare chinooks vs worker collection rate. Totally irrelevant

**Comment by ImTimK** [comment]
CXN and no money maps are also unique and different from standard map design, add those aswell? 

This map is way too simple and flat looking to be considered RANK, RANK also means it's suitable for tournaments, well this is definitely not.

**Comment by DoMiNaToRuk2** [comment]
I see your point, however you cannot really compare CXN and no money maps since they are very specialest and lame maps. You will not find a normal build or game on there.

However on such an arena map with crates on the outside you would still see pretty normal and fun games. Imagine a tank mirror between two top players on here, compared to on CXN - its not comparable.

**Comment by ImTimK** [comment]
CXN, FFA and whatever else maps are popular without being RANK, stuff like this doesn't need to be RANKED. 

Even I could make this after watching a 10 min WB tutorial.

**Comment by DoMiNaToRuk2** [comment]
Could also make vendetta myself in about 10 mins, just FYI.

But fair enough let's remove this one

**Comment by ImTimK** [comment]
Why are we even wasting time on reviewing stuff like this when you can make 5 vendetta quality maps an hour?

**Comment by DoMiNaToRuk2** [comment]
We don't need 5 identical vendettas. Variety is good but point taken, this can be discounted

**Comment by xezon** [comment]
Ok. Will be moved to backlog.
