### ISSUE TITLE
[Candidate 1v1 Kinky Fields ZH v1] Should this map be ranked?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#253]
**Issue Description**
Map displays caged woman with screams. Looks inappropriate. Should it be ranked?

**Expected behavior**
Map is removed from candidate maps.

**Screenshots**

![shot_20230927_110335_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4b68d7a7-c51d-4f37-ba14-3507df7c0483)

![shot_20230927_110326_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/223f1aac-9c65-4092-b41c-b88ba81bfbfe)

**Comment by DoMiNaToRuk2** [comment]
Killing fields is an official map and is one of the worst maps ever. This is a remake of that and with the idea to make it fun. It fits all requirements and should become RANKED. It will bring joy and laughter to those that play it.

**Comment by NoMerciBKK** [comment]
Imo it still shouldnt be a RANKED map its unfinished bad/inappropiat looking with annoying sounds. 
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/3a9f56bc-2fb8-480c-a363-8ce14c03dff4)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/6617f49a-82a8-45fe-891a-ddac931d0103)

**Comment by xezon** [comment]
I am in favor of removing this map. It does not fit the professional style of other ranked maps. And it might be offending to female audiences.

**Comment by xezon** [comment]
There has been no further input on this matter. Map will be moved to backlog.
