### ISSUE TITLE
[Candidate 1v1 Black Hell ZH v3] Units can move into Particle Cannon structures

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#255]
**Issue Description**
Units can move into Particle Cannon structures.

**Expected behavior**
Units can not move into Particle Cannon structures.

**Screenshots**

![shot_20230927_121358_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/656e0ba9-e69e-444f-abc8-7ea5f6e89cee)

**Comment by toirehantaa** [comment]
fixed.
