### ISSUE TITLE
[Candidate 1v1 Black Hell ZH v3] Supply piles have inconsistent rotations, leading to different distances they can be built towards

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#256]
**Issue Description**
Supply piles have inconsistent rotations, leading to different distances they can be built towards.

**Expected behavior**
Supply Piles have optimized and mirrored rotations. Ideally their footprint is optimized so that Supply Centers can be built as close as possible.

**Screenshots**

![shot_20230927_121649_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e2e53eaa-9aa6-4278-bae0-9e44987ecc3b)

![shot_20230927_121700_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9b8e7d96-6455-4951-8d73-dd2b84ef65a7)

![shot_20230927_122128_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/134b554b-7107-4593-a1b3-23009c5f26e6)

![shot_20230927_122140_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ec639c33-2e41-4e20-919c-a3cfd3e28746)

![shot_20230927_122203_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/86c8e77d-48a5-4864-bbc1-b90fce0f1273)

**Comment by toirehantaa** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/093a3537-88ba-415c-bef6-5ce9b49d5e8e)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/57c6656d-6b0a-4993-a71e-25ffc3761761)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/fdea5768-d701-407f-9718-0b574f892d16)
For some reason these crates vary in their hitbox, which is weird. However, like in the first picture, a perfect supply placement is possible without much effor

**Comment by toirehantaa** [comment]
so, fixed.

**Comment by xezon** [comment]
Is better. These are still not optimal:

![shot_20230929_161643_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7630832c-83d2-4a0a-bd57-d5e7af2ffc8b)

![shot_20230929_161720_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/33b821a4-9cc7-4048-87c7-1d6de2da1572)

**Comment by toirehantaa** [comment]
fixed
