### ISSUE TITLE
[Candidate 1v1 Black Hell ZH v3] Fire pit in center could be improved

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#257]
**Issue Description**
Fire pit in center could perhaps be improved. The occasional effects and loud sounds can be stressful. It also appears to spawn a Fire Storm occasionally. Is that just an effect, or an actual Fire Storm object? Keep in mind, there can only be a maximum of 3 concurrent Fire Storms on a map. So if one Fire Storm is spawned by the map, then players would only be able to spawn 2 Fire Storms themselves at the same time.

**Expected behavior**
The rocks at the core may look better if darker, to better blend with terrain and dark theme.
And the fire may be better if constantly burning generously, with a quiet sound.

**Screenshots**

Perhaps rocks can become darker.

![shot_20230927_121849_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2c4dffa6-d394-4960-94fe-978b7b210972)

Perhaps fire can be constant, with quiet sound.

![shot_20230927_120638_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d0f58532-39d6-44f4-ba69-3238a4bc8a2a)

**Comment by toirehantaa** [comment]
I am spawning actual system objects in there, so yeah, it's an actual firestorm
I can't make these rocks darker, since they are an object, and changing it in the .ini, if it was even possible, would make ALL the rocks darker, not just those in the middle

**Comment by xezon** [comment]
So there are no black rock objects in World Builder?

Ok that Fire Storm object will affect game play then. Perhaps replace it with an innocent fire particle?

**Comment by toirehantaa** [comment]
yup, leave that to me
will not look too nice then, though, that firestorm was really cool :,)

**Comment by xezon** [comment]
Before changing, I suggest spawning 4 Fire Storm objects are the same time to see if it is indeed a problem. If 4 Fire Storms objects spawn, then likely it is not a gameplay problem.

**Comment by xezon** [comment]
So this is as designed?

**Comment by toirehantaa** [comment]
yes
