### ISSUE TITLE
[Candidate 1v1 Black Hell ZH v3] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#258]
**Issue Description**
Audio emitters have no easing. Sounds clips in and out unpleasantly.

**Expected behavior**
Sound is setup with easing. Scrolling over the map gives nice audio transitions.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7ca7b308-3920-4187-9649-8af791a91623

**Comment by toirehantaa** [comment]
fixed.
