### ISSUE TITLE
[Candidate 1v1 Black Hell ZH v3] Pathways in center do not have equal width

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#259]
**Issue Description**
The pathways in the center do not offer equal space to move in. This could be advantageous or disadvantageous. Unclear.

**Expected behavior**
Pathways are of equal or similar size on a mirrored design map.

**Screenshots**

Left center is much wider than right center.

![shot_20230927_131322_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5c284ecc-9db2-4a0c-addc-bca55e149334)

![shot_20230927_131330_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ca53a6fd-5701-4b5a-a711-7498136af3ec)

Bottom center is a bit wider than top center.

![shot_20230927_131240_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/93c92d12-f7a4-441c-865b-b26c1511e421)

![shot_20230927_131250_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7c856d97-1133-47d2-8a5c-46e4f9a8a320)

**Comment by toirehantaa** [comment]
Entrances now have the widths 150, 130, 130, and 120 at their smallest chokepoints - I think a difference of 30 feet is acceptable

**Comment by toirehantaa** [comment]
![Uploading image.png…]()

**Comment by toirehantaa** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/b8cc8ea6-a9ec-403a-8cf2-8e3751ad499d)

**Comment by xezon** [comment]
![shot_20230929_163027_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/35a91470-5023-481e-b732-66e79c48b50e)

![shot_20230929_163035_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d500c95b-5075-4509-b745-ab8ac2298698)

![shot_20230929_163045_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c9d9ecbc-1e54-4bb2-92ed-9a4c63b30b3f)

![shot_20230929_163058_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/04215e5d-22cc-4947-a5f0-e1c26e9f777d)

**Comment by toirehantaa** [comment]
retexturing is a mess, wont do - I put a rock and made the area beneath impassable

**Comment by xezon** [comment]
Distances are more comparable now. Probably is good enough.

The new placed rocks are floating above terrain.

![shot_20240121_144200_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f9f7cba7-ecfc-4660-b834-1d40b0001955)

![shot_20240121_144226_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1fe8b75a-4c7e-4b75-8243-3b5956c38ad9)
