### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] Requires unspecified tweaks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#26]
**Describe the bug**
Map requires unspecified tweaks for competitive experience and release status. Please refer to Relax for more information.

**Comment by Millard9** [comment]
What Tweaks

**Comment by xezon** [comment]
Please refer to Relax for more information. He did not specify.

**Comment by Millard9** [comment]
I asked Relax and he said "Did I ever look at your map?" if this is the case and there are no tweaks can this be closed?

**Comment by xezon** [comment]
No issue.
