### ISSUE TITLE
[Candidate 1v1 Snowy Roads ZH v3] Main Supply Dock at the bottom cannot be passed all around, but can at the top

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#260]
**Issue Description**
Main Supply Dock at the bottom cannot be passed all around, but can at the top.

**Expected behavior**
The main Supply Dock's are setup equally to offer identical strategic opportunities.

**Screenshots**

![shot_20230927_161338_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fc3af442-98ff-4561-b4cf-facb92d9a1ea)

![shot_20230927_161347_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5d515c7c-36bc-46c2-9e84-5b5f230f7f10)

**Comment by xezon** [comment]
The bottom gap is much narrower. Will just fit one Humvee instead of 2 as for the other.

![shot_20230929_160837_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b0bd66d8-6ace-40c3-8d3e-dcd8f54d8b77)

![shot_20230929_160846_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bb8c7377-19ce-4cee-ad03-ca3cfb80a2ca)

**Comment by toirehantaa** [comment]
k, readjusted the top supply to only be wide enough for one vehicle

**Comment by xezon** [comment]
Have I received that update?

**Comment by xezon** [comment]
Gap at bottom Supply Dock still is narrower. This can make significant difference for group of units trying to squeeze through.

**Comment by toirehantaa** [comment]
working on it, was on a break due to real life circumstances

**Comment by toirehantaa** [comment]
fixed now

**Comment by xezon** [comment]
I tested. 2 Humvees cannot comfortably pass at the same time. Appears to be a tiny bit too narrow still.

**Comment by toirehantaa** [comment]
I was able to line up 2 humvees next to each other, same goes for the other side as well. it is identical to me

**Comment by xezon** [comment]
Could you show image or video? I can't put 2 Humvees next to each other at the bottom, without forcing the other Humvee to move out of the way.

Here is video:

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dbfdc502-3aa3-4f0f-a4d2-4d4884948a0d

**Comment by toirehantaa** [comment]
you just managed it yourself on the video :P The top is just the same really, same space for units

**Comment by xezon** [comment]
I have created a new video to try illustrate the difference in space better:

At the top, 2 Humvees have enough space to pass by through the gap.

At the bottom, 2 Humvees do not have enough space to pass by without forcing the other to make way at the gap.

This indicates that the gap at the top is wider. Perhaps not by much, but it affects gameplay in a consistently observable way.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/29fe37db-4396-4bd5-abdd-3b1d748244c7
