### ISSUE TITLE
[Candidate 1v1 Snowy Roads ZH v3] Blobs of trees look unnatural

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#261]
**Issue Description**
Blobs of trees look dense. They sit on rock. Are tightly packed.

**Expected behavior**
Forests look more realistic if possible.
Perhaps can do with less trees, but a few rocks and bushes at their base.
And some dark sand patches instead of just rock.

**Screenshots**

![shot_20230927_161446_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/850ae961-f91c-4ce8-a3a4-b5b0671440ce)

**Comment by toirehantaa** [comment]
I quite like this blobbing, not gonna back out from that - desing by choice

**Comment by xezon** [comment]
As designed.

**Comment by ImTimK** [comment]
I personally like more natural/realistic looking environments aswell, but it isn't a big deal. Taste also differs ofcourse.
