### ISSUE TITLE
[Candidate 1v1 Snowy Roads ZH v3] Intro text is wrong

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#263]
**Issue Description**
Intro text is wrong.

**Expected behavior**
Intro text shows properly.

**Screenshots**

![shot_20230927_163705_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a021702d-f79a-426a-a97f-671a2f469f79)

**Comment by toirehantaa** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/68dabc8e-3cb7-4528-95ef-ab34c886e75f)
for some reason my .str file had an invisible character behind the String initialization - fixed now
