### ISSUE TITLE
[Candidate 1v1 Dammed Scorpion ZH v2] Supply Piles in map center are not placed in middle of island

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#264]
**Issue Description**
Supply Piles in map center are not placed in middle of island.

**Expected behavior**
Supply Piles in map center are placed in middle of island?

**Screenshots**
![shot_20230927_164809_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9e53fbcf-eff3-43ac-bdae-f365ef9ebead)

**Comment by toirehantaa** [comment]
Supply crate placement is the exact same as in sand scorpion - so the same problem resides in this map as well then

**Comment by xezon** [comment]
Yes. That is fine. Placement does not need to be a copy of Sand Scorpion. Can be different.

**Comment by toirehantaa** [comment]
crates put slightly more to the right, fixed.
