### ISSUE TITLE
[Candidate 1v1 Dammed Scorpion ZH v2] Supply Piles near spawn are not mirrored

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#265]
**Issue Description**
Supply Piles near spawn points are not mirrored.

**Expected behavior**
Supply Piles near spawn points are mirrored.

**Screenshots**

![shot_20230927_165323_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/72b1d737-2f96-4672-95c4-e600f90009ae)

![shot_20230927_165326_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/794cd0f2-349d-46d8-a99f-cd044acb38af)

**Comment by xezon** [comment]
As designed?

**Comment by ImTimK** [comment]
Also best to keep them more in a line formation towards the supply center, so that china trucks don't mess up and drive circles all day.

**Comment by xezon** [comment]
I expect the piles to be at the top of the map, right to the main supply, not south of it. Then they are correctly mirrored, or am I mistaken?

**Comment by NoMerciBKK** [comment]
IMO keep them as on sand scorpion cause the ppl are used to it and it went well all the years back without any problems

**Comment by xezon** [comment]
Ok looking at map preview it actually looks mirrored. Not sure why I expect them on the other side.

**Comment by xezon** [comment]
Spacing to map border can be made consistent:

![shot_20230927_183829_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/78801037-b18d-4bb2-8c1d-a4145c2c5ad7)

![shot_20230927_183900_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bd9bf519-721b-4fe8-9b82-5890b8ecdfbe)

**Comment by toirehantaa** [comment]
moved the bottom players crates a bit up, fixed.

**Comment by xezon** [comment]
Bottom right Supply Piles have much tighter space than the ones at top left.

![shot_20231001_164427_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/43d9138c-a3ce-45c5-8ce6-60aca1009c6d)

![shot_20231001_164437_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/27d68dfb-a815-4ebf-b6f3-ff7ce57bfc2f)

**Comment by xezon** [comment]
Still happens in latest version.

**Comment by xezon** [comment]
No blocker. As designed. Cannot be easily tweaked without changing Piles distance to Command Center.
