### ISSUE TITLE
[Candidate 1v1 Dammed Korhal ZH v3] Air units hover very low near the edges of the land

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#266]
**Issue Description**
Air units hover very low near the edges of the land. Appears to not affect gameplay. Anti Air units can properly shoot onto it from large distance. And ground units cannot shoot onto air units when hovering relatively low.

**Expected behavior**
Perhaps planes can fly higher.

**Screenshots**

![shot_20230928_080538_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d2c43e5a-0e39-4e4e-a364-b32310b7c8d9)

**Comment by xezon** [comment]
Perhaps flying height can be increased by increasing the water or terrain level a bit.

**Comment by toirehantaa** [comment]
as long as it doesn't effect - design by choice. The water should cover as little of the civilian buildings on the side as possible

**Comment by xezon** [comment]
What we can test is what happens if Aurora and Migs will attack targets on edge. Will they destroy themselves?

**Comment by DoMiNaToRuk2** [comment]
This map was designed by me and partly stolen from Starcraft 2. This water level was originally much lower but during a tournament where it was played, we increased the water height multiple times up to where it is in your screenshots.

It was played in the yota nation tournament many times among the top players and feedback was good - actually it was voted the most favourite map from the tournament.

No issues with auroras or other units were found. Only sometimes migs dip a bit only to rise again when they come back to high land but it was overall pretty. Carpet bomber originally looked bad when it was much lower but now seems acceptable. 

As it was played many times in a tourny already, i would say we can close this now as water has already been risen many times.

**Comment by xezon** [comment]
I tested a bit with Aurora, Migs, Helix and was also unable to observe problems. Closing.
