### ISSUE TITLE
[Candidate 1v1 Alfies Haven ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#267]
**Issue Description**
Audio emitters have no easing. Sounds clips in and out unpleasantly.

**Expected behavior**
Sound is setup with easing. Scrolling over the map gives nice audio transitions.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f2710d9e-49fe-401b-abe5-1765a4957779

**Comment by NoMerciBKK** [comment]
fixed
