### ISSUE TITLE
Some maps are without credits

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#269]
A few maps have no credit texts:

* Endboss ZH v2
* Proxy War ZH v1
* Battle Between Them ZH v5
* Desert Vortex ZH v7
* Lethal Mill ZH v1
* Persian Gulf Conflict ZH v5

Is not a problem. As designed? Or mistake?

**Comment by NoMerciBKK** [comment]
We can only put credits where we know the mapper.

**Comment by xezon** [comment]
Ok, so I assume these remain unknown? Close this?

**Comment by toirehantaa** [comment]
yup, we gotta close this
