### ISSUE TITLE
[Candidate 1v1 Dammed Scorpion ZH v2] AI will ignore Supply Piles near dams

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#270]
**Issue Description**
The AI will ignore the Supply Piles near dams. Eventually it passes by with some units, but it never claims that space, other than capturing Oil Derricks.

**Expected behavior**
The AI does expand, if technically possible.

**Screenshots**

![shot_20230928_091301_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c31b0482-be82-40b3-983b-ec4ead36f9ff)

**Comment by toirehantaa** [comment]
AI is not meant to reach out for supply crates in general - I am working on my own Hard Army AI, so therefore I know a LOT about AIs in C&C in general :P 
They will always try to go for supplies with a full 30000$ iirc, not a map issue, but AI in general

**Comment by xezon** [comment]
Not map bug.
