### ISSUE TITLE
[Candidate 1v1 Dammed Scorpion ZH v2] There is a gap in the water at destroyed dam

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#271]
**Issue Description**
There is a gap in the water at destroyed dam. Is most visible when the fog hides the particles.

**Expected behavior**
No gap in water near dam.

**Screenshots**

![shot_20230928_091914_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/932f813d-c8cc-4ddb-857b-bd9698c268e9)

**Comment by toirehantaa** [comment]
fixed.
