### ISSUE TITLE
[Candidate 1v1 Dammed Scorpion ZH v2] FPS drops by about 25% when a dam breaks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#272]
* Relates to #244
* Relates to #231

**Issue Description**
FPS drops by about 25% when a dam breaks.

**Expected behavior**
FPS does not drop when a dam breaks.

**Screenshots**

![shot_20230928_092313_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7951bfc6-c9b1-4787-8dc8-054bf0495588)
![shot_20230928_092325_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/463d14b7-684c-4a6b-b1fe-870f9ea2c733)

**Comment by DoMiNaToRuk2** [comment]
Is 25% that bad?

What other games don't drop FPS by 25% when the really heavy graphical part of gameplay comes onto the scene? Are there any at all?

**Comment by xezon** [comment]
Close to 0% would be better. It is not labeled blocker bug, but it is recommended to fix this and it likely is possible to improve, because there are maps with rising water that do not lag like this.

**Comment by xezon** [comment]
Still happens in latest version.

**Comment by toirehantaa** [comment]
with the new fix should be fine now

**Comment by xezon** [comment]
FPS drop is not that high. Not a blocker. Acceptable.
