### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#274]
**Issue Description**
Audio emitters have no easing. Sounds clips in and out unpleasantly.

**Expected behavior**
Sound is setup with easing. Scrolling over the map gives nice audio transitions.

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
This was not closed, which should mean it was not fixed.
