### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Lightning is unnaturally dark

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#275]
**Issue Description**
Lightning (shadows) is unnaturally dark. It causes dark shadows on faction structures. And seemingly also on foliage.

**Expected behavior**
Lightning looks natural.

**Screenshots**

![shot_20230928_100259_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fbfd118d-a1e2-40d2-b440-bdd89bc1a8ab)

![shot_20230928_100916_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/14757f97-c15f-4dc8-9f92-d7c53bce97b0)

**Comment by toirehantaa** [comment]
That is because of the rotation of the sun, not the lightning level - I change the angle to match with the players view better. fixed.
