### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Oil Derricks on the left side have different rotations

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#276]
**Issue Description**
Oil Derricks on the left side have different rotations.

**Expected behavior**
Oil Derricks have identical rotation. Prefer default rotation to show flag and pump best.

**Screenshots**

![shot_20230928_100827_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b441bf8f-bd5a-4673-812e-331d7131c459)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
Is unchanged.

**Comment by toirehantaa** [comment]
Did I send the wrong version?

**Comment by xezon** [comment]
Perhaps. Some things were fixed.
