### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Units can glitch over steep terrain of Aztec temple

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#277]
**Issue Description**
Units can glitch over steep terrain of Aztec temple.

**Expected behavior**
Units do not glitch over steep terrain of Aztec temple.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/258cafb1-729a-4b86-9d04-d3c8791fd43d

**Comment by xezon** [comment]
Not sure if this should be a blocker. Perhaps happens with USA Dozer only, because of its unique turning locomotion.

**Comment by toirehantaa** [comment]
yup, its also unfixable with this level of steepness - I think we better close this, as I am pretty sure all the maps with such conditions face this bug
