### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Oil Derrick on temple is sunk into terrain, casts shadow on slope

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#278]
**Issue Description**
Oil Derrick on temple is sunk into terrain, casts shadow on slope.

**Expected behavior**
Oil Derrick on temple is not sunk into terrain, does not cast shadow on slope.

**Screenshots**

![shot_20230928_102654_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c120a176-0a8d-4446-9e8d-19b4be2fd44e)

**Comment by toirehantaa** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/56462711-19a9-4b57-9bdd-75cc4f595064)
changing the abgle fixed the shadow issue
