### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Top right Supply Dock cannot be driven around, but bottom right Supply Dock can

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#279]
**Issue Description**
Top right Supply Dock cannot be driven around, but bottom right Supply Dock can.

**Expected behavior**
Mirrored base Supply Docks offer equal space for unit mobility and building.

**Screenshots**

![shot_20230928_103302_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8611710a-2bd6-4917-b96b-3364c6a16cb8)

![shot_20230928_103316_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5e91d30b-67d7-4a70-8414-73df2f0d6645)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
Fix looks strange. The terrains still looks passable, but they aren't. Perhaps but some big rocks there to properly communicate the terrain limits?

![shot_20231001_155350_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fadea88d-eac1-417a-a6d1-c503c5a435f0)

![shot_20231001_155427_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/56b6bf6e-ddf5-4d22-89f8-1ee130d1e08d)

**Comment by toirehantaa** [comment]
Rocks here we go, fixed
