### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Bottom Supply Dock offers more movement opportunities than top Supply Dock

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#280]
**Issue Description**
Bottom Supply Dock offers more movement opportunities than top Supply Dock.

**Expected behavior**
Mirrored base Supply Docks offer equal space for unit mobility and building.

**Screenshots**

![shot_20230928_103207_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/97afc848-924c-428e-a80d-3dd7e207c1ea)

![shot_20230928_103218_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d108c2ad-d614-4b49-aaed-b94087445733)

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
Fix looks strange. The terrain still looks passable, but it is not. Perhaps but big rocks there to properly communicate the terrain limits?

![shot_20231001_155608_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c8076fca-fcdb-4b4f-94be-79b36d020a30)

**Comment by toirehantaa** [comment]
big rocks here we go, fixed

**Comment by xezon** [comment]
Looks good at the bottom.

At the top it was not really necessary to place rock. New rock clips into the Supply Dock. Looks odd.

![shot_20231206_202038_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/531e5253-1d74-4245-af27-65ffe0a6b5bc)

**Comment by xezon** [comment]
Fixed. Rock is still there.
