### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Top left Supply Piles cannot be driven around, but bottom left Supply Piles can

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#281]
**Issue Description**
Top left Supply Piles cannot be driven around, but bottom left Supply Piles can.

**Expected behavior**
Mirrored base Supply Piles offer equal space for unit mobility and building.

**Screenshots**

![shot_20230928_103048_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4f7b9be2-7774-4f77-81eb-93f1397c8c55)

![shot_20230928_103119_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/53aaa3d6-0dcc-40f1-82a8-efe440b5d7cb)

**Comment by toirehantaa** [comment]
fixed.
