### ISSUE TITLE
[Candidate 2v2 District 10 ZH v5] FPS drops by about 55% when a dam breaks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#283]
**Issue Description**
FPS drops by about 55% when a dam breaks. On my machine from 64 FPS to 28 FPS.

**Expected behavior**
FPS does not drop when a dam breaks.

**Screenshots**

![shot_20230928_105545_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cea8f433-746b-4707-9caf-d21cc578f502)

![shot_20230928_105549_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f0f6b1ba-bf33-416a-a8b5-e3d386c87afc)

**Comment by ImTimK** [comment]
I have a feeling it can't be totally fixed. 

If it's a short lasting drop that doesn't completely crash lower-end systems it would be acceptable?

**Comment by xezon** [comment]
It appears this frame drop is related to the duration the water raises. I have a map where the water level rises in an instant, which gives just a very short stall.

So to me it looks like this can be optimized by 

a) Reduce the number of water chunks that raise one after another.
b) Reduce the duration the water chunks raise by.

**Comment by toirehantaa** [comment]
since the water areas that rise are already at 0.01, I don't think we can reduce it further.
7 Water areas in total are risen on a blow - reducing them means making the rising process visible under the fog, so a downgrade for map design

**Comment by xezon** [comment]
What does the 0.01 stand for? When hiding the particles, I can see the water volume slowly moves up. Can you try move it up instantly?

**Comment by toirehantaa** [comment]
water rising in 0.01 seconds to altitude x - I don't know why it rises slowly for you

**Comment by xezon** [comment]
According to video here https://github.com/TheSuperHackers/GeneralsRankedMaps/issues/244#issuecomment-1737060594 the water takes more than 0.01 seconds to raise. Perhaps implementation is scaling differently on different hardware.

In the test map I linked the water raise is instant. May I suggest to replicate the water raise to how it is done in the test map?

**Comment by toirehantaa** [comment]
May I ask you to send me the test map then? I want to take a look at the scripts

**Comment by xezon** [comment]
You can download it from

https://github.com/TheSuperHackers/GeneralsGamePatch/tree/main/Maps/Any/!TestRisingWater

**Comment by xezon** [comment]
In "Dammed Cottages ZH v1" I am unable to observe extra performance degradation on dam break. Perhaps check what is done differently there. Map performance is low over all though. "Dammed Cottages ZH v1" runs with 75 FPS on my machine.

**Comment by DoMiNaToRuk2** [comment]
This can likely be fixed by removing the particles which hide the water level rising. I know Tanso did this to make it look pretty but if you check a map called Crazy Beach (in google drive) then you will find other mappers are able to make flooding from dams without the particles and still look good. When I played this map in a 2v2 challenge, the lag was crazy for me and I have a strong PC. I already informed Tanso about this. The screenshake also might need reducing or removing.

**Comment by DoMiNaToRuk2** [comment]
played in excals tournament - no complaints, wont be fixed

**Comment by xezon** [comment]
I have observed performance improvement. It now drops just from about 70 to about 55 FPS on my machine. Much better. I will remove blocker label because the other bug with 25% drop is also no blocker.

**Comment by xezon** [comment]
Remaining performance drop is acceptable. Fixed.
