### ISSUE TITLE
[Candidate 2v2 District 10 ZH v5] Structures are z clipping at many places

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#284]
* Related to #232

**Issue Description**
Structures are z clipping at many places. It has a notable negative visual impact on the otherwise beautiful environment.

**Expected behavior**
Structures are not z clipping. This can be avoided by varying the height of structures by a tiny amount. Polygons must not share the same plane.

**Screenshots**

![shot_20230928_104948_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/901c6288-41f2-4d8a-b3ac-87c6e70721fe)

![shot_20230928_110143_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8067b00b-68df-40e8-8396-6c1470fc6877)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
Looks much better.

There is still clipping on the sides everywhere. Not as obvious.

![shot_20230929_164428_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3935d0ba-84e6-4452-ac2d-a4564665c5bc)

![shot_20230929_164442_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/85201a44-fc68-4e1f-9346-2d3770dcce8d)

**Comment by toirehantaa** [comment]
not gonna fix that. this would take me hours trying to readjust the height when putting them further back

**Comment by xezon** [comment]
I think it is not the height, but the X Y position. Essentially these would need small variations too to avoid polygon overlaps.

**Comment by toirehantaa** [comment]
that's what I meant. adjusting the x and y position will alter the height, since everything is placed on a slope. readjusting the height accordingly is something I will not do - too much effort for the effect

**Comment by xezon** [comment]
Ok makes sense. Then this will have to do.

**Comment by DoMiNaToRuk2** [comment]
To be honest on this one I also don't like the edges. I was also not keen on the edges on Dammed Korhal. But it seems the fixes are too hard to do and the players nor the viewers have mentioned this at all, so I would say fine to go ahead. However, we should stop this on future maps - we have seen it is possible to make nice edges, like on Tourament Spaceship for example.

**Comment by xezon** [comment]
TanSo has already polished the upper edges all around the map. They no longer clip. So this is already much much better. The remaining clippings are not as visible.
