### ISSUE TITLE
[Candidate 2v2 District 10 ZH v5] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#285]
**Issue Description**
Audio emitters have no easing. Sounds clips in and out unpleasantly.

**Expected behavior**
Sound is setup with easing. Scrolling over the map gives nice audio transitions.

**Videos**

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/737ee010-3ea9-4c9b-8fef-b0eba459451f

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
The machinery sound are now emitted from here, but there is no infrastructure to support this sound. Shouldn't it be placed somewhere else?

![shot_20230929_164926_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/04573c4c-0f3a-4ba5-8180-aa9e450f8ecc)

**Comment by toirehantaa** [comment]
alright, done
