### ISSUE TITLE
[Candidate 2v2 District 10 ZH v5] Supply Piles in front of bases enable inconsistent mobility

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#286]
**Issue Description**
The Supply Piles in front of bases enable inconsistent mobility. At one pack, vehicles cannot pass. One on each team side.

**Expected behavior**
All Supply Piles can be moved around equally. No confusion.

**Screenshots**

Vehicles can drive around.

![shot_20230928_110919_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eb00831e-2575-4a04-a1d5-31b9f0c387f7)

![shot_20230928_110953_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/162f5a70-074a-49b7-adb4-91fbec42b8f4)

Vehicles can not drive around, but infantry can move around.

![shot_20230928_111024_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4451fe63-4cf5-4d13-874a-bd4db9580b86)

![shot_20230928_111111_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6b9aa209-00dd-448f-bcc7-2a9fb237fecf)

**Comment by toirehantaa** [comment]
fixed.
