### ISSUE TITLE
[Candidate 2v2 District 10 ZH v5] Map has relatively low performance

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#288]
**Issue Description**
Map has relatively low performance. Base performance on my machine is about 60 to 70 FPS. In battle situations performance will be 50% lower than that.

For reference, 2v2 Fallen Empire is about 250 FPS on my machine.

**Expected behavior**
Map performance is better.

**Screenshots**

70 FPS looking at terrain.

![shot_20230928_105634_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fdd15bc7-09dd-4835-951c-9c6b305027a7)

35 FPS in combat.

![shot_20230928_112618_49](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f574982a-049b-4458-ada5-1c2fb2a4644e)

**Comment by xezon** [comment]
Not sure what can be done here. Remove some trees? I suspect the world object count is the problem.

**Comment by FiReArM-ZH** [comment]
Can you try once without map.ini?

**Comment by toirehantaa** [comment]
to be honest, you're the first with such low performance o.0

**Comment by xezon** [comment]
No performance improvement with map.ini removed.

**Comment by toirehantaa** [comment]
The object count is not a problem, it is having < 1600 objects which is half of what the WB suggests with 3000 max. I have a map with 3800 and it has seemingly better performance

**Comment by xezon** [comment]
Can you reproduce low performance locally or are you blind on this?

**Comment by toirehantaa** [comment]
I'll do some tests

**Comment by xezon** [comment]
Min base performance has risen from 60 FPS to 145 FPS on my machine. Big improvement.
