### ISSUE TITLE
[Candidate 1v1 Fort Payne ZH v1] Bottom city has 8 usable structures, top city has 9

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#290]
**Issue Description**
Bottom city has 8 usable structures, top city has 9.

**Expected behavior**
Both cities have equal amount of usable structures, because the Oil Derrick placement is asymmetric at top and bottom.

**Screenshots**

![shot_20230928_120711_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/471800c8-9522-4aa2-a3d3-343d714360b6)

![shot_20230928_120728_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b9b4f831-2793-4cdf-91d0-3f7650f100c6)

**Comment by xezon** [comment]
Unless I count wrong, there are now 9 houses at the top, and 7 houses at the bottom.

**Comment by FiReArM-ZH** [comment]
![IMG_20240124_012910](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79019227/e5da1067-5352-447b-9403-9f650f8ede0c)
I'm pretty sure i have deleted one of these

**Comment by xezon** [comment]
Can you count again? I swear I counted 9 on top.

**Comment by xezon** [comment]
Both sides now have 9 houses each.
