### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] One bunker at bottom right base can hit Oil Refinery, but not at the other side of the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#309]
## Observed behaviour

ne bunker at bottom right base can hit Oil Refinery, but not at the other side of the map

## Expected behavior

Bunkers have consistent reach to important infrastructure on both sides of the map.

## Screenshots

![shot_20230928_154403_76](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3a365a55-1655-4a06-acdc-731dc9b90180)

**Comment by NoMerciBKK** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/716cb3c3-345e-4829-a926-57c67b6fc20e)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/415aab03-97e6-4525-b3f1-5b4a9487b02b)
 both can be killed now form all 4 bunkers but you need to prefire the ground (as intended)

**Comment by xezon** [comment]
It is difficult to do. They shoot at very tiny specific spots only.

**Comment by NoMerciBKK** [comment]
well yes it should be like this a "safe" refinery in back but you do have the option to kill it from all bunkers and tbh most ppl wont kill it with the bunkers anyway you d rather attack the supplys
