### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Units can better shoot down the cliff at the bottom center Artillery Platform

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#310]
## Observed behaviour

Units can better shoot down the cliff at the bottom center Artillery Platform. At the top center Artillery Platform units will have less reach.

## Expected behavior

Cliffs provide equal opportunity to attack things near Supply Piles.

## Screenshots

![shot_20230928_154111_72](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bade7b94-1d76-48d7-b60b-a1517cfbb8c8)

![shot_20230928_154114_73](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/194504d5-e345-4e94-9c24-1e022abf2cba)

**Comment by NoMerciBKK** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/7a031a10-ba0c-4ffe-b8df-d9e921a0132b)
Updated version fyi will be sended after all is fixed
