### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Many rocks float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#311]
## Observed behaviour

Many rocks float above terrain.

## Expected behavior

Rocks sit on terrain.

## Screenshots

![shot_20230928_153535_68](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/86e5739a-face-413c-9500-8271180132f6)

![shot_20230928_153545_69](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/94c7633e-7123-4714-b5e0-35cbb086f289)

![shot_20230928_153557_70](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fbd6e288-cc91-4ce9-87ad-37cccfee30eb)

![shot_20230928_153619_71](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fc438dc1-6b74-43d4-8669-37b0ec577fd2)

**Comment by NoMerciBKK** [comment]
fixed in newest version

**Comment by xezon** [comment]
Looks mostly good now. There are still a few left over ones.

![shot_20231001_094529_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eb3251c7-ccd2-493b-a8ea-caa9b640b5bc)

![shot_20231001_094556_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/18014baf-516d-4a0c-be0a-39598e4149d0)
