### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Units can move into explosive trucks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#312]
## Observed behaviour

Units can move into explosive trucks.

## Expected behavior

Units can not move into explosive trucks.

## Screenshots

![shot_20230928_153513_67](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/67eefe5e-11c5-43a9-b5b8-9d2c321da093)

**Comment by NoMerciBKK** [comment]
intended you can bloe them up for dmg but if i make it impassible it might block building space

**Comment by xezon** [comment]
As designed.
