### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] One Oil Derrick clips into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#313]
## Observed behaviour

One Oil Derrick clips into terrain.

## Expected behavior

No Oil Derrick clips into terrain.

## Screenshots

![shot_20230928_153313_66](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e611146-9876-4ba3-a964-7c7d826dad93)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
There is another one, but more difficult to see.

![shot_20231001_094837_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/33788f1d-ff34-4630-baf7-a0ee91f27101)

**Comment by NoMerciBKK** [comment]
its covert in snow so i d say it can stay as it is

**Comment by xezon** [comment]
Is not optimal, but ok.
