### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Boat clips through water

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#314]
## Observed behaviour

Boat clips through water.

## Expected behavior

Boat does not clip through water

## Screenshots

![shot_20230928_152720_61](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0aa01aa0-c74a-45c2-a455-2a3070770f70)

**Comment by NoMerciBKK** [comment]
fixed
