### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Tech Buildings are located too close to the map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#315]
## Observed behaviour

Tech Buildings are located too close to the map border. Some of them are less visible by default.

## Expected behavior

There is a bit of distance between map border and Tech buildings.

## Screenshots

![shot_20230928_152125_50](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/13dbb8ae-d30c-4203-89d8-0e59c9867776)

![shot_20230928_152137_51](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd7ac5fc-72c3-4055-8ef9-be3e112e7493)

![Untitled-2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9640933a-cd86-41d0-a38b-c3425861f76f)

**Comment by NoMerciBKK** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/70d4fc89-505d-4b86-9c51-3bc8c933fb2a)
fixed hope it works fine now cause i do not have the default design
