### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Supply Docks and Piles have different distances to each other on each side of the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#316]
## Observed behaviour

Supply Docks and Piles have different distances to each other on each side of the map.

## Expected behavior

Distances are comparable and fair.

## Screenshots

![shot_20230928_152431_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f7595bf3-2796-4536-b6de-1f4cfd8c0062)

![shot_20230928_152438_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1010cb55-265e-49db-913f-3bd75b0dc7e4)

**Comment by xezon** [comment]
Not sure if this is a blocker.

**Comment by NoMerciBKK** [comment]
fixed
