### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Top left corner hosts an object that is unattackable but can be destroyed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#317]
## Observed behaviour

Top left corner hosts an object that is unattackable but can be destroyed. After it has been destroyed it looks the exact same.

## Expected behavior

Object is removed or replaced or fixed.

## Screenshots

![shot_20230928_152536_54](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d34f7d06-92f1-4021-867c-57cbb6112916)

![shot_20230928_152545_55](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/27d682de-928a-4ce3-a5ef-447d8f42b615)

**Comment by NoMerciBKK** [comment]
fixed
