### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Tech Buildings have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#320]
## Observed behaviour

Tech Buildings have custom rotations that make their flag less visible.

## Expected behavior

Tech Buildings preferably have default rotation or a rotation that makes their flag highly visible.

## Screenshots

![shot_20230928_152753_62](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/69780e90-7c8a-4089-8f00-28be64b801e9)

**Comment by NoMerciBKK** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/3c7fa52b-8b98-4b38-966b-37e9e6f2e352)
this is the default rotation

**Comment by xezon** [comment]
I see. In INI it has no placement angle.

The common placement angle in Official Maps is this.

It gives best view on flag and pump in default camera rotation.

![shot_20230928_172927_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b4e0782a-d32d-4a02-b5f7-86623fcf2d8f)

**Comment by NoMerciBKK** [comment]
rotated a bit in newest version should be fine now

**Comment by xezon** [comment]
I see no difference. The easiest fix here would be to rotate the oil by 90 degrees clock wise. Then flag would be highly visible.

![shot_20231001_101308_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/89f0bec7-f48f-4488-9b66-f469e7f2fc6a)

**Comment by xezon** [comment]
Some Oil Derrick rotations were optimized. Some others not.

**Comment by NoMerciBKK** [comment]
tbh i dont want them all look in the same direction all flags are visible so thats fine for me as designed

**Comment by xezon** [comment]
In my opinion Oil Derrick rotations are not ideal.

Here Oil Derricks have different rotations unnecessarily. And one of them is partly covered by tower, which could make it a bit harder to see nearby infantry capturing it.

Their rotation is straight (~0, 90, 180, 270 degrees).

![shot_20231007_090855_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c842c2a6-51de-42e8-9b26-389a4736eef7)

Bottom oils have non straight rotation (~45, 135, 225, 315 degrees).

![shot_20231007_090909_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c4121ca8-6252-466e-98d6-5ac648032c1c)

Base Oils also have straight and non straight rotations.

![shot_20231007_090932_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a9d36d5d-acbc-45f0-8694-d114b79d1d86)

![shot_20231007_090947_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9279b888-d3ec-41eb-a0db-bd804e91095c)

**Comment by NoMerciBKK** [comment]
yes this is intended, the base rotation is like this to not fuck up the path to the bunkers and still make the flag visible as you guys prefer, the oils behind the tower are suppost to be behind it, if it falls it kills the oil, both players shall have the same angle and range for balance thingies so all as designed

**Comment by xezon** [comment]
View on flag is greatly blocked.

![shot_20231203_104102_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aaa18741-77e0-4705-86f7-7afcf50e537e)

**Comment by xezon** [comment]
I expect that the visibility of the flag can be optimized by rotating the Oil Derrick.

**Comment by NoMerciBKK** [comment]
> I expect that the visibility of the flag can be optimized by rotating the Oil Derrick.

updated
