### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] There are a few small gaps in fences

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#321]
## Observed behaviour

There are a few gaps in fences.

## Expected behavior

No small gaps in fences.

## Screenshots

![shot_20230929_080632_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b781def3-da64-400a-8181-ef178093354c)

![shot_20230929_081041_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6dc4ba3f-4bf7-4d0e-922b-300c33ad1a3a)

![shot_20230929_083532_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cf38ec60-ae69-4316-89f3-ff47a64a9d71)

![shot_20230929_083545_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e8a0f8dc-9018-4d32-ae14-42b6f833be2e)

![shot_20230929_083612_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cdad483e-028f-4e2f-9f29-c2ddc470a29f)

![shot_20230929_083648_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e9e3b3da-9d31-4f8e-bf1f-231bc2aaf026)

**Comment by NoMerciBKK** [comment]
fixed
