### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Road segments near home bases have imperfections

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#322]
## Observed behaviour

Road segments near home bases have imperfections.

## Expected behavior

Road segments are connected and smoothened well.

## Screenshots

![shot_20230929_080451_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/905b964c-b5f9-4411-abf7-4031e2815187)

![shot_20230929_083433_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3d6b430a-344d-4749-9ed9-2dc7ec827816)

**Comment by NoMerciBKK** [comment]
fixed
