### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Toxic Bunker and Town House have inferior fire ports setup

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#323]
## Observed behaviour

Toxic Bunker and Town House have inferior fire ports setup. Infantry units will shoot from 0,0,0 because there are no or little fire ports available. The Town House has some fire ports, so it can shoot over the fence with an infantry unit. The Toxic Bunker has none. Rocket Men shooting from 0,0,0 will increase the chances of damaging the building they sit in.

## Expected behavior

Used houses have appropriate amounts of fire ports.

## Screenshots

![shot_20230929_081358_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/16ecf0ba-6a66-4181-bcb1-b26df85176f6)

![shot_20230929_081420_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/52ac41bb-f223-4c5b-8d75-6957b1b9db1b)

![shot_20230929_081525_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/494c657a-1df5-41d7-a824-b2aeeccb1f3f)

![shot_20230929_081537_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9fa0005a-65e2-4959-a348-f5ee079cfaf3)

**Comment by NoMerciBKK** [comment]
fixed pls check if it is fine can be closed

**Comment by xezon** [comment]
Much better. Fire ports work.

I suggest to also rotate the structure by 180 degrees so that the fire ports are certainly equal.

![shot_20230929_170137_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f067c32-954d-4127-8821-50f120f68523)

![shot_20230929_170141_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5120c5ef-17bb-425b-834e-d88b799e4519)

**Comment by DoMiNaToRuk2** [comment]
is this fixed? can be closed?

**Comment by xezon** [comment]
It is better yes. The only missing tweak here is to make rotation of building mirrored, to have more equal conditions (because fireports have fixed positions on buildings, it is good idea to mirror all structures).

**Comment by NoMerciBKK** [comment]
> It is better yes. The only missing tweak here is to make rotation of building mirrored, to have more equal conditions (because fireports have fixed positions on buildings, it is good idea to mirror all structures).

this is also fixed in V5 i send to you last month

**Comment by xezon** [comment]
This is fixed.
