### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Oil Derrick at bottom left has unaligned rotation

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#324]
## Observed behaviour

Oil Derrick at bottom left has unaligned rotation.

## Expected behavior

Oil Derrick is rotated in 45 degree step.

## Screenshots

![shot_20230929_080542_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c818bda3-4ffe-4d6c-bd10-075d621cffa8)

**Comment by NoMerciBKK** [comment]
fixed can be closed
