### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Tech Buildings have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#327]
## Observed behaviour

Tech Buildings have custom rotations that make their flag less visible.

## Expected behavior

Tech buildings preferably have default rotation or a rotation that makes their flag highly visible.

## Screenshots

![shot_20230929_081933_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f0781831-3535-4e8c-bb57-3f9053f04967)

![shot_20230929_081941_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/53212e63-5d9b-41ec-9102-91d80cfec795)

**Comment by NoMerciBKK** [comment]
fixed can be closed

**Comment by DoMiNaToRuk2** [comment]
the yellow part of the oils need to be facing left,

refinery needs to have its pipes at the top right position,

arty platform needs to face south position

**Comment by DoMiNaToRuk2** [comment]
No Merci whats the latest on this?

There are several people holding up this project and this is not helping. Can you fix the rotations and any other open issues on this map please?

**Comment by NoMerciBKK** [comment]
> No Merci whats the latest on this?
> 
> There are several people holding up this project and this is not helping. Can you fix the rotations and any other open issues on this map please?

this is not a blocker and its fixed since a few weeks

**Comment by NoMerciBKK** [comment]
latest version 
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/0123391b-7a6b-42df-9b6e-3e879d9e5c6a)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/2c049bf6-5223-448b-92ce-80d1f83279e1)

**Comment by xezon** [comment]
This is not the version I have received, unless I made mistake.

**Comment by NoMerciBKK** [comment]
> This is not the version I have received, unless I made mistake.

its the V5 version i send to you on 29.09.23
