### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Repair Bay position and rotation is not properly mirrored

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#328]
## Observed behaviour

Repair Bay position and rotation is not properly mirrored.

## Expected behavior

Repair Bay and Supply Piles have mirrored positions and rotations.

## Screenshots

![shot_20230929_090024_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/efaf8d06-f821-4dd5-9000-fc52842f0d2b)

![shot_20230929_090055_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9b9a63c3-4a66-4dce-b995-4d4270f4e580)

![shot_20230929_090212_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a88fb846-08b2-4252-ab6d-d3e0bf7ed518)

![shot_20230929_090216_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1f3102b1-d94f-4131-ba6d-4da9140c7fa4)

**Comment by NoMerciBKK** [comment]
fixed can be closed and the gab is +-10 ft so as designed

**Comment by NoMerciBKK** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/2a890422-962c-48a2-a3cf-57f5335190ea)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/576a6abb-1bd6-4303-a166-fa047ad32f4c)

**Comment by xezon** [comment]
-115 +180 = 65, not -65

**Comment by NoMerciBKK** [comment]
65 -65 is still mirrored about the central axis

**Comment by xezon** [comment]
I don't get it. Shouldn't both Repair Bays have the same rotation towards the middle bridge?

**Comment by NoMerciBKK** [comment]
ahh this is what you meant so they d face to the middle, nah for me they should just look to the central axis

**Comment by xezon** [comment]
Ok. Looks odd to me but if so desired, closed.
