### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Grass patch near Repair Bay makes it look as if there was a dent in terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#329]
## Observed behaviour

Grass patch near Repair Bay makes it look as if there was a dent in terrain.

## Expected behavior

Grass patch is removed. Terrain looks flat.

## Screenshots

![shot_20230929_083840_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ddebdd87-1b71-4afe-a03d-db3e42ae1d31)

**Comment by NoMerciBKK** [comment]
fixed can be closed
