### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Fenced Oil Derricks appear to have different positions

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#330]
## Observed behaviour

Fenced Oil Derricks appear to have different positions. Their distance to fences are different. Or the fences are not properly positioned.

## Expected behavior

Oil Derrick placements are mirrored.

## Screenshots

![shot_20230929_081659_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0b11b8af-ce92-4be9-bbd0-66c89932f17f)

![shot_20230929_081707_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d2cb779e-4f74-41ea-90a8-10930e4f09eb)

**Comment by NoMerciBKK** [comment]
same possition just designed a bit different with the fence can be closed

**Comment by xezon** [comment]
As designed.
