### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] AI at top spot does not work

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#331]
## Observed behaviour

AI at top spot does not work.

## Expected behavior

AI works at all spots.

## Screenshots

![shot_20230929_092306_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/506ec29f-e28d-4797-b32d-129f9628353b)

**Comment by NoMerciBKK** [comment]
AI is working properly now
