### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Audio crackling when scrolling over map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#332]
## Observed behaviour

There is a bit of audio crackling when scrolling over the map.

## Expected behavior

Audio is setup well with smooth transitions. No crackling when scrolling around map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cb986d92-1eac-490b-bf02-b19a84667097

**Comment by NoMerciBKK** [comment]
hope i fixed it pls check in newest version
