### ISSUE TITLE
[Candidate 2v2 Spiders Island ZH v1] Tech Buildings have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#334]
## Observed behaviour

Tech Buildings have custom rotations that make their flag less visible.

## Expected behavior

Tech buildings preferably have default rotation or a rotation that makes their flag highly visible.

## Screenshots

![shot_20230929_104218_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8675d025-4fd1-404c-b09e-455e846b261a)

**Comment by NoMerciBKK** [comment]
as designed
