### ISSUE TITLE
[Candidate 2v2 Spiders Island ZH v1] Some coast lines look unnatural

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#335]
## Observed behaviour

Some coast lines look unnatural.

## Expected behavior

Coast lines look natural by hosting variations in terrain.

## Screenshots

![shot_20230929_104343_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a1ec03c2-f5c0-476a-a59e-681b1e022d10)

**Comment by NoMerciBKK** [comment]
as designed
