### ISSUE TITLE
[Candidate 2v2 Spiders Island ZH v1] Several path ways lead close to water

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#336]
## Observed behaviour

Several path ways lead close to water. As designed?

## Screenshots

![shot_20230929_104519_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aaf77afb-ef75-4f7e-9d7f-979dae9bd31c)

![shot_20230929_110237_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b8d4eac5-229b-4bdf-a771-ce9dc9720331)

**Comment by NoMerciBKK** [comment]
yes as designed rock texture is impassible sand is passible
