### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Repair Bay can be driven around on one side, but not the other

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#337]
## Observed behaviour

Repair Bay can be driven around on one side, but not the other. They also have non-mirrored rotations.

## Expected behavior

Mirrored Repair Bays offer equal space for unit mobility.

## Screenshots

![shot_20230929_111352_54](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c6734867-2ad2-428f-925f-01aadb3a2904)

![shot_20230929_111404_55](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/83202df7-012b-4e2c-99d4-dae8db75abaf)

**Comment by NoMerciBKK** [comment]
fixed
