### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Supply Piles near train tracks have different gap size to map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#338]
## Observed behaviour

Supply Piles near train tracks have different gap size to map border.

## Expected behavior

Mirrored Supply Piles offer equal space for unit mobility.

## Screenshots

![shot_20230929_111548_56](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4a486338-2625-4248-b1cf-3a98de27d61f)

![shot_20230929_111554_57](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/317488a3-4cc0-40d7-ae7c-ad8cdba2e84e)

**Comment by NoMerciBKK** [comment]
fixed
