### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Top left Supply Piles cannot be driven into, but bottom right Supply Piles can not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#339]
## Observed behaviour

Top left Supply Piles cannot be driven into, but bottom right Supply Piles can not.

## Expected behavior

Mirrored Supply Piles offer equal space for unit mobility.

## Screenshots

![shot_20230929_111625_58](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dce24556-b82f-4215-93ac-447c70b7e214)

![shot_20230929_111631_59](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e90a1eb0-4389-4ce3-b3c2-396f547baca0)

**Comment by NoMerciBKK** [comment]
fixed
