### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Rocky terrains under Oil Derricks and Supply Piles look unnatural

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#340]
## Observed behaviour

Rocky terrains under Oil Derricks and Supply Piles look unnatural.

## Expected behavior

Terrain around Oil Derricks and Supply Piles looks beautiful and natural.

## Screenshots

![shot_20230929_111737_60](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0f261415-221d-49fa-a30d-093797694eef)

![shot_20230929_111755_61](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/debcc97a-1946-4954-9b93-5e673a122659)

**Comment by NoMerciBKK** [comment]
shall look like this for better visuality in gameplay cause you may overlook the piles if its green on green

**Comment by xezon** [comment]
Perhaps dark brown sand patches could work better there?

**Comment by NoMerciBKK** [comment]
yes i d agree they may look better but you have no sand on the Nockberge its all gravel there

**Comment by xezon** [comment]
Is there Oil in Nockberge? If not, then it already is unrealistic. I suggest get rid of the straight terrain paint edges around the Oil Derricks and try some sand.

**Comment by NoMerciBKK** [comment]
sadly austria do have oil derricks next to the alps :D so i d keep it as designed
