### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Some mountains have gentle slopes which give the impression that they are passable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#342]
## Observed behaviour

Some mountains have gentle slopes which give the impression that they are passable, while they are not.

## Expected behavior

Mountains have sufficiently steep slopes near important infrastructure.

## Screenshots

![shot_20230929_112138_68](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7bef8086-b783-4db2-ae64-a002f5ac3650)

![shot_20230929_114402_84](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1de9dc24-21e9-4c01-94b9-bfc200f07815)

**Comment by NoMerciBKK** [comment]
its designed as the "Real" Nockberge so they supposted to be flat there thats why the terrain is marked as it is with the "Cliff" texture

**Comment by xezon** [comment]
It is ambiguous. There are other maps where units can drive over terrain like this. Perhaps put a bunch of big rocks on top of it?

**Comment by NoMerciBKK** [comment]
can do this shure

**Comment by xezon** [comment]
New rocks are partly floating above terrain. Otherwise looks good. Perhaps use higher rocks so they can be sunken into terrain on slopes.

![shot_20231001_160844_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ba93f36c-a7eb-4888-8c2a-7f5f943bf56a)

**Comment by DoMiNaToRuk2** [comment]
I am fixing this now and will upload new version in Maps Proposal topic on gamereplays with fixed terrain and floating rocks removed.

**Comment by NoMerciBKK** [comment]
@xezon is this now fixed in the last version i send to you? so that it can be closed?

**Comment by NoMerciBKK** [comment]
@xezon
