### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Tech Buildings have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#343]
## Observed behaviour

Tech Buildings have custom rotations that make their flag less visible.

## Expected behavior

Tech buildings preferably have default rotation or a rotation that makes their flag highly visible.

## Screenshots

![shot_20230929_112247_70](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/216b995d-9946-433e-ab87-974a341c8207)

**Comment by NoMerciBKK** [comment]
fixed
