### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Units can move through big rocks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#345]
## Observed behaviour

Units can move through big rocks.

## Expected behavior

Units can not move through big rocks.

## Screenshots

![shot_20230929_112518_75](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/005e7118-2dd3-4729-a61e-362b5514e7fe)

![shot_20230929_112527_76](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/608317d2-69fe-4754-af00-898cd11eb966)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Unit can now get stuck behind rock at the top. Once it sits like this it cannot be moved out again.

![shot_20231001_161426_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f3c0b2d7-6514-4090-ba90-dd7a4d1773b1)

The impassable rock at the center of the valley is irritating. It is sitting relatively low and units can shoot over it, but cannot move over. I suggest making it passable, and sink the rock sufficiently low into the terrain if necessary.

![shot_20231001_161551_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4198b424-a83b-48f5-856e-8717a86d6ada)
