### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Units can move through GLA ornament, but not build over it

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#346]
## Observed behaviour

Units can move through GLA ornament, but not build over it.

## Expected behavior

Units can not move through GLA ornament or can build over it.

## Screenshots

![shot_20230929_112558_77](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4ce315bb-1f8b-4d1a-9cfa-8f056c5495cd)

![shot_20230929_112606_78](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4ef4ea48-eb6f-4503-b196-8815588f3202)

**Comment by NoMerciBKK** [comment]
yes you need to destroy it first to build there it got a hp bar

**Comment by xezon** [comment]
As designed?

**Comment by NoMerciBKK** [comment]
yes
