### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Many rocks are floating above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#347]
## Observed behaviour

Many rocks are floating above terrain.

## Expected behavior

Rocks sit on terrain.

## Screenshots

![shot_20230929_112816_80](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1054fb55-8a8a-4764-bcc8-8b5c04cc9ca4)

![shot_20230929_112839_81](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1584bb7b-4a55-4f00-843d-4bc4f2e3b778)

![shot_20230929_112846_82](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b9afc4d6-66c8-41ad-8d60-9985ded71e3f)

**Comment by NoMerciBKK** [comment]
sadly those are not tiltable by WB

**Comment by Jundiyy** [comment]
Have you tried lowering the rocks? They'd go into the mountain and only psrt of them would stick out, which would look fine imo, since mountains do have random rocks sticking out. Lots of maps already do this.

**Comment by NoMerciBKK** [comment]
well yes ofc i did this with the bigger rocks but those smal flat road rocks you cant lower on those slopes, you just wont see any of them i d need to have the option to tilt them. So not only the option to rotate arround Z also to X and Y

**Comment by DoMiNaToRuk2** [comment]
In this instance I agree with xezon, rocks should not be floating, they can be lowered or moved into the mountain so that only some are showing and do not look odd. If it cannot be fixed then I would rather the rocks get removed. However, I think it can be fixed.

**Comment by Jundiyy** [comment]
Has this been fixed? I downloaded the map and I don't see the 'float'.

**Comment by NoMerciBKK** [comment]
nope i didnt fixed it

**Comment by xezon** [comment]
Perhaps I closed by mistake. I can recheck.

**Comment by NoMerciBKK** [comment]
@xezon is as designed

**Comment by ImTimK** [comment]
Doesn't look very good tbh

**Comment by DoMiNaToRuk2** [comment]
Uploading v3 of this map now with fixed rocks and terrain height.

**Comment by DoMiNaToRuk2** [comment]
In my opinion so many floating rocks like seen in this map are a blocker. As my edit is rejected, I suggest move map to backlog

**Comment by xezon** [comment]
Promoted to blocker as per Dominator request.

**Comment by NoMerciBKK** [comment]
this is a joke its not noticeable as you play the map (as in the normal gameview ss), all rocks do touch the ground on a certain point (this is how the WB works), its a game engine thing that you cant even place it like i would want to because there is no tilt function in the options. 
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/cf6dec05-ba03-437a-8f52-481f045a2869)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/47de24a2-ed6e-4c30-8c30-7ecb965efbfe)

**Comment by xezon** [comment]
I will look at it again.

**Comment by DoMiNaToRuk2** [comment]
For me, it becomes more annoying now because I know about it. But also you can easily see shadows under many rocks when they should not be there. This is at regular angle. Some players do use alternative angles and anyone should be able to take a good screenshot from any angle in my view and it still look good. I would just remove the rocks as players do not care and less objects probably means a few more FPS

![shot_20231007_121227_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/91014132/33d04b42-c491-4bbc-9b08-9dc42ff47c55)
![shot_20231007_121351_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/91014132/89ae39b2-d00e-40de-b1fc-59cd2ade8b92)
![shot_20231007_121403_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/91014132/77f09feb-b902-459f-92ff-ecc0c7e06d64)

**Comment by DoMiNaToRuk2** [comment]
NoMerci, whats your latest view on this?

Do you wanna fix / remove the rocks, otherwise I suggest not to become RANKED. Without RANKED status, it wont get played so much. I even did the work and removed these rocks for you but you rejected it.

**Comment by NoMerciBKK** [comment]
i m waiting for xezons feedback

**Comment by NoMerciBKK** [comment]
> i m waiting for xezons response

**Comment by NoMerciBKK** [comment]
> Xezon is taking 1 month break from the project.
> 
> It's likely he will come back and say it should be fixed. Why not just fix it?
> 
> So many people delaying this crappy project it's a joke

xezon do have the newest version since 1.10.23 so i ll wait to his response

**Comment by NoMerciBKK** [comment]
@xezon is this no fixed and can be closed?

**Comment by xezon** [comment]
Did you move the rocks closer to terrain? If not, then this issue should be still valid.

With default camera pitch, this issue is mostly obvious by the displaced shadows under the rocks.

**Comment by NoMerciBKK** [comment]
in the newest version those are moved, for me its totaly fine cause you d never see it in a live game.

**Comment by xezon** [comment]
Unclear to me what has changed. Rocks still float above terrain everywhere. The problem is these flat stones are not really fit to be placed on slopes. It would probably work better with high rocks that can be pushed into slopes generously.

**Comment by xezon** [comment]
I do not think it should be a blocker either. You can negotiate with Dominator.

But I do think it would be nice to fix. The flat rocks do not even look good, despite floating.

**Comment by DoMiNaToRuk2** [comment]
I think it's mega unprofessional to have so many floating rocks, especially when I already spent 30 mins fixing and removing them all for you. You'd rather revert my efforts and make the map look bad. Some of the rocks can be seen from normal camera view as I showed before

**Comment by NoMerciBKK** [comment]
> I think it's mega unprofessional to have so many floating rocks, especially when I already spent 30 mins fixing and removing them all for you. You'd rather revert my efforts and make the map look bad. Some of the rocks can be seen from normal camera view as I showed before

you did some fixes on an old version but nvm

**Comment by NoMerciBKK** [comment]
> I do not think it should be a blocker either. You can negotiate with Dominator.
> 
> But I do think it would be nice to fix. The flat rocks do not even look good, despite floating.

well thats a taste thing I do like them you dont thats a art thingy

**Comment by xezon** [comment]
Note that previous editions of Ranked Maps had less scrutiny. The first edition had no checks. I try to be fair in judgement for all new maps.

I can see that fixing the rocks is difficult, because there are so many of them.

**Comment by xezon** [comment]
Demoted from blocker, because rocks sit on impassable terrain and are no detriment to game play areas.

**Comment by xezon** [comment]
There are still floating rocks visible on some cliffs. Bug is no longer a blocker. Polish at will, otherwise can be closed.

**Comment by xezon** [comment]
Polished mostly. Done.
