### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Oil Refinery rotations are not aligned to train tracks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#348]
## Observed behaviour

Oil Refinery rotations are not aligned to train tracks.

## Expected behavior

Oil Refinery rotations are aligned to train tracks.

## Screenshots

![shot_20230929_111235_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4d8c4091-ed54-4ad4-8efe-a0572cbbb0d3)

![shot_20230929_111306_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e118ed71-71f1-407b-ac1b-f3fe23fd0b35)

**Comment by NoMerciBKK** [comment]
as designed
