### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Some trees look odd

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#349]
## Observed behaviour

Some trees look odd. They have a dark shade in them.

## Expected behavior

Trees look natural.

## Screenshots

![shot_20230929_113044_83](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/87f568d8-749a-4a53-be8f-effdc38f4d48)

**Comment by NoMerciBKK** [comment]
as designed dense Maple trees look like this in ZH
