### ISSUE TITLE
[Candidate 3v3 Nocky Mountains ZH v2] Tractor on right side is car bomb

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#350]
## Observed behaviour

Tractor on right side is car bomb. On left side there is no tractor.

## Expected behavior

Tractor is removed.

## Screenshots

![shot_20230929_120719_85](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/51eefe53-0c48-43e7-b312-0f90b18fd626)

![shot_20230929_120748_86](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f44aae1e-c0f2-434d-bf1e-e3a06fd49296)

**Comment by NoMerciBKK** [comment]
fixed its not passible to enter anymore

**Comment by xezon** [comment]
I suggest to remove it or put same tractor on the mirrored field on the other side, because it can still affect gameplay and be a rare hazard to infantry units as is seen here:

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b67a7fd2-aec4-4589-add4-cb4d5adf5b5e

**Comment by NoMerciBKK** [comment]
lol ok
