### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] Tech Buildings have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#352]
## Observed behaviour

Tech Buildings have custom rotations that make their flag less visible.

## Expected behavior

Tech buildings preferably have default rotation or a rotation that makes their flag highly visible.

## Screenshots

![shot_20230929_133114_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/29d6c709-c775-4661-9aee-9a67024ab153)

**Comment by NoMerciBKK** [comment]
should be fixed
