### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] Supply Docks offer varying room for infrastructure

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#353]
## Observed behaviour

Supply Docks offer varying room for infrastructure. Some are better than other.

## Expected behavior

Supply Docks offer about equal room for nearby infrastructure.

## Screenshots

![shot_20230929_132647_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/345257d0-5697-47a9-bd7c-4c7bd99a0a22)

![shot_20230929_132654_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0278321a-d58b-48f7-86db-28820ff22b7c)

![shot_20230929_132707_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9cef132f-3f0a-4dd5-982c-105f4c5e70a9)

![shot_20230929_132716_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c40f293f-a0fa-4597-92a0-1a1a070dd6d8)

![shot_20230929_132722_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/451d58a3-e234-4c97-bb9b-8086f25e47a5)

![shot_20230929_132757_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9e6696c8-ec11-4f82-90fd-06aa2eeeefcc)

![shot_20230929_132847_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/70b46eaa-0c7b-4ee0-afa7-adac33431a94)

![shot_20230929_132916_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/148826c4-a8d7-48df-b601-41f256619f7d)

**Comment by NoMerciBKK** [comment]
fixed
