### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] Some Supply Piles can be driven behind, others not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#354]
## Observed behaviour

Some Supply Piles can be driven behind, others not.

## Expected behavior

Mirrored Supply Piles offer equal space for unit mobility.

## Screenshots

![shot_20230929_131958_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fef882a6-3b9a-4785-9d19-73299fd1097a)

![shot_20230929_132026_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/194c4a1c-2235-4ecc-b5f8-e60de0bb1e9e)

![shot_20230929_132127_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dfd58486-d3df-44f8-b2ed-b427f8b3425f)

**Comment by NoMerciBKK** [comment]
fixed
