### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] One Supply Dock can be moved behind

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#355]
## Observed behaviour

One Supply Dock can be moved behind. Not the others.

## Expected behavior

Mirrored Supply Docks offer equal space for unit mobility.

## Screenshots

![shot_20230929_131643_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7b33621d-a9ec-4405-bcf8-1618d48db072)

![shot_20230929_131652_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/99546d16-c4cd-4725-bb1b-529c224edd22)

**Comment by NoMerciBKK** [comment]
fixed
