### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] Blinking lights around Tech Buildings are not properly aligned

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#357]
## Observed behaviour

Blinking lights around Tech Buildings are not properly aligned.

## Expected behavior

Blinking lights around Tech Buildings are properly aligned to the structure they surround.

## Screenshots

![shot_20230929_131158_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fcc888ca-6895-4e70-adb9-f42c3cccb28a)

![shot_20230929_131204_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e85dd2d8-bfad-4cdc-aea1-3a53eb631394)

![shot_20230929_131345_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/161bbe9b-df47-4371-9097-7546eb2862a1)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Looks good, except for this one:

![shot_20231006_180335_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e0ea4477-c5da-47d1-8edb-eabbecd0b0de)

**Comment by NoMerciBKK** [comment]
> Looks good, except for this one:
> 
> ![shot_20231006_180335_2](https://user-images.githubusercontent.com/4720891/273269535-e0ea4477-c5da-47d1-8edb-eabbecd0b0de.jpg)

this is intended we wanna make the money more visible

**Comment by xezon** [comment]
The blinking lights around this structure are not properly aligned. But they are around the other Repair Pad.

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Is still not fixed with latest map I received.
