### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] AI does not capture Oil Derricks in home base

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#358]
## Observed behaviour

AI does not capture Oil Derricks in home base. But they will capture Tech Buildings elsewhere.

## Expected behavior

AI will capture all buildings.

## Screenshots

![shot_20230929_140756_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/51615160-cb8c-4731-82aa-f934eae3a74e)

![shot_20230929_140758_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1915968a-af36-4611-a5e4-b3ad01c9960b)

![shot_20230929_140801_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f44dca70-a266-416a-a1a0-3b61f196d20c)

![shot_20230929_140813_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c9c3ef7e-3e22-4b6e-bd06-09de6307b9af)

**Comment by NoMerciBKK** [comment]
tbh i dont know where the problem is maybe someone could help us out? otherwise "as intended"

**Comment by xezon** [comment]
Adriane:
> Vanilla bug, the Devs scripted the AI to cap things only on "combat zone" before going to the last uncaptured building which is unlikely to happen

**Comment by NoMerciBKK** [comment]
as designed

**Comment by TimberOwl** [comment]
u cant fix this problem due to the 2 trigger areas cant collide together if they do they will cause more problems then oil capture
