### ISSUE TITLE
[Candidate 4v4 Dominion ZH v1] Map center is loaded with animal sounds

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#359]
## Observed behaviour

Map center is loaded with animal sounds. Frogs, Owls, Dogs, Birds, Chickens and some kind of cricket.

## Expected behavior

Ambient sound is less busy. Crickets sound strange.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/18dfecc2-b099-4837-897c-1664be5bbec9

**Comment by NoMerciBKK** [comment]
yeah but this is only one single audio from WB

**Comment by NoMerciBKK** [comment]
as designed
