### ISSUE TITLE
[Candidate 1v1 Dammed Cottages ZH v1] Map border at the bottom is very tight at start

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#364]
## Observed behaviour

Map border at the bottom is very tight at start. The Oil Derrick is hardly visible. Player needs to use the zoom trick to extend the viewable area.

## Expected behavior

Map border is not as tight. Player can see important infrastructure without tricks.

## Screenshots

Dozer builds a Patriot. Difficult to see.

![shot_20230930_091008_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1ea8109c-713a-424f-a595-34280c6ad4be)

Oil Derrick. Difficult to see.

![shot_20230930_083510_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6fbd1b25-f84a-4e37-9aa8-20eb09f57d03)

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Is better, but still tight. Is it possible to expand camera border? The Radar also shows a gap between border and view cone.

![shot_20231007_083132_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/93872b9f-3e87-495c-bdf0-6c718bc5e3b6)

**Comment by TimberOwl** [comment]
i know but border tool is a really badly designed tool it will cause more issues and balance problems as well

**Comment by TimberOwl** [comment]
but that part u cant see is impassible terrain
