### ISSUE TITLE
[Candidate 1v1 Dammed Cottages ZH v1] Bottom Oil Derrick has unexpected rotation

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#366]
## Observed behaviour

Bottom Oil Derrick has unexpected rotation. It is not mirrored.

## Expected behavior

Oil Derrick is rotated by 180 degrees, like the other Oil Derricks on the other side of the map.

## Screenshots

![shot_20230930_082923_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/317135a9-523e-4a9b-91af-36133ec13f61)

**Comment by DoMiNaToRuk2** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/91014132/881d8c76-c325-4e57-9da3-ee4ca56f5d3b)

TimberOwl is telling me all the issues on this map got fixed and apparently you have latest version. Please check all points for this map and close down the issues if resolved.

**Comment by xezon** [comment]
All issues that are not closed are not fixed, unless I made a mistake upon review.
