### ISSUE TITLE
[Candidate 1v1 Dammed Cottages ZH v1] Bottom right path ways appear to have more room than top right ones

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#368]
## Observed behaviour

Bottom right path ways appear to have more room than top right ones.

## Expected behavior

Mirrored terrain offers about equal space for unit mobility and building.

## Screenshots

Path ways are wide.

![shot_20230930_083714_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/200f11f9-82e7-4a91-9c87-90388ad7c682)

Path ways look narrower.

![shot_20230930_083732_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1bca6ba3-c45b-49a8-ad1a-c3eeed0224d4)

**Comment by TimberOwl** [comment]
fixed i will send u the fixed version via discord

**Comment by xezon** [comment]
Space looks larger now. The repaint around the mountain left an artifact. Perhaps this can be polished.

![shot_20231007_084944_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c7b6cd8f-eb38-4fb2-b1ba-b130a851e44d)

**Comment by TimberOwl** [comment]
thats actually one of the grass texture i use
some textures do look like that

**Comment by TimberOwl** [comment]
also i used ruler to check the size of those 2 
enterances

**Comment by xezon** [comment]
The image shows that there is a seam in the painting.
