### ISSUE TITLE
[Candidate 1v1 Dammed Cottages ZH v1] After dam break, water particles keep pouring in but water level no longer rises

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#370]
## Observed behaviour

After dam break, water particles keep pouring in but water level no longer rises.

## Expected behavior

There are no such particles and sound effects of pouring water after the flooding is completed.

## Screenshots

![shot_20230930_092957_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/225093ac-9831-4024-b8d8-13603fd1f72f)

**Comment by TimberOwl** [comment]
its beause the water is pourin out there also its included in dam(object itself) so it cant be fixed
