### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Infantry cannot enter bunker at the top right

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#372]
## Observed behaviour

Infantry cannot enter bunker at the top right.

## Expected behavior

Infantry can enter bunker at the top right.

## Screenshots

![shot_20231001_093758_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a77585da-a486-4b08-9658-a9c6c10e07ad)

**Comment by NoMerciBKK** [comment]
fixed
