### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Supply Piles on left side cannot be driven around, but on right side can

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#373]
## Observed behaviour

Supply Piles on left side cannot be driven around, but on right side can.

## Expected behavior

Mirrored Supply Piles offer equal space for unit mobility.

## Screenshots

![shot_20231001_095249_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9de7e78b-5f91-4f89-a370-67b26ab4105c)

![shot_20231001_095305_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0c2011db-92ac-4130-a4f6-eb7391697da5)

**Comment by NoMerciBKK** [comment]
fixed 
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/99136ddc-8e86-4017-848e-e69b279c1585)
