### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Town house next to top Oil Derrick has 10 slots and missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#374]
## Observed behaviour

The town house next to the top Oil Derrick has 10 slots and missing fire ports. The town house next to the bottom Oil Derrick has 8 slots and no missing fire ports.

## Expected behavior

The same Town house with identical slot count and functional fire ports is placed near both Oil Derricks.

## Screenshots

Most rocket soldiers shoot from 0,0,0. It has 10 slots.

![shot_20231001_100126_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1f37f8c3-12c0-4196-89a4-5711a6ff06e1)

8 slots. Good fire ports.

![shot_20231001_100029_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aa8b6b72-883c-4931-99a3-65d832a17e23)

**Comment by NoMerciBKK** [comment]
as wished fixed 

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/67fa553b-a210-4a28-bf7b-2e1a3fa7d3fa)
