### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Rocket men inside bunker at top right will damage bunker when shooting onto nearby Oil Derrick.

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#375]
## Observed behaviour

Rocket men inside bunker at top right will damage bunker when shooting onto nearby Oil Derrick.

## Expected behavior

Rocket men inside bunker will hit the Oil Derrick and other targets from inside the bunker.

## Screenshots

![shot_20231001_130720_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3059ebaa-54d2-4c3f-a538-a26a3e041ac0)

**Comment by xezon** [comment]
Bunkers need to be sufficiently elevated.

**Comment by NoMerciBKK** [comment]
fixed
