### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Large building near crane is invisible when damaged and garrisoned and easily damages itself

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#378]
## Observed behaviour

Large building near crane is invisible when damaged and garrisoned and is easily damaged when rocket soldier shoot out of it.

## Expected behavior

Buildings used in Ranked Maps work well. No bugs.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3e4bfff5-5a10-4b78-87ec-5deaa110dcfd

**Comment by xezon** [comment]
The new building is better. But not optimal either. It has a relatively large area where it can be damaged, which can result in its occupants killing it. The building in the North also party covers the flag of the Repair Bay.

![shot_20231008_174934_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5410ba18-949c-403e-9b77-81f1ce909300)

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/389f7b1c-79f9-4c4d-aa10-f5dd28420715

Also the other big building there disappears when damaged but is still intact.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/da2bfcf9-1f04-4d9f-87d9-8f4822ad2143

**Comment by DoMiNaToRuk2** [comment]
[Arctic Arena v8.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/13064382/Arctic.Arena.v8.zip)

All the buildings now changed to good and working ones. Also fixed rotations on tech buildings. Please close all the issues for this map if its now good.
