### ISSUE TITLE
[Candidate 1v1 Arctic Arena ZH v5] Supply Dock at the top cannot be moved around, but Supply Dock at the bottom can

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#379]
## Observed behaviour

Supply Dock at the top cannot be moved around, but Supply Dock at the bottom can.

## Expected behavior

Mirrored Supply Docks offer about equal opportunity for unit mobility and building.

## Screenshots

![shot_20231007_103514_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e0d90e82-855c-422e-835b-ce1a7b40a995)

![shot_20231007_103525_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/00bd61d9-7fd9-44a2-ba5b-31be51d1cfdd)

**Comment by DoMiNaToRuk2** [comment]
[Arctic Arena v7.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/12837571/Arctic.Arena.v7.zip)

Map fixed now, buildings in corner replaced with good building, supplies fixed.
