### ISSUE TITLE
[Candidate 1v1 Arizona Airfield ZH v1] Units can shoot through shipping containers

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#380]
## Observed behaviour

Units can shoot through shipping containers.

## Expected behavior

Units can not shoot through shipping containers.

## Screenshots

![shot_20231008_170456_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ab7bffa0-0467-42c2-b9f8-d0abc4cb55ee)

**Comment by DoMiNaToRuk2** [comment]
Won't be fixed as this is game engine problem and we are not excluding all shipping containers from all maps. Suggest to review it in game patch

**Comment by xezon** [comment]
Not good map design but acceptable for Ranked Map.
