### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] One Supply Pile position is not properly mirrored

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#381]
## Observed behaviour

One Supply Pile position is not properly mirrored.

## Expected behavior

All Supply Pile positions are properly mirrored.

## Screenshots

![alteracmoney](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5274d22e-d2ba-47a7-b2c0-21b14951bac8)

**Comment by TimberOwl** [comment]
i did that cause otherwise u wont be able to see the supply but the length between players are balanced

**Comment by xezon** [comment]
As designed
