### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] Some Supply Piles have 2 lights, others 4 lights

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#382]
## Observed behaviour

Some Supply Piles have 2 lights, others 4 lights. There appears to be no system.

## Expected behavior

Supply Lines have consistent amount of lights.

### 4

![shot_20231010_180841_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b2d27f7e-023e-47cf-a084-128598b4adf0)

### 4

![shot_20231010_180917_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7e3afa04-53b4-4231-9bb4-efb7216c9e78)

### 4

![shot_20231010_180955_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e0b5c708-1536-427c-bb13-57b170027065)

### 2

![shot_20231010_181036_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/77369d7b-2869-4ac3-ad0d-dc4a666f1248)

### 2

![shot_20231010_181043_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c37f6bab-571d-4d70-bab8-a7dc2bd1eee8)

**Comment by TimberOwl** [comment]
its cuz i want them to get more attention since they are in middle of the map

**Comment by xezon** [comment]
> its cuz i want them to get more attention since they are in middle of the map

Hmm ok but the one on the first image is not in the middle of the map and has 4 lights, unlike the others.
