### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] One Artillery Platform can be moved around

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#383]
## Observed behaviour

One Artillery Platform can be moved around. Not the others.

## Expected behavior

Mirrored Tech Buildings offer equal room for unit mobility.

## Screenshots

![shot_20231010_180701_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b207bf18-0f85-4386-a285-6cd41f24c5a9)

![shot_20231010_180735_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8363249d-b255-438a-bb63-a1bd23dcac4d)

**Comment by TimberOwl** [comment]
fixed
