### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] Barrels around Oil Derricks are not properly mirrored

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#385]
## Observed behaviour

Barrels around Oil Derricks are not properly mirrored. They are south of the Oil on the left side, and east of the Oil on the right side. This is arguably better for the left team.

## Expected behavior

Barrels are placed on mirrored positions.

## Screenshots

![shot_20231010_180214_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dd38085c-da50-4df6-ab3c-436423497078)

![shot_20231010_180218_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a484ccfd-9886-4e40-8d7c-774504a4187f)

**Comment by TimberOwl** [comment]
i mean i can fix this but how this is a blocker man :D seriously

**Comment by xezon** [comment]
https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e6ad80c2-81f5-4fa6-9217-b969ee3d0028

**Comment by TimberOwl** [comment]
then dont capture from the oil side u know :D

**Comment by xezon** [comment]
Yes, but since the oil barrel positions are not mirrored, one player needs to be more careful than another.

**Comment by Jundiyy** [comment]
Something like this is important, one player may be able to deny the other simple because they have to travel a bit further to be safe.
