### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] Big rocks are located on path ways

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#386]
## Observed behaviour

Big rocks are located on path ways. Units can drive through.

## Expected behavior

Rocks on path ways are low. Big rocks are moved to the side of path ways.

### Bad

![shot_20231010_180001_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/313a1664-7f4f-4f63-a296-ff6b56cee294)

### Good

![shot_20231010_180107_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c21f3597-992a-47d2-b775-998bb9d190bd)

**Comment by TimberOwl** [comment]
fixed
