### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] Map is surrounded by black mountains

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#388]
## Observed behaviour

Map is surrounded by black mountains. The straight elevation can be seen over the mountains.

## Expected behavior

No mountains in fog. Player can see edges of regular terrain.

## Screenshots

![shot_20231010_175305_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a95dc3c2-f417-4b8c-bc8e-d6f8f1de045a)

**Comment by TimberOwl** [comment]
map has a magical theme also i cant fix this

**Comment by xezon** [comment]
Looks better. Good enough?

![shot_20240121_174821_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/07040659-b1de-4118-bd9f-ddf314ffd54b)

**Comment by xezon** [comment]
Looks good now

![shot_20240514_192606_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c6f54130-e59d-497b-be09-42f6a0e00fe0)
