### ISSUE TITLE
[Candidate 2v2 Alterac Pass ZH v1] Units can be dropped on impassable area

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#390]
## Observed behaviour

Units can be dropped on impassable area.

## Expected behavior

Units cannot be dropped on impassable area.

## Screenshots

![shot_20231010_190404_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9ccce5fe-c15a-4cf1-bb1a-67d7e3048911)

**Comment by TimberOwl** [comment]
nice one ill fix and send u a new one via dc again
