### ISSUE TITLE
[Candidate 2v2 Animals of the Generals ZH v1] Space behind Supply Piles in main bases is very different

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#395]
## Observed behaviour

Space behind Supply Piles in main bases is very different.

## Expected behavior

Space behind Supply Piles in main bases is about the same.

## Screenshots

![shot_20231010_200212_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/11b6de1a-70bd-4a47-964a-6563ee2c92d1)

![shot_20231010_200223_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/44a59c90-976a-4c4e-ac1f-be5ee274e78b)

![shot_20231010_200422_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6445e6f3-8625-4d8d-95e3-10fe62446dc0)

![shot_20231010_200428_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a8b53a34-01d6-476b-b823-ff159907119e)

![shot_20231010_200540_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c1397711-31f7-4c8d-8679-eeb8a1d95703)

![shot_20231010_200551_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4c4c8abc-016a-4af4-8d6a-dff6acd867ac)

**Comment by TimberOwl** [comment]
let me measure the distance betwee player spawns then ill do something about it
