### ISSUE TITLE
[Candidate 2v2 Animals of the Generals ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#397]
## Observed behaviour

Audio emitters have no easing. Sounds clips in and out unpleasantly.

## Expected behavior

Sound is setup with easing. Scrolling over the map gives nice audio transitions.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/08708dcd-8034-41b4-8a34-a0996d4ffb34

**Comment by TimberOwl** [comment]
all problems fixed all send you via dc again
