### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Audio is clipping when scrolling over map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#398]
## Observed behaviour

Audio is clipping when scrolling over map. Comes from wind noises.

## Expected behavior

Audio transitions smoothly when scrolling over map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/121fa407-9495-439b-b752-cc8cde9c690a

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Wind is now barely visible.
