### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Oil Derricks at top right have unexpected orientation

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#399]
## Observed behaviour

Oil Derricks at top right have unexpected orientation. The flag is not forward facing, unlike the other Oil Derricks in other 3 corners.

## Expected behavior

Oil Derricks are rotated 180 to achieve symmetric setup.

## Screenshots

![shot_20231012_164912_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5a6ab158-ee75-4a1e-bd15-ab9cb90f2c28)

**Comment by TimberOwl** [comment]
fixed
