### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Rocks are visible in black map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#400]
## Observed behaviour

Rocks are visible in black map border.

## Expected behavior

Rocks are not placed in black map border.

## Screenshots

![shot_20231012_165522_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/30a3530e-71db-4239-ba4b-44f323f51fe0)

**Comment by TimberOwl** [comment]
fixed
