### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Silos at bottom right are sunk in concrete terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#401]
## Observed behaviour

Silos at bottom right are sunk in concrete terrain.

## Expected behavior

Silos are not sunk in terrain.

## Screenshots

![shot_20231011_201522_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4b1e451d-249a-4b9d-8b2f-3f4bd19a6c49)

**Comment by TimberOwl** [comment]
thats a design thing made by tklyo i wont change it think them like they are under ground

**Comment by xezon** [comment]
The Silos in the 3 other corners are not sunk in terrain.

**Comment by TimberOwl** [comment]
yes sunken ones are tklyo s design the other are a different facility so they are not sunken its just different ideas and designs

**Comment by xezon** [comment]
It looks bugged.

**Comment by TimberOwl** [comment]
sorry but i wont change it its a disrespect to tklyos design and i dont want to upset him

**Comment by xezon** [comment]
It is not disrespect to fix things. That whole bottom right section looks bumpy with its bumpy concrete terrain and floating paintings.

**Comment by toirehantaa** [comment]
just mark as design by choice and let it be, no one except for mappers will care at all

**Comment by xezon** [comment]
Yes we can close. It's no blocker, so it will not block ranked map status. Just be aware that many small issues can possibly block auto download for a map, as we will just select the very best maps for auto download.
