### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Road to bottom right Oil Depot does not blend with terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#405]
## Observed behaviour

Road to bottom right Oil Depot does not blend with terrain. Other roads do not blend well either, but it is less noticeable.

## Expected behavior

Road end blends well on terrain.

## Screenshots

![shot_20231012_170455_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f97ea1e9-5c92-4ec5-8b32-2c98fa50f6c4)

![shot_20231012_170540_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/64e01032-28ae-4a25-98d7-ac358e91c625)

**Comment by TimberOwl** [comment]
fixed
