### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Mud road does not fit into sandy desert

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#407]
## Observed behaviour

Mud road does not fit into sandy desert. The brighter sand road fits much better.

## Expected behavior

Road fits terrain.

## Screenshots

![shot_20231012_172006_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/44f29863-cb6f-4f36-98e9-d17a978d8280)

![shot_20231012_172018_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/167b7292-d317-40ba-832d-70d8a03df061)

**Comment by TimberOwl** [comment]
i would like the keep it that way since its natural to have 2 different road color

**Comment by xezon** [comment]
As designed.
