### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Some rocks float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#408]
## Observed behaviour

Some rocks float above terrain.

## Expected behavior

Rocks sit tight on terrain.

## Screenshots

![shot_20231012_172243_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8bebc576-08ca-4f2f-a194-e3f516d1aacc)

![shot_20231012_172302_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9c6657aa-3d6e-47c4-9339-7081e90ba477)

![shot_20231012_172311_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d7f85be6-7cc7-4d6d-b3f9-96bc55f5d686)

![shot_20231012_172410_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/885ef064-6c9f-473b-aa07-3dc4b742a5f3)

**Comment by TimberOwl** [comment]
thx fixed

**Comment by TimberOwl** [comment]
all fixed all send it to u via discord

**Comment by xezon** [comment]
There are still some left.

![shot_20231014_172135_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/93483bc7-e8d6-479e-9694-2471f6e18ed1)

![shot_20231014_172150_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/71b1454b-727d-422e-b0f5-3f79f22c4a3d)

![shot_20231014_172226_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/95fae1b7-e800-4a2c-ab7b-957e159ab6ec)

![shot_20231014_172240_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f7ae7bea-4c1a-42b1-adc2-ad868d4cc07c)

**Comment by xezon** [comment]
Still one left

![shot_20231116_211407_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6e819c9a-3a93-41f7-ac8a-2955311b8fa5)

**Comment by TimberOwl** [comment]
i ll send again then

**Comment by xezon** [comment]
Looks unchanged to me.
