### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Some important structures disappear in fog

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#410]
## Observed behaviour

Some important structures disappear in fog.

## Expected behavior

Important map structures do not disappear in fog.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/75d94229-8358-44e6-87c6-001c2487e998

**Comment by DoMiNaToRuk2** [comment]
Xezon are you flagging game engine / EA model issues to map makers again as blockers?

What is the suggested solution to this? Is it even possible to fix or are you literally wasting eveyone's time again?

**Comment by NoMerciBKK** [comment]
this is more like a system/hardware sided thing, all of them are showing up in my game.

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/c41ae4e9-7bde-4fc1-bcc7-d26d4d346178)

**Comment by DoMiNaToRuk2** [comment]
This seems hardware issue and it will not be changed as too much time required to change whole theme of the map. works fine on my PC

**Comment by AdrianeYves** [comment]
chill out ma mates -- thats a bug on ma code :)

**Comment by TimberOwl** [comment]
adriane 
what is that  profile pic !!!!!!!
