### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Many rocks float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#411]
## Observed behaviour

Many rocks float above terrain.

## Expected behavior

Rocks sit tight on ground.

## Screenshots

![shot_20231014_174855_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7ab46491-ac4a-4cf8-9730-c830d89b6732)

![shot_20231014_174906_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4c46e3c1-13cf-40f4-a5bd-2c9917aad061)

![shot_20231014_174931_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d30eeb38-c2de-4710-ae85-ec741a084fb7)

![shot_20231014_175009_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d0173917-c14f-462c-b136-5eb1b9635c3e)

![shot_20231014_175024_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7d39652e-26bf-4f77-a2f7-b6dfdce64bd3)

![shot_20231014_175041_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4afeb8ae-2f89-4a3e-9c74-3317acdbd0c0)

![shot_20231014_175121_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/66c66af8-1c95-47ab-a624-831f3eb544a7)

**Comment by DoMiNaToRuk2** [comment]
All these example rocks have been fixed, plus lots of ruins that block paths also removed to enable more free flow lanes to enemy base

**Comment by xezon** [comment]
Looks better in new version. There are still a couple floating rocks. Perhaps can do another polishing pass on them.

## 1

![shot_20231117_194935_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8936691e-2368-4f97-9d2d-7a96c5f7fb67)

## 2

![shot_20231117_195019_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1c174c65-bfbb-4417-9d26-6e408b277c16)

## 3

![shot_20231117_195030_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6abd0c0d-c441-4532-945c-b0141c087854)

## 4

![shot_20231117_195120_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/905ea21c-721c-4af5-904a-66f4cf250e61)

## 5

![shot_20231117_195137_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/50c9c8c7-834e-46b8-b73b-ec4f32aecd0d)

## 6

![shot_20231117_195220_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c25f72d8-7c44-4ab4-9028-87fca2388105)

**Comment by DoMiNaToRuk2** [comment]
fixed and new version sent on discord.

**Comment by DoMiNaToRuk2** [comment]
Sending v4 on discord now. I cannot attach zip because winzip trial expired. I only have winRAR.

This will be the final version, i fixed about 20-30 rocks all around the map. If there are more, its taking too long so won't be fixed. Players haven't noticed even on the oldest versioin current 20k tournament,

**Comment by xezon** [comment]
Looks good to me. I would remove or lower these rocks though, because they are located in the middle of the pathway and at a glance give the impression of blockage.

![shot_20231206_200726_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eb906e08-8763-47d0-b907-a6244a737a1e)

To illustrate the point, here is a spot where rocks are less and lower, but unit cannot move over:

![shot_20231206_201145_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4fc82e39-d92f-449f-8981-b45a4023ffb6)

There are some other spots where rocks are high on passable terrain. Perhaps can be lowered a bit so they do not look like passage blockers.

**Comment by DoMiNaToRuk2** [comment]
those 2 rock screenshots fixed, sent v5 on discord

**Comment by xezon** [comment]
Ok the first removal is good.

The second one is not good, because now there is a terrain patch that looks passable but it is not:

![shot_20231206_203901_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1f5a7a07-9a69-4318-a930-62f2d19e7c94)

I suggest to make it either passable or put big rock there.

Note though: I was able to pull USA Dozer through there. So impassable area seems to be very narrow. Perhaps needs to be bigger?

Here is video:

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e5c54bf4-1162-4628-93fe-52467c71e2ef

**Comment by DoMiNaToRuk2** [comment]
fixed by increasing passable area. Will send v5 on discord again, replace old

**Comment by xezon** [comment]
This gap still acts strange. New video:

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/101a33a3-fe37-4659-94ed-f921db711c58

**Comment by DoMiNaToRuk2** [comment]
fixed named v5 still, sent on discord.
