### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] USA Dozer can drive behind one of the Oil Derricks and cannot be attacked

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#412]
## Observed behaviour

USA Dozer can drive behind one of the Oil Derricks and cannot be attacked. This only works on this Oil Derrick.

## Expected behavior

Dozer cannot drive behind Oil Derrick and become unattackable by ground units.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2b74b831-2353-4765-b86e-7b0bb2f243b8

**Comment by DoMiNaToRuk2** [comment]
Fixed in new version by moving oil slightly left and adding some new impassable terrain
