### ISSUE TITLE
[Candidate 1v1 AKAs Magic ZH v1] Small glitch in terrain tile

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#413]
## Observed behaviour

Small glitch in terrain tile. Is z clipping.

## Expected behavior

Terrain tiles do not z clip.

## Screenshots

![shot_20231014_180752_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/206efcf7-a293-4dd3-9515-b6f03352797e)

**Comment by xezon** [comment]
Unclear to me how this is even possible on terrain.

**Comment by Jundiyy** [comment]
Happens when blending, sometimes it's very easy to fix and sometimes it's tricky.

**Comment by NoMerciBKK** [comment]
there are loads of those on nearly every map, most likely you wont see them ingame, cause you do not look for those.

**Comment by DoMiNaToRuk2** [comment]
fixed in new version, hidden with another object as fixing with new tiles just leads to more issues.
