### ISSUE TITLE
[Candidate 1v1 Dry River ZH v4] Oil Derrick at the top can be moved around, Oil Derrick at the bottom can not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#416]
## Observed behaviour

Oil Derrick at the top can be moved around, mirrored Oil Derrick at the bottom can not. It also looks like the plateau at the top has much more room somehow.

## Expected behavior

Mirrored Tech Buildings offer equal movement opportunities.

## Screenshots

![shot_20231117_183347_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0beefde0-2952-43a4-af6b-31fcac384450)

![shot_20231117_183402_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/837ee22c-5282-4caa-8a4e-aeb6482d91fb)

**Comment by NoMerciBKK** [comment]
fixed
