### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Audio is crackling when scrolling over the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#417]
## Observed behaviour

Audio is crackling when scrolling over the map.

## Expected behavior

Audio has smoother transitions and is pleasant to listen to when scrolling over the map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ee3a2bf8-775b-47a7-b77c-0df0a3cad86c

**Comment by TimberOwl** [comment]
fixed
