### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Two AI spots are not building

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#418]
## Observed behaviour

Two AI spots are not building.

## Expected behavior

All AI spots are building and attacking.

## Screenshots

![shot_20231118_095222_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/87299691-1569-4774-ae4d-92e735919589)

![shot_20231118_095354_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f205b875-cea5-431c-b6c0-0f19a62e6f63)

**Comment by TimberOwl** [comment]
hmm this one need a bit investigate ill send the map when i fix this

**Comment by TimberOwl** [comment]
i tried to fix but its a bug i think 
only usa is not building it ai movement is hard coded therefore i cant fix it

**Comment by xezon** [comment]
Anyone idea how to fix it?

**Comment by xezon** [comment]
Unable to fix. Perhaps needs fixing in scb scripts.
