### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Unit can move behind Oil Refinery at the top, but not at the bottom

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#421]
## Observed behaviour

Unit can move behind Oil Refinery at the top, but not at the bottom.

## Expected behavior

Mirrored Tech Buildings offer equal unit mobility opportunities.

## Screenshots

![shot_20231118_090606_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3fb3a5a2-ecd0-4eb4-9919-341a72c23433)

![shot_20231118_090614_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/48cd5e60-d210-4684-ac20-842468bf430a)

**Comment by TimberOwl** [comment]
fixed
