### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Units can move around one Oil Derrick at the top, but not at the bottom of the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#422]
## Observed behavior

Units can move around one Oil Derrick at the top, but not at the bottom of the map.

## Expected behavior

Mirrored Tech Builds offer equal unit mobility opportunities.

## Screenshots

![shot_20231118_090514_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1ff2fbce-5369-46ec-a547-e324987d8c24)

![shot_20231118_090528_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/edea0b16-ca0e-4c21-8e02-91205c25cc56)

**Comment by TimberOwl** [comment]
fixed
