### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Units can move around Oil Derricks at the top left, but not around Oil Derricks at the bottom right

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#423]
## Observed behavior

Units can move around Oil Derricks at the top left, but not around Oil Derricks at the bottom right

## Expected behavior

Mirrored Tech Buildings offer equal unit mobility opportunities.

## Screenshots

![shot_20231118_090424_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/12037b9e-a231-499d-a63f-42f91267ef61)

![shot_20231118_100942_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6d5b5c71-000f-4126-9916-58ecebf6621f)

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Rotation was fixed, but spacing issue is not fixed.

**Comment by xezon** [comment]
Spacing is fixed.
