### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] A few trees clip through structures

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#424]
## Observed behavior

A few trees clip through structures.

## Expected behavior

No foliage clips through structures.

### 1

![shot_20231118_090324_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aa20de83-a439-4b32-aa83-d1869d1014f6)

### 2

![shot_20231118_090326_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9f42c79a-fd2e-4b57-841a-24ea488630be)

### 3

![shot_20231118_101250_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e838e6de-e9ab-4903-8728-900b459929e6)

### 4

![shot_20231118_101300_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7a117205-9145-46cf-a520-7e4b60a57be1)

### 5

![shot_20231118_101329_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7d45b507-fdd4-4eaf-9ea1-8f8692b913ce)

### 6

![shot_20231118_085708_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f016181d-7c75-45a0-9864-9587d8764cb9)

**Comment by TimberOwl** [comment]
u know on the old walls where plants grow on them thats what i was aiming for

**Comment by xezon** [comment]
Ah. But the trees have sway movement :-)

**Comment by xezon** [comment]
Images 2 and 6 fixed, the others not.

**Comment by TimberOwl** [comment]
i now but in my country there are literally grown trees inside fort walls like that so its normal for it to sway

**Comment by xezon** [comment]
### 02.07.2024

Trees in images 1, 2, 4, 6 fixed. Others not. Closing.
