### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Many wall structures have immobile flags

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#425]
## Observed behavior

Many wall structures have immobile flags.

## Expected behavior

Wall structures have no flags, unless they can be garrisoned.

## Screenshots

![shot_20231118_090352_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/922d8eaf-79ed-4fd4-bb42-1661e44f2376)

**Comment by xezon** [comment]
I expect this can be fixed by using `HideSubObject` on these w3d files in map.ini

**Comment by TimberOwl** [comment]
do you know how can we do it i asked tanso but he doesnt knows as well

**Comment by xezon** [comment]
In INI there is HideSubObject field:

```
Object AirF_AmericaJetAurora
  Draw = W3DModelDraw ModuleTag_01
    DefaultConditionState
      HideSubObject = BurnerFX03 BurnerFX04
    End
  End
End
```
Perhaps you can override this in map.ini. You would need to find the object name(s), the module tag name and the w3d sub object name(s), which you can inspect with a w3d viewer:

https://github.com/TheSuperHackers/GeneralsTools/tree/main/Tools/w3dview/thyme20230129

**Comment by xezon** [comment]
Not fixed and not planned.
