### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Destructible barrels are inconsistently placed around Oil Derricks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#426]
## Observed behavior

Destructible barrels are inconsistently placed around Oil Derricks.

## Expected behavior

Destructible barrels are consistently placed around mirrored Oil Derricks.

## Screenshots

![shot_20231118_090148_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/84dc31dd-9ea6-4ac2-964c-5ecdfc5aa1c7)

![shot_20231118_090156_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4d6d606d-2b52-4838-ac4c-8389858cbb63)

**Comment by TimberOwl** [comment]
fixed
