### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Rotations of mirrored Oil Derricks are not properly setup

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#427]
## Observed behavior

Rotations of mirrored Oil Derricks are not properly setup.

## Expected behavior

Mirrored Tech Buildings have mirrored rotations or somewhat consistent rotations for a consistent look.

## Screenshots

Sample. I suggest to double check all.

![shot_20231118_090057_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9de85358-640b-481c-b59b-cbd3ef848752)

![shot_20231118_090131_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/73b0749d-1e45-41f7-be87-1c9a6fcf0844)

**Comment by TimberOwl** [comment]
fixed
