### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Wall segments render black near fog transition line

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#429]
## Observed behaviour

Wall segments render black near fog transition line.

## Expected behavior

Wall segments do not render black near fog transition line.

## Screenshots

![shot_20231118_085910_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/36982e99-b478-4e93-8057-ce034c1edefc)

**Comment by TimberOwl** [comment]
i want to fix but dont know how game bug i think

**Comment by xezon** [comment]
Cannot fix.
