### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Two castles at the bottom obstruct view to large sections of the passable terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#430]
## Observed behaviour

Two castles at the bottom obstruct view to large sections of the passable terrain.

## Expected behavior

Civilian structures do not obstruct much of the view.

## Screenshots

![shot_20231118_085821_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f8449cf9-082a-4015-8eeb-4648055024fa)

![shot_20231118_085838_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/37dba06c-e642-4c5a-9d77-13a9eb4f59a1)

**Comment by TimberOwl** [comment]
u can see the color anyway so i want it to keep it that way

**Comment by xezon** [comment]
As designed.
