### ISSUE TITLE
[Candidate 3v3 Garden of Terror ZH v1] Tech Buildings have custom rotations that make their flags less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#431]
## Observed behavior

Tech Buildings have custom rotations that make their flags less visible.

## Expected behavior

All Tech Buildings have default rotations or custom rotations that make their flag highly visible in default camera rotation.

## Screenshots

![shot_20231118_085759_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e3610cd-c674-4e79-8649-420ec4e7f9f9)

**Comment by TimberOwl** [comment]
done

**Comment by xezon** [comment]
What about the other one on the other side? That one was not adjusted.

![shot_20240323_144057_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3b31d131-5421-4149-a3c3-10efed0f0608)
