### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Rangers can be combat dropped on impassable terrains

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#432]
## Observed behavior

Rangers can be combat dropped on impassable terrains.

## Expected behavior

Rangers cannot be combat dropped on impassable terrains.

## Screenshots

![shot_20231118_124313_72](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c179eac5-66ab-4965-a1c9-ebc316c3020f)

![shot_20231118_124504_75](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c5e0c071-f2f1-46ca-b304-6e150e9bbc75)

![shot_20231118_124653_77](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6d536f72-52d5-4c16-8905-415c1422f98e)

![shot_20231118_124734_78](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/09ebbd9f-09d7-4a78-a47e-9a771a637251)

**Comment by TimberOwl** [comment]
ill check n fix
