### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Terrain painting is not properly aligned to start position

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#436]
## Observed behavior

Terrain painting is not properly aligned to start position.

## Expected behavior

Terrain painting is perfectly aligned to start position.

## Screenshots

![shot_20231118_123914_67](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c4110f72-66a9-49da-823c-953bcac2941c)

**Comment by TimberOwl** [comment]
fixed
