### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] All three AI at top right side do not build

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#437]
## Observed behavior

All three AI at top right side do not build.

## Expected behavior

All AI player can build and attack.

## Screenshots

![shot_20231118_123659_65](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b69b935e-cc91-4a0a-a1c4-f0243e85e33d)

**Comment by TimberOwl** [comment]
fixed
