### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Tech Buildings have custom rotations that make their flags less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#438]
## Observed behavior

Tech Buildings have custom rotations that make their flags less visible.

## Expected behavior

Tech Buildings have default rotations or custom rotations that make their flag highly visible.

## Screenshots

![shot_20231118_123512_63](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e0bf27fd-6b37-42c9-93b9-98feb04a0c9e)

![shot_20231118_122241_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a8e41c59-ba3b-4128-a6d8-ed98ed98e08f)

**Comment by TimberOwl** [comment]
why is this blocker again

**Comment by xezon** [comment]
Because on some structure(s) the flag is partly hidden to default camera.

**Comment by xezon** [comment]
New rotation is better, but not much, but I will reject new edit because of the audio regression.

It would be good if the flags were facing the default camera.

![shot_20240323_150432_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/be539b07-6afa-4aeb-a6bb-32397179c688)

**Comment by xezon** [comment]
Reopening because closed by mistake.

**Comment by xezon** [comment]
Still happens.
