### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Units can get stuck at one location

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#439]
## Observed behavior

Units can get stuck at one location.

## Expected behavior

Units cannot get stuck.

## Screenshots

![shot_20231118_122558_49](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4d678a24-7333-40ad-84cb-bdc890676431)

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/91e95d0d-9f7b-435b-975c-f214b0a68e19

**Comment by TimberOwl** [comment]
fixed
