### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Units can shoot through tall rocks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#440]
## Observed behavior

Units can shoot through tall rocks. Can destroy the Repair Bay through it.

## Expected behavior

Units can not shoot through tall rocks.

## Screenshots

![shot_20231118_122805_51](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bd06b61b-813a-4704-9dda-332b2a1b45dc)

![shot_20231118_122846_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7ba4d1dc-bfd6-4f01-a221-f3399e19f577)

**Comment by xezon** [comment]
I think to fix, try raise the terrain inside the rocks.

**Comment by NoMerciBKK** [comment]
there is no option to make rocks collide, yes you could make the terrain raised inside but you ll see it and it ll look odd + you can still shoot on certain spots through them

**Comment by xezon** [comment]
There should be a way to do this with object flags. Other structures also have collisions.

![shot_20231119_155314_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6b480c33-4de7-44da-8aee-0afea634342a)

**Comment by xezon** [comment]
Is partly fixed. Soldiers have some difficulties shooting through rocks now, but in principle it is still possible at some spots.

![shot_20231203_110052_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eeb2cacd-e6df-4472-8287-4301aad0b48b)

**Comment by xezon** [comment]
It no longer is possible to force fire terrain through the rocks, but it is still possible to attack units and buildings. I suspect the terrain needs to spike higher. Perhaps can create a sharp mountain edge between the rock models?

![shot_20231222_194220_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/316a6a05-7668-4efb-ad6e-9d9d01fb81b0)

**Comment by TimberOwl** [comment]
it looks very bad in the eye tho are u sure about it ?
i can try tho but it might end up the same

**Comment by xezon** [comment]
I have not seen it so I cannot say. It would be best if it looks good and functions good.

**Comment by xezon** [comment]
Situation has improved. And the new trees around the rocks look pretty.

But it is still possible to shoot through rocks at some locations.

![shot_20240514_184444_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0147417c-8722-4b17-a874-5076058b5ee1)

**Comment by xezon** [comment]
## 13/06/2024

Gameplay wise looks good now. Soldiers no longer shoot through rocks. But many rocks are floating above terrain. I suggest lowering a bit until the big gaps are hidden and fill the rest with bushes if so required.

![shot_20240613_182547_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f41cefa5-5499-4b6b-a5e4-24ae3300fb20)

![shot_20240613_182608_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/530b1f73-8eb9-4509-9bf5-3efbbf20bc82)

![shot_20240613_182626_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bfa279df-68b5-4f49-b9ae-777431f9e22e)

![shot_20240613_182637_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e2023cf4-bcbf-4f33-b85a-2e0fc510182a)

![shot_20240613_182641_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/71ece5fd-8431-4e8b-be4b-7995575e279d)

![shot_20240613_182646_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/05890d70-0937-4322-a184-f117b8b6b3bb)
