### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Units can drive a bit behind middle Supply Dock on one side, but not the other side

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#441]
## Observed behavior

Units can drive a bit behind middle Supply Dock on one side, but not the other side.

## Expected behavior

Mirrored Supply Docks offer equal unit mobility opportunities.

## Screenshots

![shot_20231118_122406_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0382f7c8-09e1-4a06-87be-69709963303e)

![shot_20231118_122414_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1876526d-f469-468b-808e-b101b9b4df15)

**Comment by TimberOwl** [comment]
wat

**Comment by TimberOwl** [comment]
fixed
