### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Many houses give the impression of being garrisonable, while they are not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#442]
## Observed behavior

Many houses give the impression of being garrisonable, while they are not. The no-entry decals help to communicate this, but are not sufficient to avoid confusion.

## Expected behavior

Unusable houses are clearly noticeable by the design of the map, for example by sitting on elevated terrain or by being surrounded by walls, water or other obvious obstacles.

## Screenshots

![shot_20231118_122325_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f8c371c6-25e0-41d3-bec6-b3b0d5c89e4b)

![shot_20231118_122119_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cc2577d6-298d-4170-9791-6439fcf0ac88)

**Comment by TimberOwl** [comment]
u cannot select them so therefore u will know that u cant enter them

**Comment by TimberOwl** [comment]
for u i put more no entry on them on all of them

**Comment by xezon** [comment]
Duplicate of #443
