### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Terrain patches near map border look passable, but are not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#443]
## Observed behavior

Terrain patches near map border look passable, but are not. There are no-entry signs that help communicate this, but it is not convincing. Physically nothing should prevent a unit to disrespect the virtual border.

## Expected behavior

Terrain patches near map border are passable or secluded in a more convincing way, for example with water, fences or other obvious obstacles.

## Screenshots

![shot_20231118_122057_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9db39594-1a2e-4934-a487-ef5cd95f6e83)

![shot_20231118_122039_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/327bc926-ce38-496f-8749-d86c3840fcce)

**Comment by TimberOwl** [comment]
there is crosswalks also 
and nothing is selectable

**Comment by TimberOwl** [comment]
we both now i cant fix more that this that means makin a different map basicly also this map played by alot of player and they all capable of understanding of that unpassable terrain

**Comment by xezon** [comment]
Yes does not look easy to solve. It is a bad design. Perhaps it should not be a ranked map.

**Comment by xezon** [comment]
TimberOwl disagrees with blocker classification:

> this map is a favorite map for players
> everyone pretty much understands that you can't get in those building and can't pass that back side

**Comment by xezon** [comment]
As designed.
