### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Horse carts are selectable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#444]
## Observed behavior

Horse carts are selectable. This is annoying when trying to click with air units into map corners where a horse cart is located. It would select the horse cart. Also the horse carts can be entered by Terrorists. But Terrorists cannot reach them, so they will just be stuck near impassable terrain.

## Expected behavior

Horse carts are not selectable.

## Screenshots

![shot_20231118_123235_60](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4a42ad40-0b30-40f3-a6b6-c020c84aea6f)

![shot_20231118_123357_62](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9180bfc5-2a0f-4657-8c7c-0db22f742738)

**Comment by TimberOwl** [comment]
lmao i will fix it after the next week i have exams
