### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Some unusable houses still show on radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#445]
## Observed behavior

Some unusable houses still show on radar.

## Expected behavior

All unusable houses do not show on radar.

## Screenshots

![shot_20231118_124131_71](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/46c86a80-cdc2-4c34-b2f6-b6ef5e7c0e72)

![shot_20231118_121542_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dc4ac91d-f200-4967-b137-ebc19dbfef2c)

**Comment by TimberOwl** [comment]
fixed
