### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Destructible barrels around mirrored Oil Derricks in center are not properly placed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#448]
## Observed behavior

Destructible barrels around mirrored Oil Derricks in center are not properly placed.

## Expected behavior

Destructible barrels around mirrored Tech Buildings are properly placed.

## Screenshots

![shot_20231118_123014_56](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/639592a2-9ee6-490b-91fa-cc4c74de6cdc)

![shot_20231118_123026_57](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/366426dc-3efb-4ac1-9b6c-a69754708eb7)

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Is unchanged. On second look, it also looks like the terrain around these Oil Derricks are different. Unclear what a fair barrel setup should look like exactly, because the conditions are not the exact same.

**Comment by xezon** [comment]
Demoted from blocker. Terrain is not mirrored. Not straight forward to make equal conditions.

**Comment by xezon** [comment]
Top oil derrick terrain can be made a bit more passable.

**Comment by TimberOwl** [comment]
tried my best on it

**Comment by TimberOwl** [comment]
are these still on or u havent checked yet

**Comment by xezon** [comment]
I think I did not check. I did not update to the last edit because of the audio regression.
