### ISSUE TITLE
[Candidate 3v3 Cursed Hollows ZH v1] Ambient sounds have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#450]
## Observed behaviour

Ambient sounds have no easing. Scrolling over the map will pop in and out sounds without graceful fades.

## Expected behavior

Ambient sounds ease in and out gracefully.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e1c6b484-395a-4410-9667-351cfea39e70

**Comment by xezon** [comment]
Not sure if fixed. Sounds the same.

**Comment by TimberOwl** [comment]
fixed again

**Comment by xezon** [comment]
Map is quiet now at many places. Is this intended? But sounds by the houses still have no ease in/out. I think new edit is a regression.

**Comment by TimberOwl** [comment]
well i tried best on audio but maybe the audio i used is bugged or something i will take a look on how to fix it since i dont really hear it well it is a bit difficult job for me to fix but no worries ill find something thx again

**Comment by xezon** [comment]
Sound is still not good. No easing. Quiet at many places.

**Comment by xezon** [comment]
Still happens.

**Comment by xezon** [comment]
Ox, farm, people sounds still have no good easing. Closing.
