### ISSUE TITLE
[Candidate 1v1 Rainforest Reservoir ZH v1] Performance drops by around 80% while a dam breaks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#453]
## Observed behavior

Performance drops by around 80% while a dam breaks.

## Expected behavior

Performance does not drop much while a dam breaks.

## Screenshots

![shot_20231119_142554_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/68e62335-a6f6-42e3-b1bd-1b1847288e42)

![shot_20231119_142609_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf28da9c-fed9-4da0-83e3-f0b5478f8609)

**Comment by DoMiNaToRuk2** [comment]
new version was sent on discord a few days ago. We tested 3 people on this map now and no FPS issues.

**Comment by xezon** [comment]
Please test more hardware. On my machine 80% performance drop.

**Comment by cncHD** [comment]
Destroyed both dams
FPS droped from 63 down to 54 for a few seconds and then went back up to 63 again.
Its something you cant rid of without removing the dam.
In my opinion its ok. The frame drop is not gamebreaking and only happens for a few seconds

**Comment by cncHD** [comment]
Windows 10, AMD Ryzen 7 5600G with Radeon Graphics
3.80 GHz
NVIDIA GeForce GTX 1650

**Comment by xezon** [comment]
It perhaps depends on hardware. On my machine drop is significant. Note that other maps also had this drop and it was fixed on all of them except this one.

**Comment by xezon** [comment]
Newgate says this is technically as good as we can make it.

**Comment by xezon** [comment]
Tanso managed to improve it regardless. Performance drop on my machine was reduced from around 60 FPS low to 170 FPS low.
