### ISSUE TITLE
[Candidate 1v1 Hanamura Temple ZH v1] Supply piles near main bases have inconsistent spacing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#459]
## Observed behavior

Supply piles near main bases have inconsistent spacing.

## Expected behavior

Mirrored supply piles offer equal unit mobility opportunities.

## Screenshots

![shot_20231119_154650_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dcc609b1-fcce-4847-b2fe-6abb53f4f6f7)

![shot_20231119_154657_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/92a290fc-b9b3-4ca6-8ce7-a3e12203555c)

**Comment by TimberOwl** [comment]
sure ill fix

**Comment by xezon** [comment]
Is not fixed.
