### ISSUE TITLE
[Candidate 1v1 Hanamura Temple ZH v1] Supply Docks on side lanes have different path ways around them

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#460]
## Observed behavior

Supply Docks on side lanes have different path ways around them.

## Expected behavior

Mirrored Supply Docks on side lanes have equal path ways around them.

## Screenshots

![shot_20231119_154750_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4fe71eee-92d9-41f6-8931-0b1bcf9b322f)

![shot_20231119_154823_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/77e7254a-aa13-41fb-9e68-b0de7c71099d)

**Comment by TimberOwl** [comment]
fixed
