### ISSUE TITLE
[Candidate 1v1 Hanamura Temple ZH v1] Tech Buildings have custom rotations that make their flags difficult to see

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#461]
## Observed behavior

Tech Buildings have custom rotations that make their flags difficult to see.

## Expected behavior

Tech buildings have default rotations or custom rotations that make their flags very visible.

## Screenshots

![shot_20231119_154907_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/73f1c232-158b-47f3-ae55-b750a12dec40)

**Comment by TimberOwl** [comment]
xezon me and tanso have talked about this why is this a blocker again ?

**Comment by xezon** [comment]
Because some Tech Building flags are hidden. Flags need to be visible.

![shot_20231127_222031_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/567e6690-4512-468d-b61b-c9de7b070edd)

**Comment by TimberOwl** [comment]
okay but artillery platforms change color as well and u can also see it who owns then if u move ur cursor

**Comment by TimberOwl** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/147165515/8e7beb25-7a4f-467a-b453-089f02205dc1)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/147165515/a21a167e-838b-4b6b-8ede-9cdc8ee47e32)

**Comment by xezon** [comment]
Yes, but maps need to be Player and Observer friendly. When flags are not as visible, then ownership becomes more difficult to see, which decreases map readability.

This does not just affect players, but also viewers on live streams.

**Comment by xezon** [comment]
Btw I recommend to not upload PNG pictures. They are too large and load slow. Better use JPG instead.

**Comment by TimberOwl** [comment]
viewes can also see the radar which it makes them easier and i dont think i need to say that artillery will attack to others when its captured

**Comment by TimberOwl** [comment]
if i make flag visible this time artillery platform will look bad also it will have to turn back and gets delayed

**Comment by Jundiyy** [comment]
Agree with TimberOwl, Artillery Platform is always visible even without the flag, since the model changes colour. 
And also, regarding the natural state of it, can't have them both facing one way if they are on different ends as they rotate like other defences. So would be unfair.

**Comment by xezon** [comment]
> Agree with TimberOwl, Artillery Platform is always visible even without the flag, since the model changes colour.

Yes, but the flag more than doubles the surface area of the house color. When you look at house color quickly as a player or on a small screen when watching a livestream, it should be preferably to see the house color as large as possible.

![shot_20231216_201639_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f509aed6-a779-4ed5-a5bc-be0a7044a709)

> And also, regarding the natural state of it, can't have them both facing one way if they are on different ends as they rotate like other defences. So would be unfair.

Are you sure about this? The turret rotation radius is 360 degrees. It idle rotates to all directions and on average should spend a similar amount of time in all directions. If I am not mistaken it practically is irrelevant how it is rotated and I think EA explicitly designed it this way.

**Comment by TimberOwl** [comment]
yes but its is better of when it lookin at one direction 
cuz then usually turn back to original location

**Comment by xezon** [comment]
All flags are now visible. But rotations are without system. One Artillery Platform is rotated one way and another one in another way. Would be good if there was a system. For example all platforms in the north rotated one way, and all in the south the opposite way.

At the top I recommend to rotate all of them like this:

![shot_20240121_171736_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d4fc34be-33a3-4acf-9902-8fe7d28a61b5)

And at the bottom like this:

![shot_20240121_171743_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7d244598-885c-4337-807b-10d3f71020ce)

Then the flags perfectly catch the sun light.

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
I do not see change. Rotations of 4 Artillery platforms at the right side are different from left side, top and bottom.

**Comment by TimberOwl** [comment]
ive completely change them but dunno ill check again then sry
