### ISSUE TITLE
[Candidate 1v1 Hanamura Temple ZH v1] Mirrored Artillery Platform on side lanes have different pathways around them

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#462]
## Observed behavior

Mirrored Artillery Platform on side lanes have different pathways around them.

## Expected behavior

Mirrored Tech Buildings offer equal unit mobility opportunities.

## Screenshots

![shot_20231119_155201_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4dd5ad5f-f39c-492d-b268-9e31bf8f928b)

![shot_20231119_155206_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a44912f5-e74f-4563-8cb2-d236294c66a3)

**Comment by TimberOwl** [comment]
ill put impassible
