### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Ambient light has pink tint

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#463]
## Observed behavior

Ambient light has a slight pink tint.

## Expected behavior

Ambient light looks natural.

## Screenshots

![shot_20231120_175251_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9ac28c62-cd55-4cdc-b00a-16e8cbdff0e1)

![shot_20231120_183811_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a19f14c0-f63a-4c5f-b32f-442be0cd86eb)

**Comment by Newgate-M17** [comment]
This is by design, I would like to keep it this way. It doesn't affect the players and gives the map a different feel.

**Comment by xezon** [comment]
As designed.
