### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Mirrored supply piles have non uniform gaps

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#464]
## Observed behavior

Mirrored supply piles have non uniform gaps.

## Expected behavior

Mirrored supply piles offer equal unit mobility opportunities.

## Screenshots

![shot_20231120_172621_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/963bfac9-eabe-4782-8d27-fa1a58085dc7)

![shot_20231120_172634_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cfcf666f-492c-4e87-b13a-c86cd21f9bd4)

**Comment by Newgate-M17** [comment]
I will fix this
