### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Tech Buildings have custom rotations that decrease visibility on flag

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#465]
## Observed behavior

Tech Buildings have custom rotations that decrease visibility on flag.

## Expected behavior

Tech Buildings use default rotation or custom rotations that provide high visibility on flag.

## Screenshots

![shot_20231120_172510_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/114c1b34-6432-4439-87c5-e7de56500e94)

**Comment by Newgate-M17** [comment]
I'll adjust them
