### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] A house is missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#466]
## Observed behavior

A house is missing fire ports. Soldiers shoot from 0,0,0. Soldiers in this building can damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231120_173846_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/76096e27-a887-46c4-9f14-82a492386956)

**Comment by Newgate-M17** [comment]
Didn't even know this was an issue :0
I'll find a replacement then

**Comment by xezon** [comment]
The new house has the same issue

![shot_20231126_103024_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ae328133-de0b-47ca-aae5-7fa9d3ee421f)

**Comment by xezon** [comment]
Here is the practical implication of this problem: Since rockets spawn at 0,0,0 there is a higher chance to hit the terrain nearby and damage itself.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/02b9ff6f-6f2f-4858-8c38-86c0f8da4c14

**Comment by xezon** [comment]
I was wrong about houses on the other side being ok. The outer house on the other side also has no fire ports.

![shot_20231202_180442_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f29bd81e-c05c-4c52-a937-d4376de9bef1)

So this issue is still valid (on both sides)

Also the default building damages are asymmetric. See:

![shot_20231202_180357_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ce867280-7562-47bf-8e28-9850573c287d)

![shot_20231202_180404_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/667eb81e-8689-4345-9575-9249c8d831c9)

**Comment by xezon** [comment]
### 18.06.2024

It is still possible to self destruct the Northern house.

I think the previous houses looked better in this map setting.

The way to fix this is
a) make terrain under houses flat
b) raise the houses a bit above the terrain to leave more room for missiles to fly above terrain

![shot_20240618_093021_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0a06d0f6-8768-426a-a2f0-9109c61ebc12)

**Comment by Newgate-M17** [comment]
I will raise the ground under both huts to fix this. I did test the buildings for an hour though, and I looked out for this exact bug. It's weird it never happened once.

I actually think these newer buildings better match the setting than the apartment blocks, I'm glad I got the opportunity to change a few things before the release
