### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Map hosts tree trunks with sway

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#467]
## Observed behavior

Map hosts tree trunks that sway in the wind. It looks strange. Affects all tree trunks.

## Expected behavior

Tree trunks do not sway in the wind.

## Screenshots

![shot_20231120_175416_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/df6c7c6a-e1a3-405c-bbc3-4f161fc715b1)

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3e5785bc-af46-44ae-8691-1c994a30e8d1

**Comment by Newgate-M17** [comment]
Easy fix, I'll take care of it

**Comment by xezon** [comment]
Newgate:
> I was unable to get rid of the tree sway in the stump without making the map not safe for transfer without re

**Comment by xezon** [comment]
Newgate:
> I think it's better to close it
