### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Map terrain is uneven at many places which can be tough for Rocket Buggies and Humvees

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#468]
## Observed behavior

Map terrain is uneven at many places which can be tough for Rocket Buggies, Humvees and similar. It certainly is a problem when force firing the ground. It is less of a problem when attacking units, but some hills are higher than others, so it can be a gamble.

My expectation is that this map will not be popular because there will be frustrating experiences with this design.

## Expected behavior

No excessive bumps on terrains to avoid unit targeting issues.

## Screenshots

![shot_20231120_175439_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3375943d-4323-49be-b201-860fc191c6c1)

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/abf11e88-949b-49f7-9761-11d641cf42d2

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/59d74418-31ac-4984-abd9-24916ef0746a

**Comment by xezon** [comment]
Not sure if this should be a blocker.

**Comment by xezon** [comment]
Also note that bumpy terrain like this makes it easier to see stealth Tunnel Networks and other stealth buildings. Also it allows to see shapes of unseen buildings in the fog after the terrain was dented.

**Comment by Newgate-M17** [comment]
I'll fix this

**Comment by xezon** [comment]
Map terrain looks much flatter now which should help. There are still a few patches left with many dents and ripples however.

![shot_20231126_102027_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/af16b653-5262-4abd-be1e-2799b2a18e6e)

![shot_20231126_102033_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/40d6947f-940b-4f13-9e95-5c266cca4a64)

![shot_20231126_102056_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1b941178-6fbc-43ce-90fb-7d9d1cdfd42d)
