### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Wind audio is crackling when scrolling

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#469]
## Observed behavior

Wind audio is crackling when scrolling.

## Expected behavior

Ambient audio is pleasant.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1feae2ac-48a0-4096-8157-35fef542c622

**Comment by Newgate-M17** [comment]
I'll also fix this
