### ISSUE TITLE
[Candidate 2v2 Hell on Rails ZH v3] Map terrain is uneven at many places which can be tough for Rocket Buggies and Humvees

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#470]
## Observed behavior

Map terrain is uneven at many places which can be tough for Rocket Buggies, Humvees and similar. It certainly is a problem when force firing the ground. It perhaps is less of a problem when attacking units, but some hills are higher than others, so it can be a gamble.

My expectation is that this map will not be popular because there will be frustrating experiences with this design.

Similar to
* #468

## Expected behavior

No excessive bumps on terrains to avoid unit targeting issues.

## Screenshots

![shot_20231120_201502_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2cc2221f-8a2e-48f4-91f6-062d3e63ed85)

![shot_20231120_204242_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9f61a98f-3a59-4ea4-a770-fc4fc06b28c9)

![shot_20231120_204405_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/90a7b332-dd68-4a2e-b303-f6be4e369d5a)

**Comment by Newgate-M17** [comment]
I'll smooth them out a bit to prevent any issues
