### ISSUE TITLE
[Candidate 2v2 Hell on Rails ZH v3] Map hosts bunkers with night lights despite not being a night map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#471]
## Observed behaviour

Map hosts bunkers with night lights despite not being a night map.

## Expected behavior

Map hosts bunkers for the day.

## Screenshots

![shot_20231120_204209_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/18d43ac0-01d3-4826-a198-0cda52acedc4)

**Comment by Newgate-M17** [comment]
I'll change this
