### ISSUE TITLE
[Candidate 2v2 Hell on Rails ZH v3] Bottom center supply dock offers better building opportunities

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#472]
## Observed behavior

Bottom center supply dock offers better building opportunities

## Expected behavior

Mirrored supply docks offer about equal building opportunities.

## Screenshots

![shot_20231120_202232_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d56f2db2-ab2f-403a-aa63-e64c633a7690)

![shot_20231120_202239_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/187e572a-ed92-4eb6-892b-ca672ebdcdf4)

**Comment by Newgate-M17** [comment]
I'll fix this

**Comment by xezon** [comment]
Space is much better for GLA Supply now. However, the bottom Dock still offers much better build space for a China Supply.

![shot_20231126_104546_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c703af2b-cb6d-4f52-bff5-92b5c8e8cf94)

![shot_20231126_104607_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b58c5531-fc68-4318-b299-6cea60388271)
