### ISSUE TITLE
[Candidate 2v2 Tournament D ZH v1] Player spots have urban city ambient sounds on desert jungle terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#475]
## Observed behavior

Player spots have urban city ambient sounds on desert jungle terrain.

## Expected behavior

Player spots have natural ambient sounds on desert jungle terrain.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e534488d-ea19-4d0a-a53c-8c5c48bf8179

**Comment by Newgate-M17** [comment]
I'll change this
