### ISSUE TITLE
[Candidate 2v2 Tournament D ZH v1] Map contains houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#477]
## Observed behavior

Map contains houses with missing fire ports. Soldiers will shoot from 0,0,0.

## Expected behavior

Map has houses with fully functioning fire ports.

## Screenshots

![shot_20231121_202305_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ec4db0ec-5974-4298-97ec-eb03b9d4ec82)

![shot_20231121_202413_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6e9b3ec7-3489-4d9e-8057-fa80efe1b6d0)

**Comment by Newgate-M17** [comment]
I'll find a replacement

**Comment by xezon** [comment]
Same issue on the new house. And the other bugged house was unchanged.

![shot_20231126_105953_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9a29d1e6-bb8a-4110-8b36-6677f8b256e8)

**Comment by xezon** [comment]
Not fixed. Both new houses do not have enough fire ports. Half the soldiers shoot from 0,0,0. I suggest to test the new houses before committing to them.

![shot_20231128_202607_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/87d0780b-6ef6-4176-819a-3b5534164b05)

The practical implication is that they are unable to shoot over the small dent in the terrain.

![shot_20231128_202624_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/23375366-b226-48ab-be11-07dbdf36f44e)
![shot_20231128_202742_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/17a2412e-9827-442a-9598-3e1d079785ff)

**Comment by xezon** [comment]
Fire ports of new houses look good. But the top right house is 50% damaged and bottom left house is not. This is not fair.

![shot_20231202_174448_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4d477503-57fb-418b-93c6-e40ae7c32950)

![shot_20231202_174453_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2fd6897b-3cff-4e68-83c3-ed73fa12ac7e)

**Comment by Newgate-M17** [comment]
True, this isn't fair. Shouldn't take you long to fix and it would save a lot of hassle on my end

**Comment by xezon** [comment]
Also, while looking at the houses, the top left house has another disadvantage: The gap between the house and the mountain cliff is much larger, so that house will not be as effective for defending this area. The left team may have an advantage here.

![shot_20231202_174750_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/75675a03-e0dd-4d56-b3d3-98b8b12d7907)

![shot_20231202_174756_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d06c7cf5-4db0-4481-b4c5-5112ba8bb5e1)
