### ISSUE TITLE
[Candidate 2v2 Tournament D ZH v1] Right team Supply Piles offer more build space than left team

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#481]
## Observed behavior

Right team Supply Piles offer more build space than left team.

## Expected behavior

Mirrored Supply Piles offer about equal build space.

## Screenshots

![shot_20231121_203341_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9f6a20a5-eb5c-48c4-a79b-25ffcc73e3e5)

![shot_20231121_203350_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6708e75b-a146-45c6-8a53-7d1fa7cc41e5)

**Comment by Newgate-M17** [comment]
I will sort this out

**Comment by xezon** [comment]
It still offers slightly better build opportunities. But as much anymore.

![shot_20231126_110816_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7847d4e7-cfca-4b1d-b181-d59f25dd902f)

![shot_20231126_110823_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf19cb46-c461-4635-ac98-5806bc41fd8c)
