### ISSUE TITLE
[Candidate 1v1 Snowy Drought ZH v5] Many buildings have broken fire port setups

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#485]
## Observed behavior

Many buildings have broken fire port setups. Soldiers will shoot from 0,0,0.

## Expected behavior

Ranked Maps use buildings with fully functional fire ports.

## Screenshots

![shot_20231125_164312_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4512d8fb-03e3-445c-85dd-ced509f258f1)

![shot_20231125_164335_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd6f8006-c55e-4c47-98d1-c52d847ac538)

![shot_20231125_164517_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/60607197-4771-408c-a535-3e13a2f5ff5c)

![shot_20231125_164544_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6cbc274b-07d5-424c-aa8e-c989fdcff24e)

**Comment by xezon** [comment]
Not a blocker, because this map is a revision of an established map and the buildings do not sit on uneven terrain.

**Comment by Jundiyy** [comment]
I would prefer not to mess with this. So, will leave this as is.

**Comment by xezon** [comment]
As designed.
