### ISSUE TITLE
[Candidate 3v3 Aeon of Excalibur ZH v5] Default camera makes bottom border difficult to see

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#486]
## Observed behavior

Default camera makes bottom border difficult to see. Artillery platform is barely visible. Player needs to use camera zoom trick to properly see whole map.

## Expected behavior

Camera border is well setup to cause no issues with default camera.

## Screenshots

![shot_20231125_170916_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/93d1489b-c708-44f3-b758-79bb161098f6)

**Comment by toirehantaa** [comment]
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/dcd3a355-96b8-4d80-817c-9f0e9ed1a682)
is this acceptable? I expanded the map by 50 feet on the bottom side and made impassable terrain due to otherwise space advantage

**Comment by TimberOwl** [comment]
ill find one

**Comment by xezon** [comment]
Is a bit better, but it is still not possible to see everything south without zoom trick.

Here I parked Dozer at the bottom. It cannot be seen unless the Control Bar is toggled down or zoom trick is used.

![shot_20231202_172922_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a85d6bc1-3c06-4902-b1ee-5f6819903b8a)

![shot_20231202_172926_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bc7fac29-7662-474e-af70-d48ee6eb1c1c)

**Comment by xezon** [comment]
Was improved. Remaining lack of default visibility is acceptable.
