### ISSUE TITLE
[Candidate 3v3 Aeon of Excalibur ZH v5] Some structures clip into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#487]
## Observed behavior

Some structures clip into terrain.

## Expected behavior

Structures sit tight on terrain.

## Screenshots

![shot_20231125_171116_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b9322a42-a732-490d-b6f8-9bc3aa741314)

![shot_20231125_171140_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/94f41ad9-73f6-4f33-972d-6ee1071df8f4)

![shot_20231125_171149_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2aae174c-5768-47d2-be2a-73e68818d7b6)

![shot_20231125_171244_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/231cbd8d-182a-49db-802f-5d8475e87932)

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
Fixed.
