### ISSUE TITLE
[Candidate 3v3 Aeon of Excalibur ZH v5] Custom rotation of Artillery Platform hides its flag

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#488]
## Observed behavior

Custom rotation of Artillery Platform hides its flag.

## Expected behavior

Flags of Tech Buildings are visible.

## Screenshots

![shot_20231125_171308_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0f6ea6cf-b371-4c82-92df-0bd0ef5968e9)

**Comment by toirehantaa** [comment]
we already talked about this on the dammed korhal map...

**Comment by xezon** [comment]
Flag must be visible.
