### ISSUE TITLE
[Candidate 3v3 Aeon of Excalibur ZH v5] Map uses ugly trees

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#490]
## Observed behavior

Map uses ugly trees.

## Expected behavior

Map uses pretty trees.

## Screenshots

![shot_20231125_174334_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f4304cb0-b589-45a5-8acb-100c55644901)

**Comment by toirehantaa** [comment]
I actually love these trees, I like their shading
