### ISSUE TITLE
[Candidate 1v1 Yelling Avalanche ZH v2] Map contains houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#493]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings consistently damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231126_114606_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6080dd91-dd80-4208-b3d5-48f1333cbec9)

![shot_20231126_114639_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cf6f6004-bb89-40b4-8f34-3285ffcfa73f)

![shot_20231126_114800_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f08868b4-ac79-45c2-96d9-e80c6a79b924)

![shot_20231126_114850_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/67bfcc0a-848d-4a51-ba2c-fbd2ba31f335)

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2423eb78-7bbc-46fd-bdb1-62b15ca22978

**Comment by NoMerciBKK** [comment]
updated (removed both fishinghouses in mid cause they are sunken into the ground and they would float to much ich elevated)
