### ISSUE TITLE
[Candidate 1v1 Fort Payne ZH v1] Map contains houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#496]
## Observed behavior

Map contains houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings can damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231126_120533_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c807bf69-3695-4673-8036-23a3f3ec2ba1)

![shot_20231126_120549_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/87b8bb79-8399-4c4c-94e0-cb59adee934b)

![shot_20231126_120733_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ba58fcda-9875-4e98-9003-890246b84982)

![shot_20231126_120750_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/754a1634-7976-4b12-b58c-8ad538822b19)

![shot_20231126_120814_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/472fd51f-b633-4907-835a-8927fd0c05da)

**Comment by FiReArM-ZH** [comment]
When I checked it, they do very little damage to themselves even when they are 100% full.
Generally, players put only one or two rocket guys inside. So, they will do little to no damage in that case.

So, I think this can be removed from blocker list

**Comment by xezon** [comment]
I was still able to self damage with the following:

![shot_20240123_195008_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9af52fb3-3c73-4894-98a4-eb58388fb00a)

![shot_20240123_195219_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bc8326f0-2867-4c74-b556-0c1ca49a4463)

These 2 buildings can self damage, likely because they stand so close to each other and intersect.

![shot_20240123_194723_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2db28452-b4fd-4521-a9c6-92afeed774f4)
