### ISSUE TITLE
[Candidate 1v1 Fort Payne ZH v1] Soldiers inside right center house cannot shoot south

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#497]
## Observed behavior

Soldiers inside right center house cannot shoot south.

## Expected behavior

Soldiers inside right center house can shoot south.

## Screenshots

![shot_20231126_120633_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ae5c4fcc-9cf4-41b8-8ede-2abcb97d8a5b)

**Comment by FiReArM-ZH** [comment]
If building behaves same way on other side of the map, I would let it pass side they balance out.
If not, must be changed

**Comment by xezon** [comment]
Firing from house of original post works now.

I found another house where shooting (ground) in a direction somehow does not work. There is no apparent hill in the terrain.

![shot_20240123_194857_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8c247790-3d7c-4a70-9e90-758aca92851e)
