### ISSUE TITLE
 [Candidate 1v1 Echo ZH v1] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#498]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0.

## Expected behavior

Ranked Maps use houses with good fire port setups.

## Screenshots

![shot_20231126_121422_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/06c211b4-2bdc-4a5c-aedd-a1b1a8a11afb)

![shot_20231126_121441_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c298dca2-b4f2-4836-9540-08f28c48ffde)

![shot_20231126_121457_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2e59d293-cc4f-471c-bf0f-78fded78499e)

**Comment by xezon** [comment]
Not a blocker bug, because terrain around houses is very flat and there appears to be no practical detriment.

**Comment by ReLaX82** [comment]
If houses gets destroyed by own fire firing at enemy I would agree, but as you stated "no practical detriment" I would like to leave that.

**Comment by xezon** [comment]
As designed.
