### ISSUE TITLE
[Candidate 1v1 Double Damination ZH v4] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#499]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings consistently damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231126_122118_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1be2ca29-ec4a-4d08-8a6c-66604b3416dc)

![shot_20231126_122211_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5372a387-355e-4d2e-bd38-140d49f44297)

![shot_20231126_122235_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/419052e3-b608-4e1d-9f75-f7a8170fedc3)

![shot_20231126_122243_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/abad94a4-00c6-4339-9cd8-09afcc76e1d9)

![shot_20231126_122305_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/75e209e6-dfca-4454-abfc-c0d8a348e38e)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
There are still houses where soldiers can damage themselves:

### When shooting south

![shot_20240120_100757_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5d95b817-d885-4353-99e7-8bf876e07f34)

![shot_20240120_100811_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/acedf72c-8bfe-432d-ac08-d2d79ebcbc4b)

![shot_20240120_100827_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/57f48998-82ff-4e6d-9c4f-00005c14cd7c)

![shot_20240120_100945_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6af9fcc7-4e0f-445b-83f1-7b7210e26b19)

### This has troubles shooting east

![shot_20240120_101110_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d76dbdbf-b2a6-45da-9fe8-b8aee91bf556)

![shot_20240120_101144_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e347e15-cabb-41ca-92b2-f790cbaf1ef5)
