### ISSUE TITLE
[Candidate 1v1 Dammed Scorpion ZH v2] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#500]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0.

## Expected behavior

Map uses houses with good fire port setups.

## Screenshots

![shot_20231126_122706_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1cca88c4-ed9d-4633-a166-894816745c39)

![shot_20231126_122731_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b2407bf2-f44d-4d8f-9e4e-4e74de41b0fa)

**Comment by xezon** [comment]
Not a blocker bug, because terrain around houses appears to be located on favorable terrain, causing no damage to buildings.

**Comment by DoMiNaToRuk2** [comment]
map is a one-for-one copy of sand scorpion to make sure player still like it. Sand Scorpion is ranked and is crazy popular, maybe top 5 map. Suggest to keep it exactly the same, players been using it many years and never said anything.

fix in patch

**Comment by toirehantaa** [comment]
yeah, as long as it doesn't damage itself, like on double damination (which I now fixed) it's fine

**Comment by xezon** [comment]
As designed.
