### ISSUE TITLE
[Candidate 1v1 Bozic Destruction ZH v6] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#502]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings consistently damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

### 1

![shot_20231126_123801_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0ea84215-b11c-419b-908f-591acb7eac4c)

### 2

![shot_20231126_124001_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf3c3c23-2c94-4821-835b-41d096ee9ed4)

### 3

![shot_20231126_124045_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1aad5ca3-995a-490b-bb9b-65e177e5de42)

### 4

![shot_20231126_124052_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/64f112e1-4567-42d1-956c-58b1f1a66429)

### 5

![shot_20231126_124100_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e03c1417-603e-4568-94ef-159f5f0ee2f9)

### 6

![shot_20231126_124148_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ea1f089b-e76d-48bd-83a2-e42251f654e3)

**Comment by xezon** [comment]
House 1 was replaced with Tower.
House 2 was removed.
House 4 can still damage itself.
Houses 3, 5, 6 appear to be ok now. They look to be lifted a bit above ground.

![shot_20240121_150130_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ff62c009-ddfa-47b3-9881-b16488734969)

**Comment by NoMerciBKK** [comment]
updated

**Comment by NoMerciBKK** [comment]
> Houses 3, 5, 6 appear to be ok now. They look to be lifted a bit above ground.

yes flaten ground did not change the problem the houses are elevated by 0,5
