### ISSUE TITLE
[Candidate 1v1 Blue Hole ZH v1] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#504]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings consistently damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231126_124859_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/87bd3d25-393d-480f-9dba-5a0084974a63)

![shot_20231126_125051_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7c2ee1a9-aa37-443f-bf5d-6ac245d3afc8)

![shot_20231126_125221_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1c6f078b-430a-407d-b9ce-965afa9ef9fa)

**Comment by NoMerciBKK** [comment]
fixed terrain is flat now

**Comment by xezon** [comment]
In new version, I tested all buildings that have soldiers shoot from 0,0,0 and was able to self destruct with the following ones:

![shot_20231127_191605_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b1b97d6f-2910-444f-bcbd-8d84c506dcdc)

![shot_20231127_191809_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0b0f1b51-41f0-4b4e-bfcf-f6634cac5c21)

![shot_20231127_192229_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/10dd197d-a1bc-4865-aa53-f392bac96def)

As for the towers, I suggest to replace them with another tower, because it looks bad when the soldiers shoot from the bottom.

![shot_20231127_192123_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dd5a1e1b-0437-4568-b951-52556aba0eac)

**Comment by NoMerciBKK** [comment]
updated
