### ISSUE TITLE
[Candidate 1v1 Arizona Airfield ZH v1] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#505]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0.

## Expected behavior

Map uses houses with good fire port setups.

## Screenshots

![shot_20231126_130042_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bbd0662a-ceea-480f-ba72-16d946f01b20)

![shot_20231126_130100_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d72ffe01-9b94-4926-a8a0-1185b25ea411)

![shot_20231126_130154_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5808c399-c37c-4e08-a3a4-111aa6c265d7)

**Comment by xezon** [comment]
Not a blocker bug, because houses sit on flat terrain and appear to cause no detriment.

**Comment by DoMiNaToRuk2** [comment]
first screenshot uses a building that appears in a lot of maps, like TD original for example.
rest are symetrical either side so fair for players and these buildings also suit an airport style (name of the map)

this is also TK lyo's map who had a mental breakdown and is no longer contactable.
Suggest to leave it and map working totally fine, played in challenges daily - actually very popular

**Comment by xezon** [comment]
As designed. Fire ports to be fixed in Game Patch.
