### ISSUE TITLE
[Candidate 2v2 Aztec Empire ZH v1] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#507]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0. Soldiers in these buildings consistently damage themselves.

## Expected behavior

Map uses houses with good fire port setups only or is setup in a way where those houses with broken fire ports do not cause problems.

## Screenshots

![shot_20231126_185314_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9b017842-9288-4aea-9723-33fc3057d79a)

![shot_20231126_185351_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bb735e41-f5e5-4e1f-a9d1-857860a6ce0e)

**Comment by toirehantaa** [comment]
removed the bunker now, not seeing a way where I could entirely fix this, I think it makes it a bit more open then as well.

**Comment by xezon** [comment]
The issue on the first image can perhaps be avoided by raising the bunker a bit.
The structure on the second image would have to be replaced if we wanted good fire ports on it.

**Comment by xezon** [comment]
Note that the really damaged structures can still be repaired and used. I was unable to self destruct these structures by shooting, so I will demote this from blocker.

![shot_20231206_202937_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/37ab8d6a-6077-4474-acfd-448777b57c5a)

**Comment by toirehantaa** [comment]
those buildings are supposed to be repaired ingame, all intended

**Comment by xezon** [comment]
Rocket houses as designed. Blocker was fixed.
