### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] Map uses houses with missing fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#508]
## Observed behavior

Map uses houses with missing fire ports. Soldiers shoot from 0,0,0.

## Expected behavior

Map uses houses with good fire port setups.

## Screenshots

![shot_20231126_185817_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a4bbf998-5340-4e20-abad-4e4e84f17053)

**Comment by xezon** [comment]
Not blocker bug, because houses sit on flat terrain and appear to cause no detriment.

**Comment by TimberOwl** [comment]
i dont even know how to fix that tbh

**Comment by TimberOwl** [comment]
is it necessary ?

**Comment by xezon** [comment]
Is not necessary when there are no gameplay implications.

**Comment by DoMiNaToRuk2** [comment]
This should not be changed. It's the same bunker used in oil rampage - one of most popular maps of all time. It's iconic to this map and nobody ever noticed, all players have the same building. Please close this issue as it wont be fixed. All other issues TimberOwl will review.
