### ISSUE TITLE
[Candidate 2v2 Frontier Rails ZH v1] Player can build on top of train cars, but scaffold does not appear

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#512]
## Observed behavior

Player can build on top of train cars, but scaffold does not appear. Money is not deducted, but scaffolding sound is started.

## Expected behavior

Player cannot build on top of train cars, or scaffold appears when building.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f5261376-ee53-41a7-be3a-3841fd5ec927

**Comment by NoMerciBKK** [comment]
this is neither a bug nor shall it be a blocker you just need to destroy the trains before you can build there.
Its a unit like a truck those drive away if you build a scaffold (see "Nocky Mountains" traktor crushes worker)
[https://github.com/TheSuperHackers/GeneralsRankedMaps/issues/350]

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/8248e76d-8f64-4ebf-8c14-96c3fa0501f0)

**Comment by xezon** [comment]
Yes. But why does it not show the bip for invalid build space?

**Comment by NoMerciBKK** [comment]
Thats how units work i think only the big planes do have a "not build space" on the ground

**Comment by xezon** [comment]
## Scaffold vs Train and normal unit

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/53121757-ae43-4ab1-8bb1-baaedabc5c17

## How Scaffold should react to train

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e0db0b7e-2166-4cad-bde7-2a0b9af1b30f

**Comment by NoMerciBKK** [comment]
the avanger is bound to a player so its like a playerbuilding you cant build for the game

**Comment by xezon** [comment]
The reason Avenger blocks build is because of its PORTABLE_STRUCTURE. See
* TheSuperHackers/GeneralsGamePatch#630

**Comment by xezon** [comment]
I suspect if train was setup more like a structure, then it would block build. Whether or not this is possible with non-mismatch map.ini, I do not know, but it would be good if it was investigated at least.

**Comment by NoMerciBKK** [comment]
> I suspect if train was setup more like a structure, then it would block build. Whether or not this is possible with non-mismatch map.ini, I do not know, but it would be good if it was investigated at least.

yes i do agree but i dont think this shall be a blocker cause you can destroy the trains and build afterwords, on indestructable trains i do also agree that those should have impassible terrain beneth

**Comment by NoMerciBKK** [comment]
can this be closed now? it also happens on alot of other maps where you use the trains

**Comment by xezon** [comment]
Here is how bug was fixed for Avenger for reference

https://github.com/TheSuperHackers/GeneralsGamePatch/pull/630/files

Unclear if fixing this in map would cause mismatch after next map load. Would have to be tested.

**Comment by NoMerciBKK** [comment]
and how did he fix this?

**Comment by xezon** [comment]
For Avenger & Co it was fixed by adding INERT KindOf as shown in the linked Pull. The train likely has a combination of flags that causes this misbehaviour. If we cannot fix, then it is fine, but at least we can try.

**Comment by NoMerciBKK** [comment]
i have no idea how i shall fix this within the WB

**Comment by xezon** [comment]
Cannot be fixed.
