### ISSUE TITLE
[Candidate 3v3 Mojave Desert ZH v1] Tents near main bases do not have mirrored layouts

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#515]
## Observed behavior

Tents near main bases do not have mirrored layouts.

## Expected behavior

Tents near main bases have mirrored layouts so that soldiers inside can cover the same areas.

## Screenshots

![shot_20231223_100947_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a42b6cbc-8f6d-463b-9a0b-b3cdd9c25c1a)

![shot_20231223_100950_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b87f2bf8-8c54-4021-b6ba-83016b41dfd9)

![shot_20231223_100954_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9367522e-f472-4dd7-bfae-5012541853ce)

**Comment by NoMerciBKK** [comment]
fixed
