### ISSUE TITLE
[Candidate 3v3 Mojave Desert ZH v1] Supply Piles in center do not offer space for equal building opportunities

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#516]
## Observed behavior

Supply Piles in center do not offer space for equal building opportunities.

## Expected behavior

Supply Piles in center offer space for equal building opportunities.

## Screenshots

![shot_20231223_100359_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/db83dfaf-3a67-47e9-8881-1eb673b51c8a)

![shot_20231223_100411_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b7545cc9-8773-4c7d-bdf0-0b016f14a038)

![shot_20231223_100424_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/66d68c3a-db99-4adf-b40b-3caca82866d1)

**Comment by NoMerciBKK** [comment]
fixed
