### ISSUE TITLE
[Candidate 3v3 Mojave Desert ZH v1] Some Tech Buildings have custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#517]
## Observed behavior

Some Tech Buildings have custom rotations that make their flag less visible.

## Expected behavior

Tech Buildings have default rotation or custom rotations that make their flag highly visible.

## Screenshots

![shot_20231223_095815_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0bc2be8a-3645-4eab-ac0e-2a16f2710e80)

![shot_20231223_100551_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4f80bf39-2cc1-4df2-a29c-cb723d16848a)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Looks ok in new version. The rotations of the Artillery Platforms appear to be not symmetrical however. Unclear if as designed.

**Comment by NoMerciBKK** [comment]
yes its not symmetrical, cause you wont see a flag anymore on one Artillery and i tried that the hitbox is kinda the same on all sides as you go on with the circle
