### ISSUE TITLE
[Candidate 2v2 Temperate Woods ZH v3] Big rocks are floating above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#518]
## Observed behavior

Big rocks are floating above terrain.

## Expected behavior

Rocks sit on terrain.

## Screenshots

![shot_20231223_110614_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0078d96a-7f0a-4197-94f3-feb29b632125)

**Comment by toirehantaa** [comment]
fixed.
