### ISSUE TITLE
[Candidate 2v2 Temperate Woods ZH v3] Units can move through big rocks on path ways

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#519]
## Observed behavior

Units can move through big rocks on path ways.

## Expected behavior

Rocks on path ways are small or are impassable.

## Screenshots

![shot_20231223_110507_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/55fee6c3-4e3c-4861-b939-70cf60a3ee39)

![shot_20231223_110528_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cce3af40-9a0f-45ee-b40b-47ff2d185456)

![shot_20231223_110549_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bcb7b080-fe54-4857-9613-723b3808e006)

![shot_20231223_110629_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/97a3aec2-a6e3-4df6-bc4e-8d17394c25ec)

**Comment by toirehantaa** [comment]
fixed.
