### ISSUE TITLE
[Candidate 3v3 Taiga Terror ZH v5] Center Supply Piles offer unequal space for building

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#522]
## Observed behavior

Center Supply Piles offer unequal space for building.

## Expected behavior

Center Supply Piles offer equal space for building.

### Easy to build here

![shot_20231223_112610_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3d3b3137-6093-4a30-b138-ffc277d6ab07)

### Difficult to build here

![shot_20231223_112613_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e2982ac9-7065-4701-9956-9a63b4f75d29)

### Difficult to build here

![shot_20231223_112616_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e864ead6-a12b-466e-8f1d-0cff97eca059)

### Impossible to build here

![shot_20231223_112631_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2038a645-eb12-4e7d-b390-47d4919b64aa)

### Easy to build here

![shot_20231223_112650_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3990cd1c-bee5-4308-bc54-640d8743a56d)

### Impossible to build here

![shot_20231223_112715_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a5433f5b-f317-4ca0-82b1-0f2ee74aff4c)

**Comment by toirehantaa** [comment]
fixed.
