### ISSUE TITLE
[Candidate 3v3 Taiga Terror ZH v5] Units can be air dropped on north west mountain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#523]
## Observed behavior

Units can be air dropped on north west mountain.

## Expected behavior

Units can not be air dropped on north west mountain.

## Screenshots

![shot_20231223_112830_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bc4c39c1-855f-454b-86f1-b6a263d757c2)

**Comment by toirehantaa** [comment]
fixed.
