### ISSUE TITLE
[Candidate 3v3 Taiga Terror ZH v5] Road tile is visible in map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#524]
## Observed behavior

Road tile is visible in map border.

## Expected behavior

Road tile is not visible in map border.

## Screenshots

![shot_20231223_112839_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0a442666-4013-458a-b350-f7779f4bc76f)

**Comment by toirehantaa** [comment]
fixed.
