### ISSUE TITLE
[Candidate 3v3 Taiga Terror ZH v5] Soldiers in tent can damage themselves when firing north east

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#525]
## Observed behavior

Soldiers in tent can damage themselves when firing north east.

## Expected behavior

Soldiers in tent can not damage themselves. Tents sit on flat terrain.

## Screenshots

![shot_20231223_113705_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/db94ad91-5efd-4789-91d4-df0c30b4db95)

**Comment by toirehantaa** [comment]
should be fixed now?...
