### ISSUE TITLE
[Candidate 3v3 Taiga Terror ZH v5] Sound emitters have no easing and can crackle

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#526]
## Observed behavior

Sound emitters have no easing and can crackle. Sound in center is most pronounced.

## Expected behavior

Sound fades in and out gracefully. Sound does not crackle.

## Screenshots

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/27b8bc21-94aa-402b-8401-804fc4265e64

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3528491e-3f8f-4547-a6af-8bc508d2d908

**Comment by toirehantaa** [comment]
fixed.
