### ISSUE TITLE
[Candidate 4v4 Muddy Madness ZH v1] Main Supply Docks do not offer equal unit mobility opportunities

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#527]
## Observed behavior

Main Supply Docks do not offer equal unit mobility opportunities

## Expected behavior

Main Supply Docks do offer equal unit mobility opportunities, because this map can be played as 1v1v1v1v1v1v1v1 or 2v2v2v2 or 4v4.

### 1

![shot_20231223_122339_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c8e86175-f7c5-43c8-b908-82b034b5b6fd)

### 2

![shot_20231223_122343_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/41cbe3c1-1f66-4794-9ee5-60dd45be5b2e)

### 3

![shot_20231223_122347_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3f1ac728-80d6-47dc-9257-2adae3be4590)

### 4

![shot_20231223_122352_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9e05776e-ed7f-4ed3-b0af-1e7dc5149716)

### 5

![shot_20231223_122356_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b0c06c2c-b18b-4711-b0ea-d1a95a62515b)

### 6

![shot_20231223_122404_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/30cadd82-238c-4fe0-9d0f-4c64d73dce1c)

### 7

![shot_20231223_122409_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0bf785ad-f927-4f8a-ac5c-7da6f1dde5a8)

### 8

![shot_20231223_122413_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/101e9bf9-989e-4461-a2c4-55451c43061f)

### 9

![shot_20231223_122418_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/732f649b-b0fd-4981-843f-0ad0f5d37cc3)

### 10

![shot_20231223_122422_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e2d087b-9cf0-4b4f-a8ca-7bfaaf3b794b)

### 11

![shot_20231223_122427_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/271d3faf-b633-447a-a979-299532c4338a)

### 12

![shot_20231223_122435_49](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/edf51221-13dd-4891-a471-76ac0011feed)

### 13

![shot_20231223_122439_50](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/72134f02-055a-4d1a-9d5e-ec235cec28ed)

### 14

![shot_20231223_122448_51](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9bfafaa3-746a-4798-ad92-84e8f9a0ce95)

### 15

![shot_20231223_122453_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ee8c671e-40f7-4a56-8eca-83a1223d7380)

### 16

![shot_20231223_122459_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1d58db90-73df-4f64-bf60-2540002b46c3)

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
Units can now pass everywhere except here:

![shot_20240120_093233_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/02689723-5a29-48b8-8ce0-7d8bbf4bc93e)

Also, widths of pathways vary quite a bit from one Supply Dock to another. Ideally all mirrored pathways are about equal width.

**Comment by xezon** [comment]
It still is not possible to pass this gap above. Tested with USA Dozer.

**Comment by toirehantaa** [comment]
fixed
