### ISSUE TITLE
[Candidate 4v4 Muddy Madness ZH v1] Some Oil Derricks clip into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#528]
## Observed behavior

5 of 8 Oil Derricks clip into terrain.

## Expected behavior

Oil Derricks sit tight on terrain.

## Screenshots

![shot_20231223_122534_54](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6f7bbc1b-26d9-45fd-a395-1d32d1b5652f)

![shot_20231223_122544_55](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7035dfdb-9461-4243-be91-f1f2ef4742db)

![shot_20231223_122600_56](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/67fe9e44-c8e6-4817-9f44-6541401395ad)

![shot_20231223_122609_57](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/82edba5a-c45d-4f66-9e65-6afd712e12cd)

![shot_20231223_122623_58](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c4364b7b-b909-48e9-9265-58079f867e6c)

**Comment by toirehantaa** [comment]
fixed
