### ISSUE TITLE
[Candidate 4v4 Muddy Madness ZH v1] Main Supply Docks do not offer equal Supply boxing opportunities

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#530]
## Observed behavior

Main Supply Docks do not offer equal Supply boxing opportunities. Some spots have advantages.

## Expected behavior

Main Supply Docks offer about equal Supply boxing opportunities for all players to even the playing field.

### 1 - Has full boxing opportunities, has good collection path

![shot_20231223_130106_62](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/36e53ea7-dcf2-4689-8ad7-c08e08587eb3)

### 2 - Is missing boxing opportunities, has good collection path

![shot_20231223_130159_64](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/78908754-41f2-454f-9cef-dbae4ef2a764)

### 3 - Is missing boxing opportunities, has good collection path

![shot_20231223_130212_65](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/42b6833e-d641-4a54-a740-34997e962ff5)

### 4 - Has full boxing opportunities, has not good collection path

![shot_20231223_130234_66](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/683bc95a-3566-465b-94d3-b1fa9da3ccef)

### 5 - Has full boxing opportunities, has good collection path

![shot_20231223_130252_67](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1edc3fbc-f27c-438a-84d0-cbff31a4f015)

### 6 - Is missing boxing opportunities, has good collection path

![shot_20231223_130312_68](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4718d7a0-9a73-40cb-99e4-7907e42571af)

### 7 - Is missing boxing opportunities, has good collection path

![shot_20231223_130321_69](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5f6384e4-f673-43bf-9bcc-06ac8f72aa0f)

### 8 - Has full boxing opportunities, has good collection path

![shot_20231223_130336_70](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c5f433ea-b5cf-4329-93e0-a49bbd413477)

### 9 - Has full boxing opportunities, has good collection path

![shot_20231223_130347_71](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6eead78f-c27d-4cb3-9592-865b860344cb)

### 10 - Is missing boxing opportunities, has good collection path

![shot_20231223_130429_72](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/157c3b47-8b43-4f86-a7d5-38913ea51221)

### 11 - Is missing boxing opportunities, has good collection path

![shot_20231223_130442_73](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cfc2446c-d2ab-4ae0-bc1e-aecd835fb468)

### 12 - Has full boxing opportunities, has good collection path

![shot_20231223_130505_74](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fc4ff56a-cb3c-42da-9695-94b2ca10953c)

### 13 - Has full boxing opportunities, has good collection path

![shot_20231223_130524_75](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/39f6c3bf-2194-4004-b1d7-d97f95161e3e)

### 14 - Has full boxing opportunities, has good collection path

![shot_20231223_130556_76](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/09e530d2-be8c-48bd-9504-2de5b1f8779c)

### 15 - Is missing boxing opportunities, has good collection path

![shot_20231223_130610_77](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a040fa40-f0ce-4666-98a3-43a65897a54e)

### 16 - Has full boxing opportunities, has good collection path

![shot_20231223_130624_78](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b91126e0-0232-452f-8d5a-4a95ffa2bc49)

**Comment by toirehantaa** [comment]
I think it's fixed now?...

**Comment by xezon** [comment]
Yes looks like all Supply Docks can now be boxed equally.

I did see that this one position has quite a far gap to the terrain edge. So visually it looks as if units could pass. The Radar Van was not able to pass. I recommend to narrow the gap a bit.

![shot_20240120_094739_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/98124a15-c97e-4533-aad5-e52b184256b3)

**Comment by NoMerciBKK** [comment]
thats the mapborder what is blocking the way so i think this is good for now and can be finished no?

**Comment by xezon** [comment]
Or impassable terrain? The Supply Dock left to it is set up a bit better, by allowing to build closer to the map border.
