### ISSUE TITLE
[Candidate 4v4 Muddy Madness ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#531]
## Observed behavior

Audio emitters have no easing.

## Expected behavior

Audio emitters fade in and out gracefully when scrolling over the map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d570de3a-4dde-44ec-828a-253af02d6ce9

**Comment by toirehantaa** [comment]
fixed.
