### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Some Tech Buildings clip into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#532]
## Observed behavior

2 Tech Buildings clip into terrain.

## Expected behavior

Tech Buildings sit tight on terrain.

## Screenshots

![shot_20231223_180632_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/faabce55-1f04-4226-8403-0257052c866b)

![shot_20231223_180643_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7f054423-fc49-437f-817c-c9b67dbfa65c)

**Comment by TimberOwl** [comment]
fixed
