### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Tech Buildings in main bases are not uniformly rotated

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#533]
## Observed behavior

Tech Buildings in main bases are not uniformly rotated.

## Expected behavior

Tech Buildings in main bases are uniformly rotated for an organized look.

## Screenshots

![shot_20231223_180445_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ff1d00a2-71d4-4061-a4ef-7dcf5d80c7bf)

![shot_20231223_180505_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/90e78e3e-2887-4694-ba92-d5029c6cdef2)

**Comment by TimberOwl** [comment]
fixed
