### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] AI causes big stalls on map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#536]
## Observed behavior

AI causes big stalls on map. Occasionally drops down to 5 FPS for a short period. Tested with China Infantry Hard Army vs GLA, SWG Hard Armies. Perhaps is a pathing issue.

## Expected behavior

Map has no big stalls when playing with AI.

## Screenshots

![shot_20231223_181854_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/50827085-04dd-4c31-ad62-5e7633460e73)

**Comment by TimberOwl** [comment]
hmm didnt happened on me i cant test this on my pc . what is ur system

**Comment by xezon** [comment]
Replay for latest map version in GitHub. Fast Forward to 08:15 for biggest stalls.

## [freezingbursa_stalls.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/14072416/freezingbursa_stalls.zip)

![shot_20240127_142855_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/62b8ac53-99c9-4738-a037-8834c09d3740)

The lowest it drops on my machine was 5 FPS near the end of the match.

![shot_20240127_142537_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a4a132d7-864d-403c-9f0a-806b07488e7c)

**Comment by TimberOwl** [comment]
well i dont know if there is  a fix for this soo :(

**Comment by xezon** [comment]
TimberOwl: Cannot be fixed.
