### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Rocks are visible in map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#537]
## Observed behavior

Rocks are visible in map border.

## Expected behavior

Rocks do not extent into the border.

## Screenshots

![shot_20231223_181157_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/44c0c88e-1adc-4201-ac1d-0199c6a791ec)

**Comment by TimberOwl** [comment]
fixed
