### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Units can be air dropped onto south center mountains

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#538]
## Observed behavior

Units can be air dropped onto south center mountains.

## Expected behavior

Units can not be air dropped onto south center mountains

## Screenshots

![shot_20231223_181118_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2d7ff9c9-1427-4ff4-93b4-1d117911b457)

**Comment by TimberOwl** [comment]
oh nice find ill fix and send the new version
