### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Big rocks are located on passable terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#539]
## Observed behavior

Big rocks are located on passable terrain. Many times.

## Expected behavior

Only small rocks are located on passable terrain. Big rocks are located on impassable terrain.

## Screenshots

![shot_20231223_180907_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/92982a42-3a65-4fdd-b980-c40224543791)

**Comment by TimberOwl** [comment]
fixed
