### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Oil Derricks at the top cannot be driven around, but at the bottom can be

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#540]
## Observed behavior

Oil Derricks at the top cannot be driven around, but at the bottom can be.

## Expected behavior

Mirrored Oil Derricks offer equal room for unit mobility.

### Passable

![shot_20231223_180800_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e5d62de1-ef58-4fe2-a282-c32c87a48554)

### Impassable

![shot_20231223_180806_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fde7edff-2c22-4639-b8f6-c54289b1c143)

**Comment by xezon** [comment]
Unclear to me if this is a balance and blocker issue. The Oil Derricks are in the center, so perhaps about equal chance for both teams.

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Works in principle, but there is no a little patch of water on the short, creating a smaller gap for units to drive through.

![shot_20240127_141540_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f62e06ad-6856-4f1d-b548-9a4a82133a9f)
