### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Repair Bay at west side can be driven around, but Repair Bay at east side can not be driven around

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#541]
## Observed behavior

Repair Bay at west side can be driven around, but Repair Bay at east side can not be driven around.

## Expected behavior

Repair Bays offer equal room for unit mobility for fairness.

### Impassable

![shot_20231223_180730_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/91b2c076-3a55-4e5f-b2b2-068c2a993e28)

## Passable

![shot_20231223_180738_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/57deceb3-c3b6-4de2-aa6a-ea38962d211f)

**Comment by TimberOwl** [comment]
ill fix this as well thx
