### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] Passable terrain hosts tall rocks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#542]
## Observed behavior

Passable terrain hosts tall rocks.

## Expected behavior

Passable terrain has small rocks only.

## Screenshots

![shot_20231230_164423_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d0c2ffca-ce18-4574-b39a-8153a8cd3712)

![shot_20231230_164450_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/79f80a8e-ad5d-4c7a-98df-db730baf9f38)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
Rocks are a bit lower now, but still are relatively high.

![shot_20240118_204858_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ec9b93cd-8ffb-4ab3-8eec-31fe844801fa)

![shot_20240118_204926_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8160bc0b-9178-4bde-858c-487d7a2b8d94)

![shot_20240118_204944_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/beee1e14-6beb-4662-a3cd-1574ed316f93)

**Comment by xezon** [comment]
As designed.
