### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] Main Supply Dock is passable on one side, but not on the other side

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#543]
## Observed behavior

Main Supply Dock is passable on one side, but not on the other side.

## Expected behavior

Mirrored Supply Docks offer equal space for unit mobility.

### Passable

![shot_20231230_164607_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4aedb9d2-122b-4027-9401-48d488b0f91c)

### Impassable

![shot_20231230_164614_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8fd318f6-84b1-4626-8566-8466edede115)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
The new rocks put behind the Supply Dock float above terrain. Otherwise works.

![shot_20240118_205156_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6d142acb-2b75-4dc5-a98f-052a93170dbb)

**Comment by xezon** [comment]
Rocks look good now. I took a look at the new area of the new impassable terrain and it appears to be a bit overextended. On one side it is possible to drive close to mountains:

![shot_20240123_192232_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3e595993-3cee-46bd-b6fb-8c168b86ac28)

But on the other side there is quite a considerable gap between flat terrain and the actual mountain, indicating an over-extension of impassable terrain.

![shot_20240123_192244_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/57751af7-4813-412b-afec-120832ccf778)
