### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] Sand bags near impassable terrain are destructible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#544]
## Observed behavior

Sand bags near impassable terrain are destructible. It looks as if the space would become passable but it is not.

## Expected behavior

Sand bags cannot be destroyed.

## Screenshots

![shot_20231230_165058_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/553eee3d-a082-4525-9d18-97576adfc1a3)

![shot_20231230_165106_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/44a4397a-c147-44c7-9f84-f73ddf023b2f)

**Comment by toirehantaa** [comment]
fixed.
