### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] Rangers can be air dropped on impassable terrain at north east corner

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#545]
## Observed behavior

Rangers can be air dropped on impassable terrain at north east corner.

## Expected behavior

Rangers can not be air dropped on impassable terrain.

## Screenshots

![shot_20231230_165314_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/691f1cac-fc6d-4bf5-83c1-12eaf0d86744)

**Comment by toirehantaa** [comment]
same problem as on the other maps with ranger drops, everything is impassable already.

**Comment by xezon** [comment]
Original game bug. Cannot be fixed.
