### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] China AI will not build a Supply Center at right top spot

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#546]
## Observed behavior

China AI will not build a Supply Center at right top spot.

## Expected behavior

AI can build the full tech tree at all start positions.

## Screenshots

![shot_20231230_165649_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6f2face5-f523-44c7-ae94-b33d961bb78e)

**Comment by toirehantaa** [comment]
the Powerplant is hindered from being build because of the terrain around it. Would demote this from blocker as AI generally performs bad on maps that have teammates really close anyways

**Comment by xezon** [comment]
Actually AI starts building after 7 minutes or so. No way to workaround for sure? Bug is in scripts?

![shot_20240118_210319_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ab25c127-90aa-457b-952e-0d66ba71f24b)

**Comment by xezon** [comment]
Fixing this would require major map layout reword. Not worth it. AI ideally fixed with scb script.
