### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] Audio emitters have no easing and can crackle

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#547]
## Observed behavior

Audio emitters have no easing and can crackle.

## Expected behavior

Audio emitters have easing and do not crackle when scrolling over.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/883e778d-0aa6-4ede-96c4-d76d2a070cfb

**Comment by toirehantaa** [comment]
fixed.
