### ISSUE TITLE
[Candidate 2v2 Morning Dew ZH v7] Soldiers inside bunkers can damage themselves when firing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#548]
## Observed behavior

Soldiers inside bunkers can damage themselves when firing.

## Expected behavior

Soldiers inside bunkers do not damage themselves.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8b859d5f-834e-4be8-a2f6-bfed37873059

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/14266eec-ba1f-4f24-9aac-c3f3d1344ae0

**Comment by toirehantaa** [comment]
those bunkers made it a bit too bunkery in my opinion, so I removed them altogether
