### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Destroying each castle structure will stall the game for a few seconds

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#549]
## Observed behavior

Destroying each castle structure will stall the game for a few seconds.

## Expected behavior

Destroying castle structures does not stall the game or the structures cannot be destroyed.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/089b7ae0-b7a2-443e-9841-15a43eac00d2

**Comment by toirehantaa** [comment]
structures are meant to be indestructable, forgot to do so, now fixed

**Comment by xezon** [comment]
Can still be destroyed. And stalls.

![shot_20240118_202408_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/def16f1c-3a6c-47fa-9fdb-a13468ec0b0c)
