### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#550]
## Observed behavior

Audio emitters have no easing.

## Expected behavior

Audio emitters fade in and out smoothly when scrolling over the map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c213bdea-f3a8-49f2-8f2b-f622132e605d

**Comment by toirehantaa** [comment]
fixed
