### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Units can be air dropped on mountains

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#551]
## Observed behavior

Units can be air dropped on mountains.

## Expected behavior

Units can not be air dropped on mountains.

## Screenshots

![shot_20231230_173756_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b56821cc-d73f-41e5-a1cd-50986dc1f801)

![shot_20231230_173858_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4e600cca-4739-4582-a0ef-a9d75f465d86)

![shot_20231230_173948_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4def44fd-84f2-406d-a0f0-f17f7464db48)

**Comment by toirehantaa** [comment]
I'm starting to see the pattern that rangers seem to be dropped at places even though it is impassable. The Dozer one has been definitely fixed, however, I don't know what happens with these rangers. Same thing for Wastelands Dust
