### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Units can move around one of the castle houses, but not the others

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#552]
## Observed behavior

Units can move around one of the castle houses, but not the others.

## Expected behavior

Units can move around mirrored houses equally.

### Cannot move around (5)

![shot_20231230_175706_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/57c953d2-d2d9-47de-9dba-3826e7afcd7b)

![shot_20231230_175716_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0ac1316c-cbed-4c67-80f4-d642b70f9571)

![shot_20231230_175726_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2c52887b-a2d8-47f8-b542-c0dbd24c34da)

![shot_20231230_175739_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/059e1898-2e6c-43b7-bcec-304e5d924b6e)

![shot_20231230_175749_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/303b9714-97bb-4c43-b0e8-ac9efe75206e)

### Can move around (1)

![shot_20231230_175817_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e41be51-ed23-4afd-a1ba-4b52d7295b3d)

**Comment by toirehantaa** [comment]
fixed
