### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Supply Piles in map center do not offer equal building space

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#553]
## Observed behavior

Supply Piles in map center do not offer equal building space.

## Expected behavior

Supply Piles in map center offer equal building space for fair conditions.

### 1. Has good room

![shot_20231230_193541_58](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7b70df07-5478-485d-8799-8a8a0f045056)

### 2. Has no room

![shot_20231230_193553_59](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7cf8cbc6-fe1b-4496-8818-e2c50f31f087)

### 3. Has most room

![shot_20231230_193600_60](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/19922864-17f7-4d92-b12d-c7b7ad08cc29)

### 4. Has limited room

![shot_20231230_193610_61](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/46f4f5a8-fc27-4db9-8cf3-657f91821789)

### 5. Has limited room

![shot_20231230_193628_62](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/29476be7-bc29-4769-a4d9-dac32e189b3b)

### 6. Has limited room

![shot_20231230_193640_63](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/976c54e1-ee0d-4dad-8ee3-384e279c0b62)

**Comment by toirehantaa** [comment]
somewhat fixed, made it impossible to build directly at the tower.
Everyone has the ability to build a normal supply there though, should be fine as is

**Comment by xezon** [comment]
Position 3 is now consistent with 4,5,6.

Position 2 still has disadvantage.

Position 1 still has advantage.

**Comment by xezon** [comment]
Position 2 is now consistent with 3,4,5,6.

Position 1 still has room advantage.

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
Appears unchanged.

![shot_20240127_124124_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e710609f-ede0-4c3a-9013-835e77a41c37)

**Comment by toirehantaa** [comment]
still possible? having a look

**Comment by toirehantaa** [comment]
fixed
