### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Some castle structures are partly floating above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#554]
## Observed behavior

Some castle structures are partly floating above terrain.

## Expected behavior

Structures sit on terrain tightly.

## Screenshots

![shot_20231230_173054_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8bf9187f-fa9c-4f2b-83d8-1553e0f506d8)

![shot_20231230_173135_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fafae25c-deed-45ea-84ef-577397d62c51)

![shot_20231230_173150_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7595d322-ecbb-4f7c-bf4f-ee264f8abc49)

**Comment by toirehantaa** [comment]
fixing this would mean making the road float in return sadly, wont fix

**Comment by xezon** [comment]
As designed.
