### ISSUE TITLE
[Candidate 3v3 Medieval Era ZH v4] Mirrored Oil Derricks have different room for unit mobility

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#555]
## Observed behavior

Mirrored Oil Derricks have different room for unit mobility.

## Expected behavior

Mirrored Oil Derricks offer equal room for unit mobility

### Can be moved around

![shot_20231230_173333_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/05c76500-0485-4612-8c8e-830de212a9d2)

### Can not be moved around

![shot_20231230_173343_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/44f91ab4-8b2c-44ef-9f1d-716f55d013d1)

### Can be moved around

![shot_20231230_173355_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3c94fb9c-fc76-4d42-8fbe-8180494131bc)

### Can not be moved around

![shot_20231230_173405_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c533f503-7daa-4951-bd75-f55aed88e01c)

### Can not be moved around

![shot_20231230_173417_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/529ea41b-3bd8-4a4b-9463-7e03f16fc95a)

### Can be moved around

![shot_20231230_173434_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aeae9155-eda6-4bb9-8e0b-05df527a7334)

**Comment by toirehantaa** [comment]
fixed
