### ISSUE TITLE
[Candidate 4v4 Urban Downfall ZH v2] Structures are z clipping around the map

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#557]
## Observed behavior

Structures are z clipping around the map.

## Expected behavior

Structures are not z clipping.

## Screenshots

![shot_20231231_101204_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/41fb6f2d-82e0-439e-a9cf-5ddbae36cfae)

![shot_20231231_101256_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8c05b543-83be-4882-8757-0e8bd7b7b84d)

![shot_20231231_101315_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ca48103c-d682-4ba6-9b33-4f4411c59d96)

![shot_20231231_102906_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/37300d32-c1ec-4114-a0c3-a2a94b5799b3)

**Comment by xezon** [comment]
Some places still show z clipping:

![shot_20240120_130103_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8909990d-8687-434e-a8af-408a6ede0e20)

![shot_20240120_130125_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5f5442d8-5d23-46c8-8223-2f9be6a887e3)

![shot_20240120_130132_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8b244723-b70f-4e6d-8b91-e9e3a81b1372)

![shot_20240120_130153_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/856d3697-36b1-41a5-a376-17be619222dc)

![shot_20240120_130217_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5b2804ee-6f1d-4c2a-8b75-7d8414af09d3)

![shot_20240120_130243_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f8e57f58-d798-4d4b-bbfc-3988174a34df)

![shot_20240120_130251_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fe268e8c-2a54-4364-b5c3-8cc7eec18971)

![shot_20240120_130304_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6d95b77f-b9bf-4734-a4c5-d478402747df)

![shot_20240120_130317_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ccc412e1-58f4-4b1c-b4c3-2dea76d709b0)

![shot_20240120_130335_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6905733f-4e60-465e-9b2b-d81705b3862f)

![shot_20240120_130346_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/42104ef9-87c4-4c39-bd50-a82b6e1d06c1)

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
There still is clipping here, other than that looks good.

![shot_20240201_215643_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b5de64e9-2726-41f4-8b44-4e370630fe23)
