### ISSUE TITLE
[Candidate 4v4 Urban Downfall ZH v2] Some Oil Derricks are clipping into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#558]
## Observed behavior

3 of 4 Oil Derricks clip into terrain.

## Expected behavior

Oil Derricks do not clip into terrain.

## Screenshots

![shot_20231231_103122_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/22c44005-c8db-4cc1-a16f-27382f61c3d7)

![shot_20231231_103132_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7184dfd0-6df6-475b-8ebf-8041252d714d)

![shot_20231231_103140_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/be676828-2001-443a-917f-c24e749f353a)

![shot_20231231_103148_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b21c5ea8-3a5e-4ba9-8a4f-8209be5a3941)

**Comment by toirehantaa** [comment]
fixed
