### ISSUE TITLE
[Candidate 4v4 Urban Downfall ZH v2] Light at Oil Derrick is missing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#559]
## Observed behavior

Light at Oil Derrick is missing.

## Expected behavior

Each Oil Derrick is surrounded by 4 lights.

## Screenshots

![shot_20231231_103423_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d9662c9f-c897-4746-af42-73671d54e99a)

**Comment by toirehantaa** [comment]
fixed
well spotted actually
