### ISSUE TITLE
[Candidate 1v1 Combat-Island] Supply stashes are buried in terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#56]
**Issue Description**
Supply stashes are buried in terrain.

**Expected behavior**
Supply stashes have regular height on terrain like all other maps for consistent look.

**Screenshots**
![shot_20210321_130623_24](https://user-images.githubusercontent.com/4720891/111904427-4e8b5f80-8a47-11eb-9dc7-40138ffb0256.jpg)

**Comment by Jundiyy** [comment]
I think it's quite nice, quite a lot of newer maps have started doing this and it makes it look more interesting.

**Comment by xezon** [comment]
No problem.
