### ISSUE TITLE
[Candidate 4v4 Urban Downfall ZH v2] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#561]
## Observed behavior

Audio emitters have no easing. The transition is not good when scrolling over map.

## Expected behavior

Audio emitters ease in and out gracefully.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1bd83ee6-dff5-484b-b7a5-03de15e088e2

**Comment by toirehantaa** [comment]
fixed
