### ISSUE TITLE
[Candidate 4v4 Wastelands Dust ZH v4] Impassable terrain behind Supply Docks looks passable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#562]
## Observed behavior

Impassable terrain behind Supply Docks looks passable.

## Expected behavior

Impassable terrain behind Supply Docks does not look passable. The terrain elevation is higher. Or there are big rocks.

## Screenshots

![shot_20231231_111239_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6e0624c7-3b3d-4635-a7c5-3b081acb9dd0)

![shot_20231231_111322_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/af924639-0173-45be-8b00-f72469658165)

**Comment by toirehantaa** [comment]
Rocks put, fixed.
