### ISSUE TITLE
[Candidate 4v4 Wastelands Dust ZH v4] Ruins appear very dark when revealed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#564]
## Observed behavior

Ruins appear very dark when revealed.

## Expected behavior

Ruins look natural when revealed.

## Screenshots

![shot_20231231_111608_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d407dbee-8d7b-468e-82db-df1d149dd85b)

![shot_20231231_111613_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0828b65f-353b-4af9-9d44-371cac509c71)

![shot_20231231_111651_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6947be12-21ad-45ae-aa59-e1c4c3c6d917)

![shot_20231231_111655_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c228efa5-bbba-4937-a0b4-2d8a06a95cbf)

**Comment by toirehantaa** [comment]
fixed

**Comment by xezon** [comment]
There still is one thing that is darkened:

![shot_20240120_131807_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1147af05-3476-42fa-80a3-3dfa3d2aa968)

**Comment by xezon** [comment]
Is ok.
