### ISSUE TITLE
[Candidate 2v2 Purification ZH v4] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#566]
## Observed behavior

Audio emitters have no easing.

## Expected behavior

Audio emitters fade in and out gracefully when scrolling over the map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d558d7c2-ef42-423b-85d8-54e41f4760d7

**Comment by toirehantaa** [comment]
fixed.
