### ISSUE TITLE
[Candidate 2v2 Green Silk ZH v1] Units and Rangers can be air dropped on outer islands

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#569]
## Observed behavior

Units and Rangers can be air dropped on outer islands. The Dozer I managed to drop just once. Appears to be not straight forward to do.

## Expected behavior

Units and Rangers can not be air dropped on outer islands.

## Screenshots

![shot_20240101_095721_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/920cb056-e30f-4e3a-baad-efafa9d3ab7c)

![shot_20240101_095759_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5e645d25-39e1-4c8b-864f-0e56fb1aa7ab)

![shot_20240101_095844_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c1bd225d-5967-4a70-b4f5-242869675ed5)

![shot_20240101_095905_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/60d668be-bf20-44fb-80c7-279077f77d8c)

**Comment by Jundiyy** [comment]
[Green Silk ZH v1.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/15181309/Green.Silk.ZH.v1.zip)

Fixed this issue, along with #570 and #568.

**Comment by xezon** [comment]
Fixed
