### ISSUE TITLE
[Candidate 2v2 Green Silk ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#570]
## Observed behavior

Audio emitters have no easing and cut off badly when scrolling.

## Expected behavior

Audio emitters fade in and our gracefully when scrolling over map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a737b103-33d4-4f7c-94d7-617b4d79755d

**Comment by xezon** [comment]
To me it sounds like the sounds were made much quieter but the fundamental fade issue still exists.

**Comment by Jundiyy** [comment]
[Green Silk ZH v1.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/15280524/Green.Silk.ZH.v1.zip)
Hope this one is better. Think it's good. Covers #568 as well.

**Comment by xezon** [comment]
Sounds very good.
