### ISSUE TITLE
[Candidate 1v1 Sacred Land ZH v1] Map uses houses with broken fire ports

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#573]
## Observed behavior

Map uses houses with broken fire ports. Soldiers shoot from 0,0,0 and can damage the house they sit in.

## Expected behavior

Map uses houses with working fire ports. Or houses sit on flat terrain so that soldiers cannot damage themselves.

## 1

![shot_20240101_105023_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d8fa5bdf-ecc9-407d-86fc-60a35c414b07)

## 2

![shot_20240101_105046_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cd46ac72-3d4f-4282-9cce-d419027e3d4a)

## 3

![shot_20240101_105212_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3f059c74-5831-48c7-b6c0-17afada4e57a)

## 4

![shot_20240101_105222_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/00003122-8227-4e67-ac5a-a5ed4fd65cde)

## 5

![shot_20240101_105235_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d002062e-8b1e-4667-b034-6d3070daa85d)

## 6

![shot_20240101_105243_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dc1a214c-6135-4326-8ee5-b93c7037554f)

## 7

![shot_20240101_105257_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e61da650-df09-46a1-922f-227ed27d7671)

**Comment by Jundiyy** [comment]
[Sacred Land ZH v1.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/15280509/Sacred.Land.ZH.v1.zip)
Also fixed #574 and #572 
I noticed something new, it's not always to do with the terrain below the building, but also the terrain height it shoots at.

**Comment by xezon** [comment]
Houses 2, 3, 5, 6 still can self destruct.

**Comment by Jundiyy** [comment]
Surprised, which way did you shoot to make it happen, I tested them many times.

**Comment by xezon** [comment]
I always test by shooting in a full circle.

**Comment by xezon** [comment]
Houses 2, 3 removed.
Houses 5, 6 fixed.
