### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] Terrain artifacts are located in south west water

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#581]
## Observed behavior

Terrain artifacts are located in south west water.

## Expected behavior

There are no terrain artifacts in the water.

## Screenshots

![shot_20240101_120916_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/24033fbd-9010-43e5-9b3b-6455f845f9a8)

**Comment by ReLaX82** [comment]
Please double check in new version before publishing it.

**Comment by xezon** [comment]
What new version? This is the version you sent me.

**Comment by ReLaX82** [comment]
Next version I will publish with all changes in regard to this map.

**Comment by ReLaX82** [comment]
[Additional Forces ZH v1.zip](https://github.com/TheSuperHackers/GeneralsRankedMaps/files/14075316/Additional.Forces.ZH.v1.zip)

Here is the new version.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
