### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] There is a "R" imprint in the center

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#583]
## Observed behavior

There is a "R" imprint in the center. It looks strange.

## Expected behavior

There is no "R" imprint in terrain.

## Screenshots

![shot_20240101_121227_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/884353cb-8ef0-4fcd-845d-2cdee174b488)

**Comment by ReLaX82** [comment]
If I remember correctly there has been a map with an E for EXCAL.
This design is a pretty old map and wanted to imprint my first letter of my nickname.
I will keep that one.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
