### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] Map name does not fit official map naming style

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#584]
## Observed behavior

Map name is not good. "Additional Forces" does not fit original map name style and does not describe a place.

## Expected behavior

Map name describes map location.

**Comment by xezon** [comment]
I suspect "Additional Forces" was picked to describe the 8 Reinforcement Pads.

Perhaps call it

* Reinforced Coast
* Reinforced Island
* Reinforcement Bay

**Comment by ReLaX82** [comment]
You are right with your approach.
As there are 8 Reinforcement Pads I tend to Reinforcement Bay or The Reinforcement Bay if you don't mind.

ReLaX

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
