### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] Towers in center are not equally damaged

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#585]
## Observed behavior

Towers in center are not equally damaged.

## Expected behavior

Towers in center are equally damaged for fairness.

### Undamaged (1)

![shot_20240101_121314_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/48caf8b1-8af8-491a-bb13-090ac96d4102)

### Damaged (2)

![shot_20240101_121319_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9f21c66a-af2d-42f0-b835-60386884bb2e)

![shot_20240101_121324_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a67af82d-d23d-4ee7-bd16-29998a2d0183)

**Comment by ReLaX82** [comment]
Thanks for the hint, v2 has all towers at 50% now.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
