### ISSUE TITLE
 [Candidate 1v1 Additional Forces ZH v1] Tech Buildings use custom rotation that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#586]
## Observed behavior

Tech Buildings use custom rotation that make their flag less visible.

## Expected behavior

Tech Buildings use rotations that make their flag highly visible.

## Screenshots

![shot_20240101_121455_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0467f826-cbac-4a4f-9130-33926d56369a)

![shot_20240101_121505_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/437de299-bc83-4f2a-89a6-f94d05e203a2)

**Comment by ReLaX82** [comment]
As this is no blocker, I see this as a design hint and therefore won't change.
Most maps have lots of custom rotations and those are required to keep up with the inititial map idea/design.
The player can also rotate in game.

**Comment by xezon** [comment]
All Official Maps use high visibility flag rotations, fyi.

**Comment by ReLaX82** [comment]
Official, yes.

I sometimes think you don't like diversity Xezon.

I would like to keep it as is.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
