### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] Top left and bottom right corners have industrial sound which does not fit the visual setting

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#587]
## Observed behavior

Top left and bottom right corners have industrial sound which does not fit the visual setting. Top right and bottom left sound ok.

## Expected behavior

Map uses tropical and farm like sounds that match the setting.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4ef5c91d-d062-4e8f-8df7-24a88a80fcc0

**Comment by ReLaX82** [comment]
Simply deleted those, thx.

We copies from somewhere I suppose.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
