### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#588]
## Observed behavior

Audio emitters have no easing.

## Expected behavior

Audio emitters fade in and out smoothly when scrolling over the map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7fd4571c-9409-4e2e-84d6-7cc013236dc6

**Comment by ReLaX82** [comment]
I have adapted sound customized volume and range just a bit and feels better.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
