### ISSUE TITLE
[Candidate 1v1 Canyon Frost ZH v1] Map is a copy of Canyon of the Dead

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#591]
## Observed behavior

Canyon Frost is a copy of Canyon of the Dead. There appear to be no major differences between these 2, other than some minor ones like repositioned main Supply Dock, more space around secondary Supply Dock, repositioned houses in villages, repositioned Tech Buildings, minor changes in ramps.

If I am not mistaken this exact map was already dropped in 2021.

See https://github.com/TheSuperHackers/GeneralsRankedMaps/commit/2f7f82a892e57d3308851ce6a18a9914d5e65e1e

> Rejected by Rising

Why is a winter version needed again?

## Expected behavior

Ranked Maps have unique designs. Maps do not come in duplicated desert, gras, snow variants, because that would bloat the map selection unnecessarily.

**Comment by NoMerciBKK** [comment]
i dont think its needed

**Comment by ReLaX82** [comment]
I improoved Canyon of the Dead years ago and think if that one has major issue, we shall work on them without creating another same map.

**Comment by FiReArM-ZH** [comment]
Message from MP3:

The map was done based on someone's request which included making minor changes on it, hence a large amount of similarities between original Canyon & Frost edition remaining. The entire list of changes are the following:
* Improved visuals/Winter Setting; The lightning became brighter.
* Cars were removed entirely off the map!
* The middle path is now wider, and is on the same ground level as player bases.
* The amount of buildings, on the top and bottom, sides of the map have been shortened down to 4. (Previously there were 10) 
* Each building is important for the taking, as each structure covers up the tiny path(s) that is leading towards the 2nd supply, in the form of piles.
* Command Center positions are now further away from the starting supply dock; China should no longer experience a space-limitation whenever placing down a power near by.
* Overall map-terrain is now smoother.
* Reinforcement Pads were swapped with Repair Bays
Other than that, visuals remained mostly the same

**Comment by FiReArM-ZH** [comment]
Although both are similar, in my personal opinion, this can be ranked as this provides much better gameplay than the canyon of the dead and canyon of the dead can be removed from auto download.
