### ISSUE TITLE
[Candidate 1v1 Battleship Bay ZH v1] Units can move through floodable Supply Piles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#592]
## Observed behavior

Units can move through floodable Supply Piles.

## Expected behavior

Units can not move through floodable Supply Piles

## Screenshots

![shot_20240101_164748_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8dec61f8-b383-4a5e-8d18-991106e538f1)

**Comment by DoMiNaToRuk2** [comment]
not blocker so wont be fixed, seems to be game engine anyway due to flooding this area later

**Comment by toirehantaa** [comment]
Explanation: The unit (Crate here) is inside of the water initially, so it's hitbox seems to be removed. having impassable terrain beneath would fixi it, however, if the crates were to run out of capacity and disappear, the impassable terrain would still be there. There is no way to get the hitbox back here, so not able to fix.

**Comment by xezon** [comment]
Cannot fix properly, closing.
