### ISSUE TITLE
[Candidate 1v1 Battleship Bay ZH v1] Mirrored house near Battleship has 2 less slots on one side

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#593]
## Observed behavior

Mirrored house near Battleship has 2 less slots on one side.

## Expected behavior

Mirrored houses have equal amount of slots for fairness.

## Screenshots

![shot_20240101_165525_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b44b3500-510f-42c0-a512-dbbdf38e9db9)

![shot_20240101_165536_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/56cfb460-ecc1-48ff-ba53-9ab2f5af5e31)

**Comment by DoMiNaToRuk2** [comment]
tried changing the house but as the textures have already been done under and to the side of it, its quite a mission to re-do it all. As its minor, leaving this.

**Comment by toirehantaa** [comment]
fixed.
