### ISSUE TITLE
[Candidate 1v1 Battleship Bay ZH v1] Performance drops by around 60% while water rises after dam break

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#594]
## Observed behavior

Performance drops by around 60% while water rises after dam break.

## Expected behavior

Performance is stable during water rise.

## Screenshots

![shot_20240101_165615_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/77f0f9a6-4d50-477f-af65-5602cd2ed9b8)

![shot_20240101_165625_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b2521c1c-08a2-4265-b077-36c5f9eb0201)

**Comment by DoMiNaToRuk2** [comment]
no complaints during excal tournament so leaving it

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
Performance is very good now.
