### ISSUE TITLE
[Candidate 1v1 Battleship Bay ZH v1] Crane at top right spot blocks build space near Supply Dock

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#595]
## Observed behavior

Crane at top right spot blocks build space near Supply Dock.

## Expected behavior

Both players have equal building space near their respective Supply Dock.

## Screenshots

![shot_20240101_170027_51](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/77ba1c11-6e95-4a81-a096-fb8eff805c37)

![shot_20240101_170038_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d5fc810f-74a4-412f-af6d-d362a063c0ad)

**Comment by DoMiNaToRuk2** [comment]
fixed

**Comment by toirehantaa** [comment]
removed the cranes. fixed.

**Comment by xezon** [comment]
Is better, BUT at the top the space is tighter than at the bottom, so it is not possible to build identically with right distance for optimal truck collection:

### Bottom is good, trucks collect optimal

![shot_20240323_121714_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d72dcf82-5a0c-4de6-bf82-66bc88a987c5)

### Top is not so good, trucks need to drive back and forth

![shot_20240323_121726_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/743abd74-839d-43c6-934f-d6b72ca5cce7)

**Comment by NoMerciBKK** [comment]
> Is better, BUT at the top the space is tighter than at the bottom, so it is not possible to build identically with right distance for optimal truck collection:
> 
> ### Bottom is good, trucks collect optimal
> ![shot_20240323_121714_2](https://private-user-images.githubusercontent.com/4720891/316237404-d72dcf82-5a0c-4de6-bf82-66bc88a987c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjIyNTMsIm5iZiI6MTcxODcyMTk1MywicGF0aCI6Ii80NzIwODkxLzMxNjIzNzQwNC1kNzJkY2Y4Mi01YTBjLTRkZTYtYmY4Mi02NmJjODhhOTg3YzUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTQ0NTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWIxNGI3YmI4NzYyY2QzYmE2NDFlNDMzMDQxYzFiYjZmNzAxMTIzOTg1ZmFlZjJhMjNiYmFmZDQ5YzU1ODFlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VZ-O0uK_HamYV8NLmiF3ZhYz0FSH4ZYNwZWSS2gR65w)
> 
> ### Top is not so good, trucks need to drive back and forth
> ![shot_20240323_121726_3](https://private-user-images.githubusercontent.com/4720891/316237406-743abd74-839d-43c6-934f-d6b72ca5cce7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjIyNTMsIm5iZiI6MTcxODcyMTk1MywicGF0aCI6Ii80NzIwODkxLzMxNjIzNzQwNi03NDNhYmQ3NC04MzlkLTQzYzYtOTM0Zi1kNmI3MmNhNWNjZTcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTQ0NTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ4ZGY5Y2RhYmU0NTVkZGU0YjE0NWI0ZWUwZDllMWJmZWZiODRiOWM1ZDcxZjFkN2Q2NTNlMjZlMTQ5MDQ0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iQAVqgStvQxC0gDnoNbIJZsgvxHQ-5XTvshds3U_beo)

this is gameengine based with the supplys getting collected, pref on this one side over all other sides cause this is the "main" side of the supply to be collected from 

I think radar already reported this issue on an other map per pm to you @xezon 
I hope it makes sence what i tried to explaine :D

**Comment by xezon** [comment]
I think the issue is that the top has less build space because of these shipping containers. Supply Center must be built closer, which is bad for trucks.

**Comment by NoMerciBKK** [comment]
updated ans fixed

**Comment by xezon** [comment]
Fixed

![shot_20240621_194913_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/692f5107-1d48-4406-80a0-0c6c87476c05)
