### ISSUE TITLE
[Candidate 1v1 Battleship Bay ZH v1] Tree is placed in house

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#596]
## Observed behavior

Tree is placed in house.

## Expected behavior

Tree is not placed in house.

## Screenshots

![shot_20240101_170153_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3439dde5-c778-463d-8229-4faf4d7aebb5)

**Comment by DoMiNaToRuk2** [comment]
tree removed
