### ISSUE TITLE
[Candidate 1v1 Storm Surge ZH v1] Oil Refinery has custom rotation that makes it flag less visible than necessary

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#597]
## Observed behavior

Oil Refinery has custom rotation that makes it flag less visible than necessary.

## Expected behavior

Oil Refinery has custom rotation that makes it flag highly visible.

## Screenshots

![shot_20240101_175526_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/02c7448a-e630-4549-b1fe-0fdc7a3bc3d4)

**Comment by DoMiNaToRuk2** [comment]
fixed

**Comment by cncHD** [comment]
This was not fixed. I fixed it now
![bottom](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79742408/de3b4b2e-f97d-4501-a9b7-8fafd5ea0a8d)
