### ISSUE TITLE
[Candidate 1v1 Storm Surge ZH v1] Supply Docks near dams do not offer equal build space

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#598]
## Observed behavior

Supply Docks near dams do not offer equal build space.

## Expected behavior

Supply Docks near dams offer equal build space for fairness.

### Can not build

![shot_20240101_182822_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/578daff5-2af7-41fa-883d-36458d95bf6f)

### Can build

![shot_20240101_182834_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/88c3829b-590f-4113-8364-9bd5a23295f8)

**Comment by DoMiNaToRuk2** [comment]
fixed

**Comment by cncHD** [comment]
Ths was not fixed. I fixed it now. Question is: Are the rocks on the buildings a problem or not? Its no problem to remove them, but I would rather not as it hurts the optic. If seen as an issue I can remove the rocks on the buildings
![bottom](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79742408/b0bbc4c9-58d0-4184-ade2-c55d243497c6)

**Comment by xezon** [comment]
I think Dominator just commented "fixed" but never actually sent a fixed version. So ignore these. If a report is open, it is considered valid.

**Comment by xezon** [comment]
Big rocks must not clip into buildable space. Move or remove them if space is meant to be buildable.
