### ISSUE TITLE
[Candidate 1v1 Storm Surge ZH v1] Building a Supply Center at the bottom Supply Dock is a bit more difficult than at the top

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#599]
## Observed behavior

Building a Supply Center at the bottom Supply Dock is a bit more difficult than at the top.  It is possible with a bit more trying, but not as easy as it is at the top.

## Expected behavior

Building a Supply Center at the bottom Supply Dock is as easy as it is at the top.

### Less room to build

![shot_20240101_182955_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b5ca1c2c-ca4e-4f0a-9b51-0a68f2d198b2)

### More room to build

![shot_20240101_183002_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4e53279e-f7f7-433a-8307-84cf5b88950f)

**Comment by DoMiNaToRuk2** [comment]
fixed by smoothing

**Comment by cncHD** [comment]
Can confirm its fixed as per Dominators post. I played around with both spots and gave the bottom spot more space by moving the supply dock and player spot a bit up.
It is super simple to build a supply center on the bottom now. Top spot still has way more space, but that should be no issue. If it is, the top spot can be made a bit smaller by adding more water to it

I would call this fixed
