### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] Units can be air dropped at invalid places

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#614]
## Observed behavior

Units can be air dropped at invalid places.

## Expected behavior

Units can not be air dropped at invalid places.

## Screenshots

![shot_20240104_183100_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8e4061e0-1d42-482c-8064-cf7e0363c790)

![shot_20240104_183136_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd8bd3e6-b0b4-44c4-825f-90e315830137)

![shot_20240104_183158_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7b8caba1-b8ad-418f-b70a-e0f390511cc9)

![shot_20240104_183212_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9bcccdab-23cd-4aec-b13e-22f0428c10e9)

**Comment by toirehantaa** [comment]
fixed. Just the ranger problem as always will probably still reside

**Comment by xezon** [comment]
Vehicle drop fixed.
