### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] Oil Derricks near player spots offer unequal unit mobility opportunities

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#615]
## Observed behavior

Oil Derricks near player spots offer unequal unit mobility opportunities.

## Expected behavior

Oil Derricks near player spots offer equal unit mobility opportunities.

### Unit cannot drive through gap (1)

![shot_20240104_183434_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ff221d2c-fd89-4427-b334-c15d1210723c)

### Unit can drive through gap (7)

![shot_20240104_183459_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f7825d89-1245-4129-a04a-9fc9bfcee845)

![shot_20240104_183508_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd38cb09-b002-438c-82b2-d9c4157299da)

![shot_20240104_183517_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e5a83817-e64c-46ea-a606-292129a69586)

![shot_20240104_183526_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6c9cbd94-be4e-4904-81c0-b7d6c615ab0f)

![shot_20240104_183533_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9ea90774-412e-4e02-a1f9-942acc446216)

![shot_20240104_183540_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f7cecdf-fb20-4ec3-ba2d-8b252f53ab95)

![shot_20240104_183547_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bce3dffc-023b-4205-b6bf-27d827561a1d)

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
The gaps to Supply Dock are now uniform. But the rotation and positions of the Supply Docks have changed which creates a new problem. It now needs to be retested for Supply build space. China Supply build space is not equal. GLA build space I have not tested. Please check.

![shot_20240426_194910_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7ff96066-9811-4736-a1e5-c1649a8d6807)

![shot_20240426_194923_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7855eea7-a69a-4ee7-b490-25cfd91bb29f)

![shot_20240426_194937_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/81afe8ad-ed6d-45e1-a2e2-56975180d67d)

![shot_20240426_194946_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d6b7f05f-a937-4f49-8080-bf16cb910ee0)

![shot_20240426_194956_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a9fb2fb6-8a00-425e-a3dd-7abec18ead2b)

![shot_20240426_195008_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/289b018d-d596-41af-9992-85421a2848f1)

![shot_20240426_195018_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7063b311-46db-4326-9b2d-635b7fe6b875)

![shot_20240426_195026_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f4e0aa65-def0-461c-854c-cae1b4f991e6)
