### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] Some Oil Derricks use custom rotations that make their flag less visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#616]
## Observed behavior

Some Oil Derricks use custom rotations that make their flag less visible.

## Expected behavior

All Oil Derricks use custom rotations that make their flag highly visible.

### Flag would be more visible when rotated 90 degrees clock wise.

![shot_20240104_183651_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ea4af84c-c0cb-463d-b218-83c015e3a2ef)

**Comment by toirehantaa** [comment]
fixed.
