### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] East Tower is not properly centered in front of structure

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#617]
## Observed behavior

East Tower is not properly centered in front of structure.

## Expected behavior

East Tower is centered in front of structure like the other sides.

### Tower is not well centered (1)

![shot_20240104_183813_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1531fcd6-0be7-49de-8b2f-b8963e867c1d)

### Tower is centered better (3)

![shot_20240104_183919_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a170d949-959f-4df8-974f-bb4a8def16a9)

![shot_20240104_183945_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d3f388d4-2d3f-4b94-9058-8577ae92cc86)

![shot_20240104_184008_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5bb2df29-ac2e-42ab-8b12-d7433c7b993c)

**Comment by toirehantaa** [comment]
fixed
