### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] Intro title stays longer than 8 seconds

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#621]
## Observed behavior

Intro title stays longer than 8 seconds.

## Expected behavior

Intro title disappears at 8 seconds.

## Screenshots

![shot_20240104_190100_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cc873df2-5620-4fc4-87df-ffd0eee6cf87)

**Comment by toirehantaa** [comment]
fixed
