### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] Bunkers on ramps have different distances in relation to Oil Derrick, Oil Refinery and ramp

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#622]
## Observed behavior

Bunkers on ramps have different distances in relation to Oil Derrick, Oil Refinery and ramp.

## Expected behavior

Bunkers on ramps have identical distances in relation to Oil Derrick, Oil Refinery and ramp.

## Screenshots

![shot_20240104_185523_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/111a4bf5-5451-42c5-b53d-efc372e194c1)

![shot_20240104_185531_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3af9ee1a-701a-4b72-9a99-fafae881a140)

![shot_20240104_185542_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e4bbd43f-894d-4256-b7f0-9395396353b8)

![shot_20240104_185611_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/63650ead-1fc5-4654-8f4e-2e4e37c7c3cc)

**Comment by toirehantaa** [comment]
fixed
