### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] 2 soldiers walk down the ramp after evacuating elevated bunkers

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#624]
## Observed behavior

2 soldiers walk down the ramp after evacuating elevated bunkers. Happens on all 4 elevated bunkers.

## Expected behavior

Soldiers do not walk down the ramp after evacuating elevated bunkers.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/658a9eb4-f187-485f-9141-d47770338a40

**Comment by toirehantaa** [comment]
fixed.
