### ISSUE TITLE
[Candidate 4v4 Lost Cause ZH v4] Infantry cannot enter 2 elevated bunkers from ramp

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#625]
## Observed behavior

Infantry cannot enter 2 elevated bunkers from ramp. It can enter the other 2 elevated bunkers from the ramp. Tested from all directions.

## Expected behavior

Infantry can enter all elevated bunkers from ramps.

### Soldiers will not enter bunker from ramp (2)

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e1728e3a-1405-44d8-82d8-f391959d48d3

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bdc2add2-f3a3-4ada-9ace-bfd293b7b12d

### Soldiers will enter bunker from ramp (2)

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c561e279-b2e4-40ce-9d8e-fc326aeb513e

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ceb4b9fa-85d0-4f45-96b8-a095518ce61f

**Comment by toirehantaa** [comment]
fixed.

**Comment by xezon** [comment]
Fixed
