### ISSUE TITLE
[Candidate 3v3 Mojave Desert ZH v1] Soldiers in tents can destroy themselves

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#626]
## Observed behavior

Soldiers in tents can destroy themselves. Rockets spawn from 0,0,0 and hit the terrain.

## Expected behavior

Tents sit on flat terrain to reduce the chances of self damage.

## Soldiers in tent damage tent when shooting north

![shot_20240117_193155_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ba935e1f-127b-4dac-9afe-0c2e99fc7a52)

## Soldiers in tent damage tent when shooting north

![shot_20240117_193228_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0210d913-31b4-4cbc-8a04-741dfa07e8cd)

## Soldiers in tent damage tent when shooting south west

![shot_20240117_193302_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/59b2041f-d0d8-4ac8-8681-1a1ad303ea73)

**Comment by NoMerciBKK** [comment]
fixed
