### ISSUE TITLE
[Candidate 1v1 Bozic Destruction ZH v6] Tech Buildings in the north are positioned closer together than in the south

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#629]
## Observed behavior

Tech Buildings in the north are positioned closer together than in the south. This allows point attacks to apply more damage to both buildings at the same time.

## Expected behavior

Mirrored Tech Buildings have equal distance to each other for fair conditions.

### 5 GLA Terrors take down 2 Tech Buildings

![shot_20240121_145401_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5ad70809-222e-493e-8e64-2eb59be62488)

![shot_20240121_145414_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d06f8ffd-a184-48d0-a38f-b252ba2bcaeb)

### 5 GLA Terrors do not take down 2 Tech Buildings

![shot_20240121_145442_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7a02395a-fb7d-4b8c-ade3-a6f3fe49fd1c)

**Comment by NoMerciBKK** [comment]
updated
