### ISSUE TITLE
[Candidate 1v1 Hanamura Temple ZH v1] Temples and walls show as point of interest on minimap

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#630]
## Observed behavior

Temples and walls show as point of interest on minimap.

## Expected behavior

Temples and walls do not show as point of interest on minimap. They cannot be interacted with.

## Screenshots

![shot_20240121_171642_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ecaa74f3-7e1b-4ca5-87db-039da15ad1b2)

**Comment by TimberOwl** [comment]
fixed
