### ISSUE TITLE
[Candidate 2v2 Oil Carnage ZH v1] USA Rangers can be dropped behind Oil Derricks and may be unable to move, capture, be killed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#632]
## Observed behavior

USA Rangers can be dropped behind Oil Derricks and may be unable to move, capture, be killed.

## Expected behavior

USA Rangers
* can not be exclusively dropped behind Oil Derricks
* or any unit can move behind Oil Derricks
* or Rangers can reliably move, capture and be killed when dropped behind Oil Derricks

## Videos

Dropped Ranger cannot walk to Oil Derrick. Can capture when dropped close. Can eventually be killed. Cannot move out of the trap zone.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b154b890-a76f-408b-84cc-a348b52875c3

Dropped Ranger can walk to Oil Derrick. Can capture when dropped afar. Can eventually not be killed. Cannot move out of the trap zone.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a323bf1a-d8a0-4bc6-a377-726ba27958d2

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Rocks were put behind Oil Derricks. But it is still possible to drop Rangers behind.

I will reject the new edit.

![shot_20240514_180925_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bd89883d-4953-40bb-90fe-8e96a0002efb)

![shot_20240514_181027_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/85e4064c-5e8c-4a1a-9f0d-58d6ff17f317)

**Comment by xezon** [comment]
I was unable to drop soldiers at the top behind the Oil Derrick. But at the bottom it was still possible. However, unit was able to attack and kill it when it stood behind.

Appears to be no gameplay concern anymore.

![shot_20240613_185758_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f8af2683-59ad-41b5-ae1b-90a78bc96e5d)
