### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Tech Buildings in south west corner have less distance between them than in north east corner

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#633]
## Observed behavior

Tech Buildings in south west corner have less distance between them than in north east corner. This allows point damage attacks to apply more damage to the buildings.

## Expected behavior

Mirrored Tech Buildings have identical distance to each other for fair conditions.

### 5 Terrors kill 2 Tech buildings

![shot_20240127_143825_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ece22a09-2bbc-4b9a-b9af-5539fb9b6757)

![shot_20240127_143833_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3ed6b10c-a5ee-48bb-b523-3948d4e7749e)

### 5 Terrors do not kill 2 Tech buildings

![shot_20240127_143853_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b295ec8f-3872-41cd-a571-a3a83076b55b)

![shot_20240127_143900_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3f5c8ca8-0b60-4d6f-8f0e-4e9c97fd2c3b)

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
Change looks odd. It means player can no longer build supply there on one side.

![shot_20240323_140548_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1ad1fb82-2f5a-4735-81ae-aae9d2e1a173)

![shot_20240323_140600_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/15fadf4b-9aa1-4b4f-a211-84e3822da639)

**Comment by TimberOwl** [comment]
oh right ill fix it

**Comment by xezon** [comment]
Appears to be fixed.

Left side Tech Buildings still look to be bundled closer than right side Tech Buildings, but I was not able to kill Oil Derrick + Oil Refinery with 5 Terrorists at both sides.
