### ISSUE TITLE
[Candidate 2v2 Freezing Bursa ZH v1] Ground units and air units cannot move close to map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#634]
## Observed behavior

Ground units and air units cannot move close to map border. Especially for Chinooks, Helix this is not good, because they will have troubles dropping units into precise space behind the base Tech Buildings.

## Expected behavior

Units can move closer to the map border for comfortable plays.

### Is impassable for Aircraft

![shot_20240127_141342_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/20d83a2c-b393-4394-b236-401e2f8bc749)

![shot_20240127_141352_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/edcffbf7-0f7a-4c1b-9bf3-6f1f3b4afda3)

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5411a2a6-faa4-4aed-aebc-2a9a50c5ee3d

**Comment by TimberOwl** [comment]
fixed

**Comment by xezon** [comment]
With new map version provided:

South west: Unit can no longer pass Oil Refinery at the bottom edge, but can at the left edge.
North east: Unit can no longer pass Oil Refinery at either side. Inconsistent!

I suspect the intent was to make it not passable. But its bad, because it is inconsistent now and is not visually obvious. There would need to be mountains or rocks to make it obvious.

Btw I just found it is possible to move Chinook closer to map edges by using waypoints (ALT key) 👀 

The new map edit is a definite regression over the previous version. I will reject it. And I will close this report because waypoint trick works.
