### ISSUE TITLE
[Candidate 1v1 Additional Forces ZH v1] Should this map be ranked?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#635]
NoMerciBKK has raised that "Additional Forces ZH v1" map layout is similar to "Endboss ZH V2", which is also a Ranked Maps candidate. Ideally we do not push 2 similar maps.

Plus the large amount of Reinforcement Pads on "Additional Forces ZH v1" can be considered imbalanced, because Infantry General gets the most valuable drops.

Move "Additional Forces ZH v1" to backlog in favor of "Endboss" ?

## Top Additional Forces, bottom Endboss

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2ecf78ba-79e9-48d6-9d9b-c412c9256cab)

**Comment by ReLaX82** [comment]
I am hearing End Boss for the first time.

I consider this a quite good map to be fair.

Also a variation of tech buildings is always welcome even if its favouring one faction.

**Comment by NoMerciBKK** [comment]
> Also a variation of tech buildings is always welcome even if its favouring one faction.

Yes i do agree, but have you ever seen a repairpad on ranked maps? No cause ppl think its a drop zone, also you wont see many reinforcement pads cause they make the whole game inbalanced. And about the "Endboss" map its defenitly a coppy of your map but way better in balance. So if we take one of those maps in id prefer to take the better balanced version. But i m not a pro-player maybe we get some feedback from persons who will play the maps in the future.

> BTW: Imminent Victory is a pure copy from Natural Threats.

About Imminent Victory thats 3 years ago its not easy to get ridd of a published map.

**Comment by ReLaX82** [comment]
Your choice in the end.

What I can tell its a symmetrical maps with a few more tech buildings.

If that is worrying you, fine.

Liquid Gold has also more tech buildings and is or was played a lot.

**Comment by xezon** [comment]
Additional Forces ZH v1, quasi duplicate of Endboss. Moving to backlog.
