### ISSUE TITLE
[Candidate 1v1 Battleship Bay ZH v1] Unusable houses and boats show on Radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#637]
## Observed behavior

Unusable houses and boats show on Radar.

## Expected behavior

Unusable houses and boats do not show on Radar.

## Screenshots

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1fb8ea5e-4da9-4054-98d2-31751291a52a)

**Comment by toirehantaa** [comment]
fixed.
