### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Units cannot drive around south west Supply Piles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#642]
## Observed behavior

Units cannot drive around south west Supply Piles

## Expected behavior

Units can drive around south west Supply Piles.

## Screenshots

![shot_20240203_195324_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/973922e3-9bee-4d27-99ac-201c32a79048)

![shot_20240203_195441_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/342c19da-74aa-4535-8196-e347c8e70e0a)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by cncHD** [comment]
Fixed it
