### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Units cannot drive around north center Supply Dock

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#643]
## Observed behavior

Units cannot drive around north center Supply Dock.

## Expected behavior

Mirrored Supply Docks offer equal opportunities for unit mobility.

## Screenshots

![shot_20240203_195503_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/754e9487-a2df-4431-a5ba-45e9e6308ec9)

![shot_20240203_195448_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/27ea55e8-1b02-41c2-96bd-1fc223a6c016)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by cncHD** [comment]
![issue](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/79742408/4248319d-58df-43f9-99d9-4a2e93cfbb19)

[Comment by the map creator - cncHD]
The movement of the technical behind the supply does not make me happy. It moves in weird circles around the supply. I will fix it.

**Comment by xezon** [comment]
Note that you cannot touch the map right now because NoMerciBKK already did/does.

**Comment by cncHD** [comment]
NoMerciBKK did send me the latest version of the map yesterday. I will take the fixing of this map over from here because I also want to change some other things like visuals which are still untouched and do not look good at some parts of the map

**Comment by cncHD** [comment]
Fixed it
