### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Units cannot drive around north center Supply Piles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#644]
## Observed behavior

Units cannot drive around north center Supply Piles.

## Expected behavior

Mirrored Supply Docks offer equal opportunities for unit mobility.

## Screenshots

![shot_20240203_195515_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/47252e6e-10f8-4fb4-abc7-45dcb6c18485)

![shot_20240203_195524_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d138c57d-3a72-4445-90bf-eb6ee79082ba)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by cncHD** [comment]
Fixed it
