### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Flags are hidden behind Artillery Platforms

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#647]
## Observed behavior

Flags are hidden behind Artillery Platforms.

## Expected behavior

Flags are highly visible on all Tech Buildings.

## Screenshots

![shot_20240203_195748_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/57862ad8-d4f5-4343-abeb-8337b627d0eb)

![shot_20240203_195753_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/61ec0957-8285-49c4-9741-743e5432b5f4)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by cncHD** [comment]
All artillery platforms have the same angle now. Fixed

**Comment by xezon** [comment]
It is a bit better, but the flags are not perfectly viewable. The flag would be much better to see when rotated by 90 degrees counter-clock-wise.

![shot_20240521_212128_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5d5ce3e5-e0d0-417b-918d-470555f53b28)

**Comment by cncHD** [comment]
fixed
