### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Oil Derrick clips into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#648]
## Observed behavior

Oil Derrick clips into terrain.

## Expected behavior

Oil Derrick sits on flat terrain.

## Screenshots

![shot_20240203_195822_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d87c0330-8642-41ca-b4d3-058b7dc7efac)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by cncHD** [comment]
reviewed and fixed
