### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Artillery Platforms float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#649]
## Observed behavior

Artillery Platforms float above terrain.

## Expected behavior

Artillery Platforms sit tight on terrain.

## Screenshots

![shot_20240203_195650_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/078a4a93-7d4a-4972-9ae7-d1e8f64dc041)

![shot_20240203_195700_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bb0c760b-ee07-45ef-a2da-3ecea823b4ea)

![shot_20240203_195714_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a7cfbe94-042d-46af-8d3d-3a569ed4c763)

![shot_20240203_195730_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/03f6e122-3bce-40c4-959c-945bb929d594)

**Comment by NoMerciBKK** [comment]
fixed
