### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Not all soldiers inside huts can shoot in all directions

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#650]
## Observed behavior

Not all soldiers inside huts can shoot in all directions.
At least not when force firing the terrain.

## Expected behavior

Soldiers can comfortably shoot in all directions inside all huts.

### All soldiers are firing

![shot_20240203_200459_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/84007702-b5b1-41d3-811b-9e677caba35e)

![shot_20240203_200527_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6e39e830-6094-4cec-a47f-c0fe4cef4cd0)

### Just a few soldiers are firing

![shot_20240203_200509_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/86ff4fd1-6042-4b0a-b893-49d742dc47cd)

![shot_20240203_200545_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ccc927ab-4e99-4619-8201-8e90fa41998f)

![shot_20240203_200600_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/44393230-d702-4e7a-8bb0-ffbe1c55d3a5)

![shot_20240203_200619_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/95ce4657-c2eb-4c52-ae39-d10b19a267fb)

**Comment by xezon** [comment]
Perhaps huts need to be elevated a bit.

Or terrain needs to be flattened.

**Comment by NoMerciBKK** [comment]
> Perhaps huts need to be elevated a bit.
> 
> Or terrain needs to be flattened.

done both now if its not fixed its based on game-engine

**Comment by cncHD** [comment]
I have removed the huts due to them beeing unable to shoot consistantly. They got replaced with bunkers instead.
Middle huts stayed, but only the big one. I will call this issue fixed

**Comment by xezon** [comment]
All 4 Bunkers can be destroyed by shooting out of them.

![shot_20240521_212520_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4f572d30-a0c7-40fc-b8fe-b7eacbdd834f)

![shot_20240521_212549_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/02b3dc62-d529-4bf9-86c5-d0de36720706)

![shot_20240521_212707_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1ca0de56-2a63-4ce5-ab74-0a2f69a7f4f4)

![shot_20240521_212718_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1fa6bca2-e50b-4493-b912-c08ba267a93f)
