### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Terrain around Artillery Platforms is not created equal

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#651]
## Observed behavior

Terrain around Artillery Platforms is not created equal.

## Expected behavior

Terrain around Artillery Platforms is created equal for consistency.

### 1. Player can build on outer hill, send infantry too

![shot_20240203_200029_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/413b268e-eb3a-4269-aeed-78fe3cecf7cb)

### 2. Player can build on outer hill, cannot send infantry

![shot_20240203_200100_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bc65e74b-02b6-415b-bb99-86eeb248da3d)

### 3. Player cannot build on outer hill, cannot send infantry

![shot_20240203_200134_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/09dd48c9-e0a4-4369-a26d-9e74aa9acb95)

### 3. Player cannot build on outer hill, cannot send infantry

![shot_20240203_200203_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ad91ecdb-7162-49df-a8bd-81a174675d77)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by cncHD** [comment]
reviewed and fixed
