### ISSUE TITLE
[Candidate 1v1 Tiny Tactics ZH v1] Civilian base shows on Radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#653]
## Observed behavior

Civilian base shows on Radar.

## Expected behavior

Civilian base does not show on Radar, if possible.

## Screenshots

![shot_20240204_103619_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4a9f52df-2373-43d1-aef6-f46e8a8dbeb0)

**Comment by NoMerciBKK** [comment]
fixed but 2 points need to stay on radar otherwise player USA strat and airfield wont be shown on map anymore
