### ISSUE TITLE
[Candidate 1v1 Tiny Tactics ZH v1] East bottom lane is narrower than west bottom lane

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#654]
## Observed behavior

East bottom lane is narrower than west bottom lane. This can affect build strategies.

## Expected behavior

East and west bottom lanes have equal width at their respective sections.

### West bottom lane has mostly generous room to build tunnels

![shot_20240204_104030_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ad9bf2fb-5fcd-4946-afbf-f5656c3170cf)

![shot_20240204_104032_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f3531cb6-9152-4d6c-9dfe-198b0f4a14a9)

### East bottom lane has less room to build tunnels

![shot_20240204_104037_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bbb06985-b9f8-4662-954a-034c89696dcc)

![shot_20240204_104057_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e4e8ec88-0d17-408c-be56-71f59f7f9b11)

![shot_20240204_104107_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/54856af0-a2dd-4f11-88d4-9544f1c84977)

**Comment by NoMerciBKK** [comment]
should be fixed

**Comment by xezon** [comment]
Fixed

![shot_20240323_130906_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/76e67072-60d4-41bf-b803-fd4356d07087)
