### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Boats show as POI on Radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#658]
## Observed behavior

Boats show as POI on Radar.

## Expected behavior

Boats do not show on Radar.

## Screenshots

![shot_20240204_113846_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5065749c-1df5-42de-ae73-c4427676ad34)

![shot_20240204_113850_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9c7283bb-7ff3-4231-9e5f-dcaf07349601)

![shot_20240204_113854_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/97165469-963a-4fc2-adf3-43bb7161442f)

**Comment by NoMerciBKK** [comment]
fixed
