### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Units can move through bridge pillars

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#659]
## Observed behavior

Units can move through bridge pillars.

## Expected behavior

Units can not move through bridge pillars.

## Screenshots

![shot_20240204_113717_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a2cf286f-4e3f-408d-b760-b932eb3b9477)

![shot_20240204_113747_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f658f566-6273-4844-9b16-cf30cbf2a31a)

**Comment by xezon** [comment]
Probably can be changed by deploying tiny impassable terrain under pillars, however, that needs to be carefully tested if it still plays good.

**Comment by NoMerciBKK** [comment]
if fucks up pathways so as designed

**Comment by xezon** [comment]
As designed.
