### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Units can move and shoot through walls

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#660]
## Observed behavior

Units can move and shoot through walls.

## Expected behavior

Units can not move and shoot through walls.

## Screenshots

![shot_20240204_113623_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/498668ed-5e7c-431a-8d73-d442df5cab6a)

**Comment by xezon** [comment]
Perhaps remove the outer walls.

**Comment by NoMerciBKK** [comment]
Removed / fixed
