### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Artillery Platforms float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#661]
## Observed behavior

Artillery Platforms float above terrain.

## Expected behavior

Artillery Platforms do not float above terrain.

## Screenshots

![shot_20240204_113107_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4f466b25-fb1b-4178-974d-416de946b864)

![shot_20240204_113117_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf24adb5-a20a-4be4-8608-be6773d4efe4)

![shot_20240204_113130_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0c2b372d-6396-4abb-84e2-14a02d580c7a)

![shot_20240204_113138_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/93422409-27bd-45fe-960b-d89003cce927)

![shot_20240204_113200_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1cbf04dc-f546-4231-bc8b-72eb2f4c819e)

![shot_20240204_113206_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a75a5cac-63b3-4b8b-8c43-eef3554e534c)

**Comment by NoMerciBKK** [comment]
big floats fixed

**Comment by xezon** [comment]
Big floats fixed confirmed. There are some small floats left but needs no attention I think.
