### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Units can hide behind Oil Derricks and cannot be attacked

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#663]
## Observed behavior

Units can hide behind Oil Derricks and cannot be attacked.

## Expected behavior

Units can not hide behind Oil Derricks or can be attacked when standing behind Oil Derricks.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3e6857c2-aee9-49a4-b026-08a0d5763c4e

**Comment by NoMerciBKK** [comment]
fixed
