### ISSUE TITLE
[Candidate 4v4 Battle for Reach] Addition to the mappool

### ISSUE THREAD

**Issue by toirehantaa** [TheSuperHackers/GeneralsRankedMaps#665]
Been played in challenges quite a lot, people are very happy with the map. Here some screenshots.
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/84abf955-8e2b-453d-9517-8180f155013b)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/e4113238-8cb1-4ffa-8a3a-5153f467ded0)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/daa0af8e-3f36-4094-af5c-9ee62f7fa2a5)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/ac7faf61-8947-4abd-81a1-babdb5816e53)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/238d345d-82dd-4394-9b47-5c03bbeadde6)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/a43cd39c-b05e-41dd-a34f-223602108426)
![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/115837820/58d59420-dbc1-4df1-b3c5-5ca022c17fb0)

**Comment by toirehantaa** [comment]
sorry for being stupid with the labels and stuff, missclicking constantly...

**Comment by xezon** [comment]
Prefer attaching JPG images, because they are much smaller than PNG images.

Map has been added to candidates.
