### ISSUE TITLE
[Candidate 1v1 Salt Lake River ZH v2] Units can move around Artillery Platforms in the north west, but not in the south east

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#666]
## Observed behavior

Units can move around Artillery Platforms in the north west, but not in the south east

## Expected behavior

Mirrored tech buildings offer equal unit mobility opportunities

### Can move around

![shot_20240323_125431_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/066abee8-461d-47b0-b9c7-d66a18484a36)

![shot_20240323_125513_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1af7f4c9-de42-4013-9512-abacda3d20cb)

## Cannot move around

![shot_20240323_125442_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/598f1ec0-0191-4a1f-8acb-9c8d31d0ef57)

![shot_20240323_125501_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/39380a7f-1bd2-4276-826d-876b95ca7f9f)

**Comment by NoMerciBKK** [comment]
updated
