### ISSUE TITLE
[Candidate 4v4 Persian Gulf Conflict ZH v5] Wind audio is crackling

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#670]
## Observed behavior

Wind audio is crackling when scrolling over map.

## Expected behavior

Wind audio does not crackle when scrolling over map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/43eabad4-0709-4554-bcc0-377d26d7c18d

**Comment by NoMerciBKK** [comment]
should be fixed

**Comment by xezon** [comment]
Wind sounds ok to me. But these structures still emit sound that trigger bad crackling when scrolling.

![shot_20240426_203319_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/03ef625e-3193-4b83-a15e-d1e953ef15c8)
