### ISSUE TITLE
[Candidate 4v4 Persian Gulf Conflict ZH v5] Rocks in center do not necessarily look impassable but are

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#671]
## Observed behavior

Rocks in center do not necessarily look impassable but are. Happens 8 times in center.

## Expected behavior

Rocks (or other obstacles) are large enough and cover appropriate surface area to justify impassable terrain.

### Rocks look very small, but units cannot pass it

![shot_20240323_185005_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2360a1e0-7a68-433c-b3c6-f82d25f0a4c1)

### Rocks look tall, but do not cover enough area to justify entire impassable area

![shot_20240323_185021_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bfc62a88-d2a2-4f6a-a446-3c7ee4dd8f3a)

**Comment by xezon** [comment]
I suggest to put large enough obstacles to justify impassable area. Note: Units can shoot over it, so it should not be too large!

**Comment by NoMerciBKK** [comment]
fixed
