### ISSUE TITLE
[Candidate 4v4 Persian Gulf Conflict ZH v5] Civilian structures show as POI on radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#672]
## Observed behavior

Civilian structures show as POI on radar.

## Expected behavior

Civilian structures do not show as POI on radar.

## Screenshots

![shot_20240323_184328_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f92bca8-17fb-4fef-8d55-a17791ba4408)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Fixed in principle.

There still are towers showing as POI. Perhaps we can replace the unusable towers with another structure?

![shot_20240426_203946_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fc7bed16-c270-499e-bd7d-bbc8187a1697)
