### ISSUE TITLE
[Candidate 4v4 Persian Gulf Conflict ZH v5] Barrels at Oil Derricks are not consistently placed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#673]
## Observed behavior

Barrels at Oil Derricks are not consistently placed.

## Expected behavior

Barrels at Oil Derricks are properly mirrored.

### Barrels face map outwards

![shot_20240323_184613_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9ecbff67-f0b8-423e-b693-ebaf9a39482f)

### Barrels face map inwards

![shot_20240323_184623_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/db161379-d2ae-4de7-8c48-0cb4f2410194)

### Barrels face map to the side

![shot_20240323_184638_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a11e2dd8-d9c7-4663-858d-482156fa573d)

**Comment by xezon** [comment]
I suggest reposition them so they all face map inwards or map outwards. Then it is fair.

**Comment by NoMerciBKK** [comment]
fixed
