### ISSUE TITLE
[Candidate 4v4 Persian Gulf Conflict ZH v5] Units cannot move around the Oil Refinery in the south west

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#674]
## Observed behavior

Units can move around all Oil Refineries except the one in the south west.

## Expected behavior

Units can move around all Oil Refineries.

### Units can move around

![shot_20240323_184835_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/68a7529d-1012-4f68-a603-91fbfcf12df5)

![shot_20240323_184851_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf915b0f-77b1-48e4-b300-0a36abd14c20)

![shot_20240323_184905_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bd0215db-000d-496b-a2a0-0673c6ecd3ab)

### Units can not move around

![shot_20240323_184926_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b9a06b25-69e0-4b29-b21d-9760a565450b)

**Comment by NoMerciBKK** [comment]
fixed
