### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Vehicle props are very dark

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#677]
## Observed behavior

Vehicle props are very dark.

## Expected behavior

Vehicle props look natural.

## Screenshots

![shot_20240323_194342_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8321baf3-9bad-4481-a9af-3b341f6c1840)

![shot_20240323_194352_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/81c80556-af06-4e04-870a-ce8540589c5d)

**Comment by NoMerciBKK** [comment]
fixed
