### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Units can move through large props

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#678]
## Observed behavior

Units can move through large props.

## Expected behavior

Units cannot move though large indestructible props.

## Screenshots

![shot_20240323_194410_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5f303482-a21f-4e0b-8d75-5b246159d12d)

![shot_20240323_194436_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3ded7fc5-bbeb-4c6e-b9ce-3522669e4f32)

![shot_20240323_194441_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7cc1f9d8-1c8d-4458-ba90-23c3c17ebfa4)

![shot_20240323_194455_49](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f51b1395-3c9b-4d4f-b5ba-03343143d9b3)

![shot_20240323_194524_50](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/887e07b5-fdf2-4aa1-ac64-557d3b7af3e5)

**Comment by xezon** [comment]
The shipping containers and tanks are destructible. So it is probably fine to be able to move through these, but it looks odd.

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
The shipping containers are impassable and indestructible now, that is fine.

But the tanks are impassable and destructible, which is not good either, because it leaves impassable terrain after destruction. So they should be either passable and destructible, or impassable and destructible. I would say revert them how they were originally. Is not optimal, but ok.

![shot_20240511_081402_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a8a48429-5cee-4832-a162-47f7aacc54d5)

![shot_20240511_081409_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d44fa497-b91e-4d2d-867e-3736bfd50488)

**Comment by xezon** [comment]
While at it, perhaps make the red cranes indestructible. They just disappear when shoot at with force fire.

![shot_20240511_082044_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/40e83726-5e27-49a1-977d-876baa24ea5d)

**Comment by NoMerciBKK** [comment]
> While at it, perhaps make the red cranes indestructible. They just disappear when shoot at with force fire.
> 
> ![shot_20240511_082044_8](https://private-user-images.githubusercontent.com/4720891/329759161-40e83726-5e27-49a1-977d-876baa24ea5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTQ4ODgsIm5iZiI6MTcxNTQxNDU4OCwicGF0aCI6Ii80NzIwODkxLzMyOTc1OTE2MS00MGU4MzcyNi01ZTI3LTQ5YTEtOTc3ZC04NzZiYWEyNGVhNWQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDgwMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg0MWVkZWQ0YzM5Yjc0MmY0ZWY4YzMxZTJhZWJhZjQ5M2ExMGU3ZmM5ZmE5OWFkZmE4ZTE5MDgyMTMxMzRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qjk75ZjxOGRzxo3sM53U-YU1tWkeC6bwncITqTyHST4)

they are all indestructible in WB just checked

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
## 11.05.2024

All red cranes are no longer destructible.

Several shipping containers are still destructible. I have marked them in the following screenshots (after destruction).

![shot_20240511_145356_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5a602dba-704f-4f4a-8661-eddb6bc43e4e)

![shot_20240511_145404_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7cd0a347-8ce5-4d85-8c7f-8d658c25ccb5)

![shot_20240511_145410_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f4b5bca7-10d7-4d92-96a4-bdea9e7706cb)

![shot_20240511_145419_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0f1bc3a8-690e-45b2-89ca-34fdbdc88bb6)

![shot_20240511_145423_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/619ac712-1431-4c51-b860-d0007eb27d42)

![shot_20240511_145511_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4caf802b-04c3-4bfa-8fe3-a922d1a7a7b6)

![shot_20240511_145528_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0d3b03eb-d0f9-4fa5-8486-a6c68b6e5ab8)

![shot_20240511_145534_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5baaca4c-6b45-4d98-8b04-d10313bbf1ca)

![shot_20240511_145634_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/124bc578-b061-428f-9164-7ee9fb0030d3)

![shot_20240511_145652_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/93bf6831-fc8f-4fea-ba7d-ff9bd93fbed8)

**Comment by xezon** [comment]
Black Oil Tanks are impassable and no longer destructible.
