### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Supply Piles near map border have inconsistent room for movement

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#679]
## Observed behavior

Supply Piles near map border have inconsistent room for movement.

## Expected behavior

Supply Piles near map border offer consistent movement opportunities.

### 1. Can move behind

![shot_20240323_194537_51](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/16cd2236-3111-45fc-a0b2-d22136243ea0)

### 2. CAN NOT MOVE BEHIND

![shot_20240323_194548_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2e5230d8-5be8-4300-b759-2bbe86d3fa50)

### 3. Can move behind

![shot_20240323_194611_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/64d728de-2df2-4e00-9390-2ea6a32c506e)

### 4. Can move behind

![shot_20240323_194626_54](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/251abe14-31df-464b-8549-4d29d0f2be5d)

### 5. Can move behind

![shot_20240323_194638_55](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a41a1fd7-c1fd-4866-bbc2-90090d48f589)

### 6. Can move behind

![shot_20240323_194649_56](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/01722c24-9d20-4ee9-a9ad-776a3feafa8d)

### 7. CAN NOT MOVE BEHIND

![shot_20240323_194708_57](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0643844a-0003-4734-b100-44ec15fc801a)

### 8. Can move behind

![shot_20240323_194718_58](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3a9c9759-ce5d-4abd-9e55-a298058f74ed)

**Comment by NoMerciBKK** [comment]
fixed
