### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Oil Derricks near map center have inconsistent room for movement

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#680]
## Observed behavior

Oil Derricks near map center have inconsistent room for movement.

## Expected behavior

Oil Derricks near map center offer consistent mobility opportunities.

### 1. Can move around

![shot_20240323_194050_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7d38f89e-372f-4fdd-a600-3e83ece38710)

### 2. Can move around

![shot_20240323_194054_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6480f5cb-cef7-41ca-893e-b0044392fbca)

### 3. Can move around

![shot_20240323_194100_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9aa27d1a-71b3-45b2-86ca-9e8aade543cb)

### 4. Can move around

![shot_20240323_194106_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4f1df8fc-403a-4d88-b437-b03249961876)

### 5. Can move around

![shot_20240323_194112_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/134a9742-6e8a-4a17-b4a5-ac1f5ff01ce7)

### 6. CAN NOT MOVE AROUND

![shot_20240323_194119_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/aeed1092-c7d3-447b-97e5-ceb924440da7)

### 7. CAN NOT MOVE AROUND

![shot_20240323_194124_34](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ef0de43a-df6e-4101-b479-52e03f708320)

### 8. CAN NOT MOVE AROUND

![shot_20240323_194133_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ea5dcb90-fbaa-4e27-81e2-94a8be611da6)

### 9. Can move around

![shot_20240323_194139_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/909d146e-c786-4058-8f33-13af1057874a)

### 10. Can move around

![shot_20240323_194146_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2840730f-3e3c-418a-8d14-cf9120fa6f2c)

### 11. CAN NOT MOVE AROUND

![shot_20240323_194154_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e0fc94ec-75e7-40f7-8e1d-38f6e3bb4a73)

### 12. Can move around

![shot_20240323_194207_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5cfc2523-fb82-4bef-9a58-40ee51b3238d)

### 13. Can move around

![shot_20240323_194213_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d31ca7f5-ce9b-44e0-a7c9-f602dd35f4b1)

### 14. CAN NOT MOVE AROUND

![shot_20240323_194218_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/67a906b1-1036-4d65-950b-f580771eb840)

### 15. Can move around

![shot_20240323_194248_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7933a69d-0ede-4728-809e-f74c16b92399)

### 16. Can move around

![shot_20240323_194258_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4fddbc26-d7aa-407e-acee-6f3226473f3e)

**Comment by NoMerciBKK** [comment]
fixed
