### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Soldiers can damage their own building

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#681]
## Observed behavior

Soldiers can damage their own building when shooting to the north west.

## Expected behavior

Soldiers can not damage their own building

## Screenshots

![shot_20240506_175739_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4a573add-0fae-4c37-bf5a-614d8735bbab)

**Comment by NoMerciBKK** [comment]
fixed
