### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Unusable buildings show as POI on radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#682]
## Observed behavior

Unusable buildings show as POI on radar.

## Expected behavior

Unusable buildings do not show as POI on radar.

## Screenshots

![shot_20240506_175947_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5efcb20c-5f68-499f-b640-3c784f1a5bcc)

![shot_20240506_181051_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/789eaca0-883f-4aad-9670-2ae017aa4bdf)

![shot_20240506_181116_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5cd87919-c4c7-4cc1-90e7-e25ffaa0eed8)

**Comment by NoMerciBKK** [comment]
fixed for the most buildings

**Comment by xezon** [comment]
Yes. Looks much cleaner now. There are still a few left over:

### 2 objects here

![shot_20240511_082321_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3401f9b5-edb2-4a19-b987-67547e8db266)

### 1 of these

![shot_20240511_082624_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dd410f5c-152e-49e5-83f1-d26c4e9d43fa)

### Something here

![shot_20240511_082638_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1f1b90a4-a668-474f-a2c2-0c82bac1b5e8)

### This I suspect

![shot_20240511_082727_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/efa41806-5ad7-446a-8477-e00381cdffcb)

**Comment by NoMerciBKK** [comment]
1,2&3 cause of the house in the right corner yes.
4 is a nuclear bunker from mid with radiation so POI

**Comment by xezon** [comment]
There are also other buildings on this map that can explode but do not show on radar.

**Comment by xezon** [comment]
One of 1 fixed. 4 fixed.

How about we replace the usable house in the bottom right corner with another, then turn off the radar POI for this type of house? Then all of them are fixed. It is a strange garrisonable house anyway, because it only has one infantry slot.

**Comment by NoMerciBKK** [comment]
> The rocket silo in the center still shows as POI on radar but I will mark this report as fixed now.

its a POI after 20 min it got a "start" animations at least the scrits say that
