### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Cars on impassable terrain are usable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#683]
## Observed behavior

Cars on impassable terrain are usable. GLA terror can not reach it.

## Expected behavior

Cars are not usable.

## Screenshots

![shot_20240506_181237_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/04fc029f-b3c7-4515-a2ca-4b8013ec40c8)

**Comment by NoMerciBKK** [comment]
fixed
