### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] One soldier will move down after evacuating tower

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#684]
## Observed behavior

One soldier will move down after evacuating tower. Happens on most towers near the edge.

## Expected behavior

All soldiers evacuate at the top of the ledge and stay there.

### Soldier moved down after evacuate

![shot_20240506_180548_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/03bed2ff-3ba5-4c5d-8cbb-a8e9d428d9fb)

### Does not happen on every tower

This one is ok:

![shot_20240506_180559_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0eddc80b-b669-44b4-a81c-42b9a63e1fc9)

**Comment by NoMerciBKK** [comment]
fixed
