### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Performance will briefly drop by 95% when sending soldiers into bottom right house

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#685]
## Observed behavior

Performance will briefly drop by 95% when sending soldiers into bottom right house.

## Expected behavior

Performance does not drop when garrisoning buildings.

## Screenshots

Send soldiers to this house

![shot_20240506_180438_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f49f3b04-cad7-464d-ac57-8495dd684d54)

Performance drops every time the soldiers are ordered to enter.

![shot_20240506_180426_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d56e2ae6-8576-41e2-a371-013ba0aa2017)

**Comment by NoMerciBKK** [comment]
hopefully fixed

**Comment by xezon** [comment]
Yes performs good now.
