### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Evacuating 10 soldiers at top bunkers will leave one of them trapped

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#686]
## Observed behavior

Evacuating 10 soldiers at top bunkers will leave one of them trapped.

## Expected behavior

Soldiers are not trapped after evacuation.

## Screenshots

![shot_20240506_180127_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a22859d3-b980-482a-bf60-7c18cb83b296)

**Comment by NoMerciBKK** [comment]
fixed
