### ISSUE TITLE
[Candidate 4v4 Umbrella Corps ZH v1] Audio emitters have no easing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#689]
## Observed behavior

Audio emitters have no easing.

## Expected behavior

Audio sounds pleasant when scrolling from one place to another without hard cuts.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/270b16da-a290-455b-bb71-a585ed41a80b

**Comment by NoMerciBKK** [comment]
fixed
