### ISSUE TITLE
[Candidate 1v1 Winding River Revised ZH v1] Map has rain and thunder sounds, but no rain effect

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#691]
## Observed behavior

Map has rain and thunder sounds, but no rain effect.

## Expected behavior

Map has no rain and thunder sounds, or has rain effect.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8c0591af-44cd-4670-adbc-5477a2039402

**Comment by FiReArM-ZH** [comment]
Audio is as in the original map and has not been touched

**Comment by xezon** [comment]
Meaning its already bad in the original. Can this be improved or impossible? If I am not mistaken there are maps with light rain sounds and visual effects.

**Comment by FiReArM-ZH** [comment]
In that case I'll choose to remove sound effects rather than adding rain/thunder.
I don't want them to cause FPS issues for low end PC/laptops

**Comment by xezon** [comment]
Rain sound is still present.

**Comment by xezon** [comment]
Rain sound is still present.
