### ISSUE TITLE
[Candidate 1v1 Winding River Revised ZH v1] Oil Derrick at the top has civilian buildings nearby, Oil Derrick at the bottom does not

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#692]
## Observed behavior

Oil Derrick at the top has civilian buildings nearby, Oil Derrick at the bottom does not. This makes one of the Oil Derricks easier to defend.

## Expected behavior

Both Oil Derricks offer equal bunker opportunities.

## Screenshots

![shot_20240507_202509_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fda6a8b2-26f9-4dd5-9d08-9f04f40efa5e)

![shot_20240507_202422_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2fc8f97e-bbd9-4c90-992f-e1c7d5e27ba7)

**Comment by xezon** [comment]
Bottom Oil Derrick is further away from river and bridge, which is good for it, but unclear to me if that offsets the house disadvantage.

**Comment by NoMerciBKK** [comment]
this is a remake of an official map so it will be inbalanced but as other inbalanced ranked maps you normaly play the reverse so it should be fine

**Comment by xezon** [comment]
Oil Derricks were moved in new revision. Observations:

### Top Oil Derricks now clips through terrain

![shot_20240511_115353_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3898141c-3ae2-4fd2-ac89-b2834d7d98cc)

### Ramp to top Oil Derrick is much closer than at the bottom

Is this fair?

![shot_20240511_115445_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd1a6213-1124-4542-93cc-cc61a1158861)

![shot_20240511_115450_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/60f37a78-4690-4e64-baf0-219d6005bc4f)

### Both Oil Derricks can be killed with Dragon Tank from other side

As designed?

![shot_20240511_115710_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/36ccbd0f-04d9-43d0-b2ee-b68584d81721)

![shot_20240511_115715_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ccd66311-5ea9-4243-8fd3-ff02840387fc)

**Comment by NoMerciBKK** [comment]
i did no changes on this map, i think @FiReArM-ZH made those.

**Comment by FiReArM-ZH** [comment]
1 and 2 I'll fix them later. 
3 - not intended but many maps already have it. So should be ok imo

**Comment by xezon** [comment]
Setup looks fair to me now.
