### ISSUE TITLE
[Candidate 1v1 Winding River Revised ZH v1] Supply Docks have differently sized gaps towards the map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#693]
## Observed behavior

Supply Docks have differently sized gaps towards the map border. Top Docks gaps are narrower, bottom docks are wider.

## Expected behavior

Supply Docks offer about equal unit mobility opportunities around them.

### Top is narrow

![shot_20240507_201343_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7920b29a-4263-46ef-8ef7-62a43b6b12db)

![shot_20240507_201350_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c7b54e92-e4cf-4903-bebc-5ceea0d7c40d)

### Bottom is wide

![shot_20240507_201355_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b6a1a55f-944d-4212-a4ef-72e7d05d0c19)

![shot_20240507_201404_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1629c225-38b7-4995-889b-d6bf7dfce61f)

**Comment by xezon** [comment]
Not sure if this should be blocker. Map design is kind of asymmetric. It is really difficult to evaluate what is fair and what is not.

**Comment by NoMerciBKK** [comment]
i think we should kick/skip this map there is loads to do on it afais in wb
