### ISSUE TITLE
[Candidate 1v1 Winding River Revised ZH v1] Houses cannot shoot in certain directions and/or damage themselves

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#695]
## Observed behavior

Houses cannot shoot in certain directions and/or damage themselves. I have not tested each house. But at first sight there is a lot wrong and room to optimize.

## Expected behavior

Houses are well setup soldiers can shoot in all directions. They never damage the house when shooting out of it.

### 1. House was destroyed when shooting north west

![shot_20240507_200358_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4aeb44fb-08b7-49aa-84b1-01aae3e45039)

### 2. Only one of 10 soldiers shoots in this direction

![shot_20240507_200414_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cd0febaf-f187-4fc1-848b-bb99e8676abf)

### 3. No soldier can shoot in this direction (on terrain)

![shot_20240507_200436_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/31b0d02c-4b0e-46e0-956e-ed953be7684d)

### 4. No soldier can shoot in this direction (on terrain)

![shot_20240507_200448_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/06c890d3-3f54-44ab-8fe9-866df8ba4f8d)

### 5. Rockets can hit terrain when shooting in this direction

![shot_20240507_200533_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c4104353-dcd0-460b-92a7-dd88650082c5)

### 6. No soldier can shoot in this direction (on terrain)

![shot_20240507_200543_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/475ca22d-09b9-44f6-827f-52924bcb27d9)

### 7. No soldier can shoot in this direction (on terrain)

![shot_20240507_200555_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5cf76ae8-ea8b-47ad-98a4-bac674f33971)

### 8. Only one of 10 soldiers shoots in this direction

![shot_20240507_200629_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e33d7453-a5ba-4a53-a3aa-92904c25ace7)

### 9. Only one of 10 soldiers shoots in this direction

![shot_20240507_200641_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0cda2204-822f-4713-880f-9a4bf91e84da)

### 10. This house can damage itself when shooting north east

![shot_20240507_200842_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/095992b6-ada6-4c15-8f03-557a66c6ea25)

### 11. This house has troubles shooting south (on terrain) over the elevated tracks

![shot_20240507_201049_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7a523b82-a2f5-4175-9b8e-268a710d8f7b)

![shot_20240507_201126_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f437ce67-b9eb-4f7a-91d7-ad3c203fde39)

### 12. This house has troubles shooting east (on terrain) over the elevated tracks

![shot_20240507_201135_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b212c813-271c-44ff-bc14-3d129ffa6157)

### 13. This house is destroyed when shooting north east (on terrain)

![shot_20240507_201236_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/43a2e65f-fb9b-4e87-825f-3a834922d4d5)

**Comment by xezon** [comment]
Houses near train tracks work good now.

There still is one hut that can self destruct:

![shot_20240511_120716_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/70c65bca-1c83-4d9a-9501-6febe2c8cad6)

The removed houses at all the beaches leave a void. Beaches look odd now. Perhaps do not remove huts and houses, but just make them not usable?

![shot_20240511_120816_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f6c27f50-f651-4977-b88c-5cf29a75c08d)

**Comment by FiReArM-ZH** [comment]
Making unusable confuses players. 
I'll make it something else and make them look better
