### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Soldiers damage some buildings when shooting out of it

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#696]
## Observed behavior

Soldiers damage some buildings when shooting out of it.

## Expected behavior

Soldiers do not damage buildings when shooting out of it.

## Screenshots

![shot_20240508_192157_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d86578cb-97b3-4340-876a-a22b3623d58f)

![shot_20240508_192253_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9dab86ef-3914-476c-a6d7-81565ffeb06b)

![shot_20240508_192628_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1768d16b-9c90-4d7a-bc90-d8155b9dd581)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Houses 1 and 3 can still self destruct.

![shot_20240510_190129_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e370a86c-b70a-456d-aee8-b8c21e5bcc5a)

![shot_20240510_190312_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f0c95cd5-93e4-4b5b-b0a1-fc26b95c489c)

**Comment by NoMerciBKK** [comment]
tried to fix it again, couldnt reproduce it in my newest test
