### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Some Oil Derricks clip through terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#697]
## Observed behavior

Some Oil Derricks clip through terrain.

## Expected behavior

Oil Derricks sit on terrain.

## Screenshots

![shot_20240508_192859_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/34cd3a0f-3c14-430a-ba5d-b44dc6ce1949)

![shot_20240508_192911_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6818ea56-aa52-49ce-82de-4d1229cff911)

![shot_20240508_192920_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c40d1fb2-736a-4e83-947e-a49ec6cd7637)

![shot_20240508_192955_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f7bd84ca-5d97-40f3-a0d3-9563e6c63520)

**Comment by NoMerciBKK** [comment]
fixed
