### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Supply Docks float a bit above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#698]
## Observed behavior

Supply Docks float a bit above terrain.

## Expected behavior

Supply Docks sit tight on terrain.

## Screenshots

![shot_20240508_193021_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7436239c-04d4-4545-b13b-c990754edb13)

![shot_20240508_193035_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6a3c9566-8de2-44f2-b691-c1e4109d3a95)

![shot_20240508_193049_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ddcb0d46-7b83-43a9-8750-580a87a0b6e4)

![shot_20240508_193110_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/56d7bf4f-43ec-45c9-ac02-f3d358c8549e)

![shot_20240508_193136_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c3fedca7-ed7a-4db0-a2fa-95be69cc0eb2)

![shot_20240508_193203_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/541931b4-e8cd-4256-b19d-dd2cca6fc982)

**Comment by xezon** [comment]
One of them still floats

![shot_20240510_190438_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/329d2f56-793b-4f6c-a949-a179e242233a)

**Comment by NoMerciBKK** [comment]
fixed
