### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Units can drive around 6 of 8 Supply Piles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#699]
## Observed behavior

Units can drive around 6 of 8 Supply Piles only.

## Expected behavior

Units can drive around 8 of 8 Supply Piles only.

## Screenshots

![shot_20240508_193123_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/749df269-c58a-45e7-9826-4d64b35c09fc)

![shot_20240508_193145_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1198f2e5-1f13-464e-852d-b90f548c9bae)

**Comment by NoMerciBKK** [comment]
fixed
