### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Units can drive around 7 of 8 houses

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#700]
## Observed behavior

Units can drive around 1 of 8 houses. It can help to protect or escape an important unit, like a Dozer.

## Expected behavior

Units can drive around 0 of 8 houses.

### UNIT CAN DRIVE AROUND THIS HOUSE

![shot_20240508_193318_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6af316d6-269b-455b-a74b-876440f6a2ac)

### Unit cannot move around this house

![shot_20240508_193331_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/26a70909-e1d4-4f3d-ac4a-dcce59f0e9d8)

### Unit cannot move around this house, but looks as if it could

![shot_20240508_193340_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0c189bca-195c-49b3-a3ec-d2a02f01827a)

### Unit cannot move around this house

![shot_20240508_193348_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1cfa2d7e-8d69-4983-abb9-0a74460e6d2f)

### Unit cannot move around this house

![shot_20240508_193356_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3e3c1376-3338-451c-96c0-5f395d4bba46)

### Unit cannot move around this house

![shot_20240508_193403_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3bb2dd5c-9726-4b3a-8967-9e0b4aee23fe)

### Unit cannot move around this house

![shot_20240508_193410_24](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e463c928-a9fd-4709-851d-939cebc7020f)

### Unit cannot move around this house, but looks as if it could

![shot_20240508_193417_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bea9883e-db6f-4762-b4ba-548948ea5b70)

**Comment by NoMerciBKK** [comment]
fixed
