### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Player cannot build China Supply at 1 of 8 Docks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#701]
## Observed behavior

Player cannot build China Supply at 1 of 8 Docks.

## Expected behavior

Player can build China Supply at 8 of 8 Docks.

### PLAYER CANNOT BUILD

![shot_20240508_193548_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a48096c4-368d-4a97-b0ba-d915df7b0a45)

### Player can build

![shot_20240508_193602_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/48ddf397-be3f-46ec-9747-fb83fdfc5ec7)

![shot_20240508_193616_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1a7655ab-5542-495d-a572-18ab36b1ecab)

![shot_20240508_193629_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e6b30169-bd50-47f7-9a44-e96ef8af6098)

![shot_20240508_193643_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c8c12334-fc33-47c4-87bf-a8e7a2af085d)

![shot_20240508_193751_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/04e8b9e0-cd6d-41b9-ad21-5c94db6662b1)

![shot_20240508_193535_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f7cfe3e9-c67a-45d9-8acb-1cbff04fdd91)

![shot_20240508_193541_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5cd13c0e-847e-4aa0-b0be-f357988ca1d9)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
It is now possible to build a Supply Depot there, but not at an optimal distance for the Trucks, unlike at all other Supply Docks.

![shot_20240510_190834_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/99641a8c-27f4-4831-9ef9-0533eec509dd)

**Comment by NoMerciBKK** [comment]
updated
