### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] GLA can build safe Supply Stash at 1 of 8 Supply Piles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#704]
## Observed behavior

GLA can build safe Supply Stash at 1 of 8 Supply Piles.

## Expected behavior

GLA can build safe Supply Stash at 0 of 8 Supply Piles.

## Screenshots

![shot_20240508_193952_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/38da1da6-de46-4f1d-86b9-cb2795573f29)

![shot_20240508_194005_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a0a3e5d7-6b41-464f-afcf-f93b3a41d773)

![shot_20240508_194018_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/60fe9836-a97c-497a-870e-762eacee6749)

![shot_20240508_194028_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8ec4133a-078d-402c-9141-a2b04e6986a1)

![shot_20240508_194037_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c2090b06-8fc3-425e-8fa0-0a06c9f5cac1)

![shot_20240508_194052_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2d1f5f60-1a0c-4c5d-b51f-adfeda071c41)

![shot_20240508_194103_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a8ef4cd5-5d35-48ab-ba3e-7bdd2015f64d)

![shot_20240508_194114_44](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d874c23a-ba1c-472b-b2a3-ed709a21fdc0)

**Comment by NoMerciBKK** [comment]
fixed
