### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Units can move at some coastal walk ways

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#705]
## Observed behavior

Units can move at some coastal walk ways but not others.

## Expected behavior

Units cannot move at coastal walk ways. Impassable.

### Unit can pass here (2)

![shot_20240508_194144_45](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9612a137-dc8d-44ad-afde-5c7640c78d29)
![shot_20240508_194154_46](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8fe9e01b-b274-4b55-9082-f8c4c736e6fb)

### Unit can almost pass here (5)

![shot_20240508_194227_47](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/83671192-4722-4c42-8ed7-2c5944e0ec35)
![shot_20240508_194244_48](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/32d52f44-1946-49c9-8e6b-df60a054940d)
![shot_20240508_194345_49](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e9c8f7d-25ae-4d5f-a2bc-e0bd02cceb51)
![shot_20240508_194415_50](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/26e0d787-b0e6-4bda-913c-18678de0fe8b)
![shot_20240508_194424_51](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e24f5f90-a845-44fb-9e58-a5bcf192b08e)

**Comment by NoMerciBKK** [comment]
shouldnt be a blocker imo but fixed
