### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Terrain and wave artifacts at map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#706]
## Observed behavior

There are minor terrain and wave artifacts at the map border.

## Expected behavior

Map border is ocean.

## Screenshots

![shot_20240508_194533_52](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/90f4970b-f700-4b85-9698-afe86e8a6d49)

![shot_20240508_194538_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3c72cb04-25d2-439b-9bc8-7603ea01cdef)

![shot_20240508_194552_54](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fcfecb6c-11e4-4ae6-ab43-bb44c41a25d6)

![shot_20240508_194558_55](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b8ca8f90-3cb5-437b-a2e9-8b0cfb7d2789)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Terrain is fixed. Wave is still there.

**Comment by NoMerciBKK** [comment]
> Terrain is fixed. Wave is still there.

sadly there is no wave in the worldbuilder ^^

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/18619f8b-3eae-4fb2-a5aa-20d0666897c4)

**Comment by xezon** [comment]
There now is an island instead of a wave. Looks odd.

![shot_20240511_130541_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8a89af14-e04e-4242-b26c-68cbdf674b2a)

**Comment by NoMerciBKK** [comment]
> There now is an island instead of a wave. Looks odd.
> 
> ![shot_20240511_130541_32](https://private-user-images.githubusercontent.com/4720891/329776437-8a89af14-e04e-4242-b26c-68cbdf674b2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzQ5NjksIm5iZiI6MTcxNTQzNDY2OSwicGF0aCI6Ii80NzIwODkxLzMyOTc3NjQzNy04YTg5YWYxNC1lMDRlLTQyNDItYjI2Yy02OGNiZGY2NzRiMmEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTMzNzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWIyMzBlOTk4Y2JmNGIxM2Q1YjczOWNjYzkyYWFhM2IwMTZhN2Q3OWQ5YzU1NTA3NDM5Y2JmOGJmZDVlZGY1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PfhRwfuaohn6xqIfEynS6hwfLlNNvpCigfShPrLo1Jc)

you can have an odd looking island not showing on radar or a random wave :D

**Comment by xezon** [comment]
The wave was smaller, so I would go with that.

**Comment by xezon** [comment]
Wave is back, but otherwise looks good, closing done.
