### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Unit can get stuck at northern coast

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#709]
## Observed behavior

Unit can get stuck at northern coast.

## Expected behavior

Unit cannot get stock at northern coast.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/552006f6-1b2c-4d34-8894-49f20a80cba6

**Comment by NoMerciBKK** [comment]
fixed
