### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Map has just basic audio setup

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#711]
## Observed behavior

Map has just basic audio setup. There are ocean sounds in the corners, and a bunch of civilians talking by the various huts on land. That is it.

## Expected behavior

Map has a richer variety and coverage of appropriate sounds.

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Wind was added to fill the void. Sounds good.
