### ISSUE TITLE
[Candidate 4v4 Desert Vortex ZH v7] Terrain in home base is not good for building

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#712]
## Observed behavior

Terrain in home base is not good for building.

## Expected behavior

Terrain in home base allows for great base builds with ease.

## Screenshots

![shot_20240509_081547_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d84e21b0-3ecb-4af0-8156-1ea1a69fdd11)

![shot_20240509_081556_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4deeb2f0-84e9-4149-bd88-fe4335839962)

![shot_20240509_081602_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bdca6351-2ed2-479d-8f79-f42926a96589)

**Comment by NoMerciBKK** [comment]
there is a slope down to the water thats intended by the mapper i think, the rest is all one hight. so imo no blocker cause designed

**Comment by xezon** [comment]
But how is one supposed to build there then? Why can the slope not be confined to the near water area?

**Comment by NoMerciBKK** [comment]
![shot_20240509_174555_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/d216383b-5637-41a0-a132-4acad8d62649)

i think thats good to build

**Comment by xezon** [comment]
Ok I will recheck then.

**Comment by xezon** [comment]
Ok
