### ISSUE TITLE
[Candidate 3v3 Coral Islands ZH v1] Map intro text shows as missing

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#713]
## Observed behavior

Map intro text shows as missing. It says "MISSING: 'MapIntro01'"

## Expected behavior

Map intro works properly or is removed.

## Screenshots

![shot_20240509_091644_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0590799a-387b-48fb-9b16-b594497e17b2)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Map was made by "El Chapo" if I am not mistaken.

**Comment by NoMerciBKK** [comment]
> Map was made by "El Chapo" if I am not mistaken.

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/2f9ca7f1-32ee-4142-b7b1-8c048fd88bc4)
