### ISSUE TITLE
[Candidate 3v3 Coral Islands ZH v1] Boats and inaccessible houses show as POI on radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#714]
## Observed behavior

Boats and inaccessible houses show as POI on radar.

## Expected behavior

Boats and inaccessible houses do not show as POI on radar.

## Screenshots

![shot_20240509_091807_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b384e498-8350-441e-8ece-b5ec21280071)

**Comment by NoMerciBKK** [comment]
fixed
