### ISSUE TITLE
[Candidate 3v3 Coral Islands ZH v1] Some Oil Derricks are rotated at random, without symmetry

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#715]
## Observed behavior

Some Oil Derricks are rotated at random, without symmetry.

## Expected behavior

Oil Derricks have symmetrical rotations, or rotations that put their flag at a high visibility.

### Some samples, not complete.

![shot_20240509_091942_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fd5ac0b0-b0e2-482f-a89e-3a384da287ad)

![shot_20240509_091948_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1ebf99b8-b5c6-44bf-a946-061b46c13d8c)

![shot_20240509_091957_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/37edea9d-0ba5-4238-bbb2-2f1b4a9b4f5b)

![shot_20240509_092001_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8e8131f2-0e52-4b10-8731-b011701d32ef)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Outer Oil Derricks are now rotated like so:

![shot_20240511_074736_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d8f3d1e0-8e16-4091-9a2e-7f12b36e7e9c)

May I suggest to rotate them 45 degrees counter clockwise? Then their flag will be no longer in the shade.

Inner ring Oil Derricks are still rotated without a system.

**Comment by xezon** [comment]
One Derrick was not rotated. Otherwise looks good.

![shot_20240511_143606_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2d1a0e21-8462-46ea-95d9-8484c28c0053)

**Comment by xezon** [comment]
Not fixed in new version.

**Comment by NoMerciBKK** [comment]
i think i mixed up some versions gonna have a look a bit later sry for the trouble
