### ISSUE TITLE
[Candidate 3v3 Coral Islands ZH v1] Gras huts are unexpectedly strong

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#716]
## Observed behavior

Gras huts are unexpectedly strong. They tank as much damage as regular buildings, which is unusual.

## Expected behavior

Gras huts are relatively weaker than regular houses like on every other map.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/00d5793d-602a-4d81-a6a7-bcad39078940

**Comment by NoMerciBKK** [comment]
set back to default
