### ISSUE TITLE
[Candidate 3v3 Coral Islands ZH v1] Clumped houses will damage themselves when firing out of them

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#717]
## Observed behavior

Clumped houses will damage themselves when firing out of them. This likely happens because the fire ports emerge from inside the nearby structure.

## Expected behavior

Houses do not damage each other when troops shoot out of it.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f7df6e18-8400-4076-934a-fee3b179f37d

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/54b33035-301b-487a-8ff6-f66d4f851dd0

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3a13538b-aee9-4f3b-8c12-393446d32830

**Comment by NoMerciBKK** [comment]
hopefully fixed

**Comment by xezon** [comment]
Is not fixed. Samples:

![shot_20240511_075551_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a745f510-3f79-4eb9-938d-2bd596ea9062)

![shot_20240511_075634_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/98cc82a2-3f0b-476b-87ea-9bfe75815cfd)

![shot_20240511_075702_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8d3923e0-8b48-4510-98a3-ff6cca6a067e)

**Comment by xezon** [comment]
## 11.05.2024

I tested all houses anew and these I have been able to self destruct. The others are ok.

![shot_20240511_144002_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9cfe1790-de2d-46ed-b246-26fd42dd6983)

![shot_20240511_144027_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/473aae6e-7472-46c1-aedc-517d7df3719b)

![shot_20240511_144102_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0ae20030-b31a-4182-97bc-e3915773868d)

![shot_20240511_144120_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bc366d3a-6a9c-4766-83d9-35fc1e250fb1)

![shot_20240511_144246_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3e40a61f-4c93-422c-8ca7-57bfd14d93c7)

![shot_20240511_144304_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e5f11bbb-ed19-4ba7-889a-903d83fe5d77)

![shot_20240511_144403_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/388edde1-d4d7-45c6-b37f-9d13c29ca256)

![shot_20240511_144421_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eb22a158-08fa-4a82-8368-f14176fc578b)

![shot_20240511_144500_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/49d2c28c-dec0-47c4-ab9b-505eeb70e7c2)

**Comment by NoMerciBKK** [comment]
you forcefire a mountain there so they will kill themselfe can only remove all buildings or the mountain an than id will look odd

**Comment by xezon** [comment]
Perhaps the distance between buildings and mountains can be increased a bit to reduce the splash damage probability?

**Comment by Jundiyy** [comment]
If the damage happens due to the buildings being too close to the mountains, I think that is acceptable, this could be splash damage. Same as when a Humvee is too close to a building or a Nuke Cannon near a mountain.

**Comment by xezon** [comment]
Ok.

**Comment by xezon** [comment]
Ok ignoring the mountains, I have been able to damage these buildings by shooting out of them and hitting the nearby building. I think the buildings cannot be this close.

![shot_20240515_200407_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/fb6d64df-efd3-43a4-a922-be8cb8ca17a5)
![shot_20240515_200516_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0532d26a-d420-47bf-868a-064a697f00b5)
![shot_20240515_200609_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9f06f8f2-eec6-48ef-bb0d-8b3b6b640ce1)
![shot_20240515_200621_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7fd12ed2-5d5d-4767-a1da-1cd43554c7b4)
![shot_20240515_200705_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d3a1415a-1ebe-498f-9e2d-0580f2f7e231)
![shot_20240515_200756_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d55b9f82-69f8-4b45-8474-d989bbf7d265)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
I tested new version and was able to kill the following:

![shot_20240522_203023_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/55705bf7-6a93-498a-9011-c10a77681a02)
![shot_20240522_203051_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5ab93bcb-9010-407c-b087-710be3439097)
![shot_20240522_203110_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2911263b-92e2-40c3-8a6c-c6eafc17aa8b)
![shot_20240522_203206_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ec9139b5-f669-4e3a-9180-455c4a1e62ac)
![shot_20240522_203315_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a2bbb173-3265-44ab-85bb-5eecbbcc7170)
![shot_20240522_203326_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f26639f5-b009-477d-9d7a-848ba4b7b3b4)
![shot_20240522_203349_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c4976a33-537b-48a3-a62d-59670adf1cb3)
![shot_20240522_203425_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ac9cfe90-cca1-442d-8c41-fc6431d061a0)

**Comment by NoMerciBKK** [comment]
updated version  22.05.2024 21:02

**Comment by xezon** [comment]
Looks ok now. We can close.
