### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] Units cannot move around 3 of 8 Oil Derricks

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#718]
## Observed behavior

Units cannot move around 3 of 8 Oil Derricks.

## Expected behavior

Units can move around 8 of 8 Oil Derricks or can move around 0 of 8 Oil Derricks.

### Cannot move around Oil Derrick (3)

![shot_20240509_120601_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dd690882-6bde-480d-a738-7f32749c1271)
![shot_20240509_120641_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ebfdbf23-1ab2-4573-9331-08cdb342842d)
![shot_20240509_120653_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ea7493c0-aec4-4688-a66a-accfad35f9be)

### Can move around the other Oil Derricks (5)

![shot_20240509_120707_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bed612c9-cd8b-4780-8536-1a2e77c95277)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
fixed
