### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] Flags of most Tech Buildings are not optimally visible

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#719]
## Observed behavior

Flags of most Tech Buildings are not optimally visible.

## Expected behavior

Tech Buildings are rotated by 90 degrees clockwise for optimal flag visibility.

## Screenshots

![shot_20240509_120734_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/98c694c1-9d1f-4f3a-a6f3-f6f37710d7db)

**Comment by NoMerciBKK** [comment]
updated
