### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] Supply Piles in center float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#720]
## Observed behavior

Supply Piles in center float above terrain.

## Expected behavior

Supply Piles sit tight on terrain.

## Screenshots

![shot_20240509_120754_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5568e85e-6161-45db-86ee-340077cde8dd)

**Comment by NoMerciBKK** [comment]
fixed
