### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] A few Oil Derricks clip into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#721]
## Observed behavior

A few Oil Derricks clip into terrain.

## Expected behavior

Oil Derricks sit tight on terrain.

## Screenshots

![shot_20240509_120845_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0b4deb70-b323-4382-8f2f-d4999f29d553)

![shot_20240509_120859_17](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/84694655-85a6-42af-8330-f4123fe704fb)

![shot_20240509_120910_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e25ec237-f4de-4011-9031-2bfde543ee78)

![shot_20240509_120935_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/114a0a9d-1923-45cd-824a-2be3f936a4de)

![shot_20240509_120949_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2e3e7deb-3fca-45e2-af74-63493bb5e82e)

**Comment by NoMerciBKK** [comment]
fixed
