### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] At least 4 of 8 bunkers self destruct when soldiers shoot out of them

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#722]
## Observed behavior

At least 4 of 8 bunkers self destruct when soldiers shoot out of them.

## Expected behavior

Houses take no damage when soldiers shoot out of it.

## Screenshots

![shot_20240509_121108_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c7aed298-3daa-40f0-a33f-5ad4e0d94222)

![shot_20240509_121251_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b769d348-b18b-466a-b062-08790d7b9e20)

![shot_20240509_121352_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/98a342a8-5860-4fa2-b783-65fdda23cfc9)

![shot_20240509_121559_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/223f8179-b008-4e79-8457-f353f07c9bdb)

**Comment by xezon** [comment]
Likely can be fixed by raising bunkers.

**Comment by xezon** [comment]
Was this addressed?

It still is possible to damage bunkers when shooting. Reproduced on 2:

![shot_20240510_160450_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b52b78ea-712b-42a6-b637-556f5d7865c0)

![shot_20240510_160604_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0dfd6375-e4f4-472c-a230-4a84c1290cec)

**Comment by xezon** [comment]
This can still kill itself:

![shot_20240511_142804_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf51034e-e49e-4a55-a2d4-7e24d36a975c)

**Comment by NoMerciBKK** [comment]
i didnt change anything there so 2/3 tests of yours this bunker didn t kill itselfe ^^

**Comment by xezon** [comment]
Yes. More time spent with testing can reveal more errors.
