### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] Supply Piles between bases have no consistent placements

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#725]
## Observed behavior

Supply Piles between bases have no consistent placements. China trucks will act differently on all of these.

## Expected behavior

Supply Piles have more consistent placements.

### 1

![shot_20240509_123524_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/10f23764-fe6e-4f71-b3ad-f7aef931d936)

### 2

![shot_20240509_123532_37](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c94e0906-f96c-4626-977f-1ea0691fee5b)

### 3

![shot_20240509_123543_38](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ea3116bc-432c-48d0-b327-a0aba732df39)

### 4

![shot_20240509_123552_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/11034434-95c7-4116-b9be-7c2ee32cccb4)

### 5

![shot_20240509_123604_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e8b65f7f-5072-48c6-8ba1-b09ef6198078)

### 6

![shot_20240509_123612_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dff3a9cf-2998-449c-a379-b660715c5347)

### 7

![shot_20240509_123623_42](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/7c29f1e6-ce55-467f-86ea-28e829da23b0)

### 8

![shot_20240509_123631_43](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6af54929-0fe0-483d-86bf-3effe5a3b260)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Looks good, except for this one which is missing the wave pattern

![shot_20240510_161320_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/61c2e6db-21ea-4b18-893d-a557bb477ae1)
