### ISSUE TITLE
[Candidate 4v4 Battle Between Them ZH v5] Audio emitters have no easing; and overlapping bird sounds?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#726]
## Observed behavior

Audio emitters have no easing. Also it sounds like there are overlapping bird sounds, aka intense double bird chirps?

## Expected behavior

Audio emitters fade nicely when scrolling over the map and bird sounds are pleasant.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/76696a35-9b63-454e-8716-1e587c51a2d6

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Sounds better. May I suggest to replace this type of bird sound with another though? It sounds bad because of the static noise in the sound.

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/90f5b6fb-d5ff-4227-b187-44e99f0f3f1a
