### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] Unusable boat houses show as POI on radar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#730]
## Observed behavior

Unusable boat houses show as POI on radar. There are 4 of them.

## Expected behavior

Unusable boat houses do not show as POI on radar.

### Unusable boat house on radar

![shot_20240509_150722_53](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b0b19020-f3d6-47a4-a753-dba817600197)

### Destroyed (rubble) boat house not on radar

![shot_20240509_150843_55](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/604c4741-68cd-4908-b5f1-6e858e637bf0)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
I had already seen it but somehow forgot to list it.
