### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] Oil Derricks clip into terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#731]
## Observed behavior

Oil Derricks clip into terrain.

## Expected behavior

Oil Derricks do not clip into terrain

## Screenshots

![shot_20240509_150909_56](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f8f57eda-528d-445b-a53a-3914554d494e)

![shot_20240509_150913_57](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f85e9c69-6e27-49be-bec6-e7dcabb7f17f)

![shot_20240509_151007_58](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5ed5ef45-fca7-4693-9789-4e13dc637085)

**Comment by NoMerciBKK** [comment]
fixed
