### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] Flags of Oil Derricks are not optimally in view

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#732]
## Observed behavior

Flags of Oil Derricks are not optimally in view.

## Expected behavior

Oil Derricks are rotated by 90 degrees clockwise to make their flags highly visible.

## Screenshots

![shot_20240509_151016_59](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/12e97c99-7cfc-438b-a5af-e4bffec94011)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
Could you please also rotate the Derricks at top and bottom of map?

![shot_20240510_180124_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b3a425b1-bc7e-4951-b7c5-1bba6336c856)
