### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] East boat house is damaged by occupants when shooting south

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#733]
## Observed behavior

East boat house is damaged by occupants when shooting south.

## Expected behavior

Houses take no damage when occupants shoot out of it.

## Screenshots

![shot_20240509_151213_60](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e5e0ab73-524d-4d43-b134-38ab1d80a1b4)

**Comment by NoMerciBKK** [comment]
fixed
