### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] GLA can build Supply Stash at the bottom coast, but not at the top coast

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#734]
## Observed behavior

GLA can build Supply Stash at the bottom coast, but not at the top coast

## Expected behavior

Mirrored Supply Docks offer equal space for building.

## Screenshots

![shot_20240509_151413_61](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e92b80ba-ed59-4546-8fdf-92de1131e3e7)

![shot_20240509_151416_62](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/af568135-0ff3-4601-99ca-23922ac77742)

**Comment by NoMerciBKK** [comment]
fixed

**Comment by xezon** [comment]
The top now allows for a slightly better build than the bottom. Can this be streamlined so this is about the same space?

![shot_20240510_181108_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/317ad28a-db69-4398-b196-8381b5fdd2c9)

![shot_20240510_181119_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b981762f-1e2d-4e57-9ae7-9347cedd5652)

**Comment by NoMerciBKK** [comment]
there is so much buildspace i dont think anybody would build a supply at this place and even if it is a tiny bit bigger we have other maps where the map is a-symetrical and defenitly less balanced

**Comment by xezon** [comment]
Top depot now has less room than bottom depot.

![shot_20240511_134520_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b9431795-69f8-487f-a198-0b42fb939b21)

**Comment by NoMerciBKK** [comment]
tbf thats not worth a blocker nobody will build there anyway and you can build on both sides a supply with mini difference

**Comment by xezon** [comment]
It depends. Rebuild there can happen when first supply is destroyed. And GLA is pushed a bit back. Then "turtleing" in can happen.

**Comment by NoMerciBKK** [comment]
yes i know but you can build on both sides a supply

**Comment by xezon** [comment]
> yes i know but you can build on both sides a supply

It depends on the situation. If the enemy built 2 tunnels near the Supply Dock, then it can be beneficial to build on the other side of the Supply Dock.

**Comment by NoMerciBKK** [comment]
fixed now you cant build any supply on this side anymore

**Comment by xezon** [comment]
Ok that also works.
