### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] Unit can not move past house near top coast, but can near bottom coast

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#735]
## Observed behavior

Unit can not move past house near top coast, but can near bottom coast.

## Expected behavior

Mirrored map layout offers equal movement opportunities.

### CANNOT MOVE THROUGH GAP

![shot_20240509_151656_63](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/d9dd51bd-61f2-482a-b629-4498c9717e49)

### Can move through gap

![shot_20240509_151711_64](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ab1cfcfb-c639-4c3b-ab78-cf8d2dd42c7e)

**Comment by xezon** [comment]
Can be fixed by moving boat house similar to how its on the mirrored coast.

**Comment by NoMerciBKK** [comment]
fixed
