### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] Flag of Artillery Platform is hidden

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#736]
## Observed behavior

Flag of Artillery Platform is hidden.

## Expected behavior

Flag of Artillery Platform is visible.

### Cannot see flag

![shot_20240509_151802_65](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/91bebedc-b6e6-47d0-a397-f363b461cb09)

### Mirrored Artillery Platform shows flag, but it is in shade.

![shot_20240509_151827_66](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3d2e12a7-52fc-40f0-84a4-97c3deeae373)

**Comment by xezon** [comment]
I suggest rotate both 90 degrees in either mirrored direction, then its likely ok.

**Comment by NoMerciBKK** [comment]
fixed
