### ISSUE TITLE
[Candidate 1v1 Proxy War ZH v1] Top center bunker can take damage when occupants shoot out of it

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#739]
## Observed behavior

Top center bunker can take damage when occupants shoot out of it.

## Expected behavior

Houses never take damage from occupants.

## Screenshots

![shot_20240509_172405_69](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0f04f567-0841-42fe-a768-c4216d514607)

**Comment by NoMerciBKK** [comment]
fixed
