### ISSUE TITLE
[Candidate 1v1 Proxy War ZH v1] Unit can get stuck near bottom Supply Dock

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#740]
## Observed behavior

Unit can get stuck near bottom Supply Dock. Somehow.

## Expected behavior

Units never get stuck.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/431d56e1-1626-4465-ab03-555f1d18995a

**Comment by NoMerciBKK** [comment]
fixed
