### ISSUE TITLE
[Candidate 1v1 Endboss ZH v2] Soldiers do not walk through fence openings correctly or at all

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#741]
## Observed behavior

Soldiers do not walk through fences correctly or at all.

## Expected behavior

Soldiers can walk through fence openings correctly.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a3525d3e-bc77-43c5-9fab-9a45e7cb325a

**Comment by xezon** [comment]
Perhaps the entrance is not wide enough? Could remove that one section close to the bridge to widen it.

**Comment by NoMerciBKK** [comment]
> Perhaps the entrance is not wide enough? Could remove that one section close to the bridge to widen it.

than they wouldnt walk through a 1 mm gab in the fence
