### ISSUE TITLE
[Candidate 1v1 Winding River Revised ZH v1] Beaches are impassable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#743]
## Observed behavior

Beaches are impassable. Even though the terrain does not look steep enough to communicate that.

## Expected behavior

Beaches are more passable or something clearly blocks units from moving there, such as indestructible tank barriers.

## Screenshots

![shot_20240511_120756_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c9fa3add-b505-429e-8bff-a3117ad0088a)

![shot_20240511_120816_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/15b66fb5-429c-4157-b8e7-df0bc3553e6a)

![shot_20240511_120852_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bdae8b24-074c-4601-afc2-867a7b3ab622)

![shot_20240511_120905_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c6eb112b-c9eb-4f87-9282-5125d239f56c)

![shot_20240511_120929_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/84cf9bb1-6699-4618-bf63-34f7bc92629b)

**Comment by FiReArM-ZH** [comment]
I forgot to remove impassable terrain.
Easy fix, will be done
