### ISSUE TITLE
[Candidate 2v2 Green Goon ZH v1] Farm house can take damage when shooting out of it

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#750]
## Observed behavior

Farm house can take damage when shooting out of it.

## Expected behavior

House does not take damage when shooting out of it.

## Screenshots

![shot_20240516_180337_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2f912438-3cde-4023-ba8f-d1b703390e6d)

**Comment by NoMerciBKK** [comment]
fixed hopefully

**Comment by xezon** [comment]
Still happens when shooting North East.

**Comment by xezon** [comment]
This bunker can also kill itself:

![shot_20240521_174148_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4dde6c81-f2e5-44f8-95c6-ad67d650cca1)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Farm house looks ok now.

Bunker can still be killed when shooting out of it.
