### ISSUE TITLE
[Candidate 2v2 Green Goon ZH v1] Base bunkers cannot shoot forward at some spaces

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#751]
## Observed behavior

Base bunkers cannot shoot forward at some spaces.

## Expected behavior

Base bunkers can perfectly shoot forward in 180 degrees cone.

### 1. Cannot shoot here

![shot_20240516_180831_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/47f16a70-a172-4965-a965-bde6e7c76f94)

### 2. Cannot shoot here

![shot_20240516_180917_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/9b1c1447-fb55-44ff-a0b8-9ce02ed5fd67)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Bunker 1 is not ok yet.
Bunker 2 seems to be ok.

**Comment by NoMerciBKK** [comment]
updated
