### ISSUE TITLE
[Candidate 2v2 Green Goon ZH v1] Cannot build perfect China Supply behind north west Supply Dock

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#752]
## Observed behavior

Cannot build perfect China Supply behind north west Supply Dock.

## Expected behavior

Can build perfect China Supply behind north west Supply Dock.

### Can build perfect China Supply (3)

![shot_20240516_181347_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/13ea6c67-55bc-46f2-ab33-e0f811e8c1ad)

![shot_20240516_182220_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ed19e274-bfb3-499a-8cab-b1562c0c7de9)

![shot_20240516_181149_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b3df05c9-a1eb-4544-9279-729c2c5b3cab)

### Cannot build perfect China Supply (1)

![shot_20240516_181427_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a10eaad8-6841-45e5-a9ff-5f6728614315)

**Comment by NoMerciBKK** [comment]
updated
