### ISSUE TITLE
[Candidate 1v1 Sakura Forest II ZH v1] Tree partly covers flag of Oil Refinery

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#754]
## Observed behavior

Tree partly covers flag of Oil Refinery.

## Expected behavior

Tree does not cover flag of Oil Refinery.

## Screenshots

![shot_20240516_191748_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/cc83630f-cc9a-4429-b1ad-e8a340394226)

**Comment by NoMerciBKK** [comment]
as designed

**Comment by xezon** [comment]
As designed.
