### ISSUE TITLE
[Candidate 1v1 Sakura Forest II ZH v1] Impassable terrain behind Supply Piles will prevent building

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#755]
## Observed behavior

Impassable terrain behind Supply Piles will prevent building.

## Expected behavior

Flat looking terrain can be built on. Supply Piles can be moved closer to mountain.

## Screenshots

![shot_20240516_192105_18](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/539a49be-f30a-4412-acde-f7f0992203ec)

![shot_20240516_192130_19](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/6c46c498-19bf-4813-b644-5e657a564998)

**Comment by NoMerciBKK** [comment]
as designed

**Comment by xezon** [comment]
As designed.
