### ISSUE TITLE
[Candidate 1v1 Sakura Forest II ZH v1] Units can drive around Supply Piles near Artillery Platform on one side only

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#756]
## Observed behavior

Units can drive around Supply Piles near Artillery Platform on one side only.

## Expected behavior

Mirrored Supply Piles offer equal unit mobility opportunities.

### Unit cannot move around

![shot_20240516_192227_20](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b041b7d0-c99d-4dec-abe7-fe15cd67b9f4)

### Unit can move around

![shot_20240516_192231_21](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/e24bd008-80e9-4fe5-829b-c351d10a0e8f)

**Comment by NoMerciBKK** [comment]
updated

**Comment by xezon** [comment]
Functionality wise its identical now, but visually it looks as if a unit can pass there, while it cannot pass. Perhaps the mountain can be moved closer to the Supply Piles like on the other side of the map?

![shot_20240521_174944_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2da041a1-f08c-4603-9b90-b9aa132ac8bd)

**Comment by NoMerciBKK** [comment]
tbh i d leave it now like it is yes its a tiny detail but i m fine with it

**Comment by xezon** [comment]
I recommend to fix it. When people see a gap they eventually want to move through there. Imagine a critical GLA technical trying to go there. Then player cannot go, loses it, loses the game. It could make a big difference in rare events.

**Comment by NoMerciBKK** [comment]
updated
