### ISSUE TITLE
[Candidate 1v1 Sakura Forest II ZH v1] Space behind Supply Docks has unequal width

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#757]
## Observed behavior

Space behind Supply Docks has unequal width. North west Supply Dock is a bit narrower at one side.

## Expected behavior

Mirrored Supply Docks offer about equal space for unit mobility.

## Screenshots

![shot_20240516_192557_22](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0c595fa9-e31f-4c0e-bde9-80b92b77c4f6)

![shot_20240516_192605_23](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/00cd0351-b892-43f7-ad61-49f58a5ebfad)

**Comment by NoMerciBKK** [comment]
updated with same passible width on both sides
