### ISSUE TITLE
[Candidate 2v2 Forgotten Factory ZH v2] Asphalt has cow-skin-like patterns

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#759]
## Observed behavior

Asphalt has cow-skin-like patterns. It looks unexpected for an industrial site.

## Expected behavior

Asphalt looks more uniform.

## Screenshots

![shot_20240517_181803_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8977debd-aada-47d0-946e-5fb89aacaedb)

**Comment by xezon** [comment]
This lighter contrast looks good on the other hand.

![shot_20240517_183203_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5b1b4a61-138f-4f2e-bac6-1e032c8cccf1)

**Comment by NoMerciBKK** [comment]
thats on purpose so as designed (rain puddles)

**Comment by xezon** [comment]
As designed
