### ISSUE TITLE
[Candidate 2v2 Forgotten Factory ZH v2] Units can move around Repair Bay on one side, but not the other side

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#760]
## Observed behavior

Units can move around Repair Bay on one side, but not the other side.

## Expected behavior

Mirrored Tech Buildings offer equal unit mobility opportunities.

### Can move around

![shot_20240517_181858_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/77c5a361-27fa-4ddb-864b-e445d951c309)

### Cannot move around

![shot_20240517_181911_4](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a2738cc0-ca94-4124-9eea-c674537067cb)

**Comment by NoMerciBKK** [comment]
updated
