### ISSUE TITLE
[Candidate 2v2 Forgotten Factory ZH v2] Supply Dock at south west is not selectable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#761]
## Observed behavior

Supply Dock at south west is not selectable. It shows no money when hovered. It cannot be attacked.

## Expected behavior

Supply Dock is selectable.

## Screenshots

![shot_20240517_182424_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/27ec2080-4863-4710-af7b-a908b001f93d)

**Comment by NoMerciBKK** [comment]
fixed
