### ISSUE TITLE
[Candidate 2v2 Forgotten Factory ZH v2] Map hosts variety of bird sounds but no trees

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#762]
## Observed behavior

Map hosts variety of bird sounds but no trees. Also it is at night. This does not match. Toxic seagulls perhaps make sense by the toxic canals.

## Expected behavior

Map has no or less bird sounds because it is a toxic industrial site at night. Dogs and talking people may fit better.

## Videos

https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/26459cdd-fe09-4eb7-95e2-f0e82efe791b

**Comment by NoMerciBKK** [comment]
should be a cloudy bad weather setting not night

**Comment by xezon** [comment]
Bird sounds. Birds typically live in nature, aka around trees.

**Comment by NoMerciBKK** [comment]
Amseln, Blaumeisen, Mauersegler, Stadttauben, Zaunkönige, Wanderfalken -> Birds in citys

**Comment by xezon** [comment]
But would they live in a toxic industrial site? There would be no food, but bad air. It is not the place for birds to prosper.

**Comment by NoMerciBKK** [comment]
well in spandau industrial area you ll find them :D

**Comment by xezon** [comment]
As designed
