### ISSUE TITLE
[Candidate 3v3 Glacier 6 ZH v1] Dust particles emit from center Oil Derrick

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#763]
## Observed behavior

Dust particles emit from center Oil Derrick. It looks strange.

## Expected behavior

No particles emit from center Oil Derrick.

## Screenshots

![shot_20240517_193035_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/f20a1b56-f577-4ebd-aeea-c87f6ff65d7b)

**Comment by NoMerciBKK** [comment]
take as designed

**Comment by xezon** [comment]
As designed
