### ISSUE TITLE
[Candidate 3v3 Glacier 6 ZH v1] Soldiers in house shooting west will hit the terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#765]
## Observed behavior

Soldiers in house shooting west will hit the terrain. This only happens with 1 of 3 houses.

## Expected behavior

Soldiers in house shooting west will hit their target.

## Screenshots

![shot_20240517_200547_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/0e0de90b-6efe-47fe-80ae-454560103117)

**Comment by NoMerciBKK** [comment]
updated
