### ISSUE TITLE
[Candidate 3v3 Glacier 6 ZH v1] Units can be air dropped on mountain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#767]
## Observed behavior

Units can be air dropped on mountain.

## Expected behavior

Units cannot be air dropped on mountain.

## Screenshots

![shot_20240517_203148_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/357b9804-dbeb-4216-9382-aa245d246dbc)

**Comment by NoMerciBKK** [comment]
fixed
