### ISSUE TITLE
[Candidate 4v4 Battle for Reach ZH v1] 2 Oil Derrick flags are partly or fully covered by foliage

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#769]
## Observed behavior

2 Oil Derrick flags are partly or fully covered by foliage.

## Expected behavior

Flags of Tech Buildings are not covered by foliage towards default camera rotation.

## Screenshots

![shot_20240518_083655_6](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4ba4fe71-a384-4e0a-8c73-62e07e58fac8)

![shot_20240518_083707_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/a0282a39-6550-439b-a312-86b4d949ea9e)

![shot_20240518_083719_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/133fa889-340f-44d8-84c5-7c5c39bdf183)

**Comment by NoMerciBKK** [comment]
fixed
