### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Oil Derrick does not sit on terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#776]
## Observed behavior

Oil Derrick does not sit on terrain.

## Expected behavior

Oil Derrick does sit tight on terrain.

## Screenshots

![shot_20240518_122804_26](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3ca0d53f-cdf8-4692-a2a0-de1a21995f27)

**Comment by NoMerciBKK** [comment]
fixed
