### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Tank Trap and Burning Barricade are selectable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#777]
## Observed behavior

Tank Trap and Burning Barricade are selectable.

## Expected behavior

Tank Trap and Burning Barricade are not selectable on the battle field.

## Screenshots

![shot_20240518_123601_28](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/818afdab-7622-420d-a2c4-167f4d9f6a0a)

![shot_20240518_123604_29](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/59d9bdad-656d-4add-ac5f-3a4280dbf659)

**Comment by xezon** [comment]
Not sure if should be blocker. Depends on how annoying this can become in battle situations.

**Comment by NoMerciBKK** [comment]
those are destructible buildings with a bit more hp than oneshot thats why i left the hp bars on

**Comment by xezon** [comment]
We have other Ranked Maps with Tank Traps and none show health bars.

**Comment by NoMerciBKK** [comment]
they are also indestructible on other maps

**Comment by xezon** [comment]
I may be mistaken. On Fort Payne and Diamonds Edge the Tank Traps are also selectable.

**Comment by xezon** [comment]
As designed.
