### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Burning Barricade has a lot of health

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#778]
## Observed behavior

Burning Barricade has a lot of health. Is unexpected.

## Expected behavior

Burning Barricade has a reasonable amount of health to clear.

## Screenshots

![shot_20240518_123620_30](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/8729cbf9-b781-4f5a-bcbb-cf79d4d401e5)

**Comment by NoMerciBKK** [comment]
thats default by the game

![image](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/146106317/b8dab2fd-7435-4dd9-93d4-85a462c74550)

**Comment by xezon** [comment]
As designed.
