### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Some flags of Tech Buildings are in shade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#779]
## Observed behavior

Some flags of Tech Buildings are in shade. This makes them more difficult to see.

## Expected behavior

Flags are not in shade for best visibility. Light can be optimized by rotating the sun in relation to default camera angle.

## Screenshots

![shot_20240518_123903_31](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/eb9f29e2-d58d-4f23-b074-13c794ea9ba1)

![shot_20240518_122940_27](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b7982f99-2c6e-41f7-9b0b-ff4bb02778b4)

**Comment by NoMerciBKK** [comment]
as designed

**Comment by xezon** [comment]
As designed.
