### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Some flags of Tech Buildings are not perfectly in view

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#780]
## Observed behavior

Some flags of Tech Buildings are not perfectly in view.

## Expected behavior

Flags of Tech Buildings are perfectly in view. Can be fixed by optimizing rotation.

## Screenshots

![shot_20240518_122743_25](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/ebf02341-fd98-4f5f-ad1e-f6ec5dd16662)

**Comment by NoMerciBKK** [comment]
updated
