### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Bottom Supply Dock offers less build space than top Supply Dock

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#781]
## Observed behavior

Bottom Supply Dock offers less build space than top Supply Dock.

## Expected behavior

Mirrored Supply Docks offer about equal build space.

## Screenshots

![shot_20240518_124136_32](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dddbfaa5-5787-4a73-b473-adec0c50ee4f)

![shot_20240518_124142_33](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/3369fe83-c069-453d-a7e0-0d7b71863c08)

**Comment by NoMerciBKK** [comment]
updated
