### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Units cannot move around South hangar, but can move around North hangar

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#782]
## Observed behavior

Units cannot move around South hangar, but can move around North hangar.

## Expected behavior

Mirrored hangars offer equal unit mobility opportunities.

### Cannot pass

![shot_20240518_124453_35](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2070e4bd-57ec-4688-9417-f8f3b37d616f)

### Can pass

![shot_20240518_124502_36](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/68f7451c-4bc8-403d-b35a-033256b56cac)

**Comment by NoMerciBKK** [comment]
updated
