### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Rocks reach into map border

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#783]
## Observed behavior

Rocks reach into map border.

## Expected behavior

Rocks do not reach into map border.

## Screenshots

![shot_20240518_125005_40](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/98ab6f9d-4cdc-4b71-a9d6-441096f1da9f)

![shot_20240518_125031_41](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/bf770e03-a186-4e79-8680-06c3ed12ab10)

**Comment by NoMerciBKK** [comment]
updated
