### ISSUE TITLE
[Candidate 4v4 Twisted Treeline ZH v1] Rocks float above terrain

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#784]
## Observed behavior

Rocks float above terrain.

## Expected behavior

Rocks sit tight on terrain.

## Screenshots

![shot_20240518_124827_39](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c7ae2181-c8f5-402e-b3f3-b9135f79e682)

**Comment by NoMerciBKK** [comment]
updated
