### ISSUE TITLE
[Candidate 2v2 Forgotten Factory ZH v2] Chinook reaches into crane when collecting supplies

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#786]
## Observed behavior

Chinook reaches into crane when collecting supplies.

## Expected behavior

Cranes are not located at the center of Supply Docks.

## Screenshots

![shot_20240521_173242_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/67e81c69-5162-40a2-ad33-c68ddc9458f3)

**Comment by Jundiyy** [comment]
Could be moved, although same could happen since Chinooks don't always collect from the middle, many factors.

**Comment by NoMerciBKK** [comment]
as designed

**Comment by xezon** [comment]
As designed.
