### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Bunkers can take damage when soldiers shoot out of them

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#787]
## Observed behavior

Bunkers can take damage when soldiers shoot out of them.

## Expected behavior

Bunkers take no damage when soldiers shoot out of them.

## Screenshots

Note that in images, the soldiers moved away after destroying their bunkers to continue shooting at target.

![shot_20240521_212520_7](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4f572d30-a0c7-40fc-b8fe-b7eacbdd834f)

![shot_20240521_212549_8](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/02b3dc62-d529-4bf9-86c5-d0de36720706)

![shot_20240521_212707_9](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1ca0de56-2a63-4ce5-ab74-0a2f69a7f4f4)

![shot_20240521_212718_10](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/1fa6bca2-e50b-4493-b912-c08ba267a93f)

**Comment by cncHD** [comment]
fixed

**Comment by xezon** [comment]
Is still possible on these 2. Other 2 appear to be ok.

![shot_20240613_181251_2](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/dff97674-ea06-4a5b-875d-be04191aa186)

![shot_20240613_181326_3](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/2044adf0-89a6-4d15-b4e1-6a6b8e8b0dac)

**Comment by cncHD** [comment]
Bunkers removed and replaced with Guard Towers. I will call this fixed
