### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Supply Docks and Supply Piles have unequal build space

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#789]
## Observed behavior

Supply Docks and Supply Piles have unequal build space.

## Expected behavior

Supply Docks and Supply Piles have equal build space.

## Screenshots

![shot_20240521_222824_11](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/905dd585-ff14-4220-932f-0443887b4f8d)

![shot_20240521_222829_12](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/c244eadf-b947-43dc-b2e1-b09aace1aca2)

![shot_20240521_222832_13](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5d5a15fb-0520-4adb-92fc-01b479174dcb)

![shot_20240521_222835_14](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/b2b226d6-33aa-451b-8168-6411d3fb66ed)

![shot_20240521_222837_15](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/abec1a99-11b6-49f6-a858-c86e4ba53473)

![shot_20240521_222840_16](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/5c836364-1693-4a80-ad20-29b14ff5b200)

**Comment by cncHD** [comment]
Fixed

**Comment by xezon** [comment]
Fixed. The south mid Supply Dock is a bit tight, but it is possible to build perfect Supply Center.

![shot_20240613_181956_5](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/4435c34e-307a-4a12-92dd-d551cb45c113)
