### ISSUE TITLE
[Candidate 3v3 Tournament C ZH v1] Soldiers have difficulties entering 1 of 4 bunkers from ramp

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#792]
## Observed behavior

Soldiers have difficulties entering 1 of 4 bunkers from ramp. Some or all of them do not enter the bunker and stop moving at the cliff.

## Expected behavior

Soldiers can enter all bunkers from the ramp.

## Screenshots

![shot_20240613_181211_1](https://github.com/TheSuperHackers/GeneralsRankedMaps/assets/4720891/91284595-b4cd-4d49-b81e-2bff5e9c39c0)

**Comment by cncHD** [comment]
Bunkers removed and replaced with Guard Towers. I will call this fixed
