### ISSUE TITLE
[Candidate 2v2 Drowning Horses V1] AI is not collecting from supply piles

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsRankedMaps#93]
**Issue Description**
AI is not collecting from supply piles.

**Expected behavior**
AI collects from all supplies.

**Screenshots**
![shot_20210323_135129_11](https://user-images.githubusercontent.com/4720891/112149571-6dbcf500-8bdf-11eb-8389-418f3103b17a.jpg)

![shot_20210323_135142_12](https://user-images.githubusercontent.com/4720891/112149590-70b7e580-8bdf-11eb-8741-e42493d62643.jpg)

**Comment by Jundiyy** [comment]
Sadly this isn't something easy to fix, it's ZH scripting, not the mapper doing something wrong. More detail in the staff room.

**Comment by xezon** [comment]
Ok. Is not a blocker bug. Minor issue.
